### ISSUE TITLE
Shipping cost not applied while checking out with Apple Pay

### ISSUE THREAD

**Issue by malmualla** [woocommerce/woocommerce-gateway-stripe#1793] opened 2021-09-06 22:19 UTC
**Describe the bug**
When using Apple Pay to check out, while loading Shipping cost shows as ( 30.00 ) which is correct and perfect, suddenly it changes to ( 0.00 )

**Screenshots**
While Loading:
![IMG_7A3B7AFDB7C3-1](https://user-images.githubusercontent.com/81653743/132263149-ace82a94-6bcd-4b0b-b0e1-c0c7c8dcf5cb.jpeg)
After Loading
![IMG_150FA2DB2DA3-1](https://user-images.githubusercontent.com/81653743/132263165-c0bf0208-4107-40b0-9b58-2e3481a7e76a.jpeg)

**Environment (please complete the following information):**
 - WordPress Version : 5.8 
 - WooCommerce Version : 5.6.0
 - Stripe Plugin Version : 5.4.1
 - Browser Safari on Mac OS + IOS 

**Additional context**
Shipping Method is showing and selected but rate not reflected in shipping cost

**Comment by dougaitken** [comment] 2022-07-29 15:32
Hey @malmualla 

I appreciate some time has passed since the original comment, thanks for your patience. 

It is possible that this issue has been fixed by a more recent release as I’ve been unable to replicate the issue you described using the latest release of the core WooCommerce plugin and the [WooCommerce Stripe Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/). 

<img width="632" alt="apple_pay_shipping_rate" src="https://user-images.githubusercontent.com/52214/181793664-63a0cadc-48c7-4934-ab5c-be3cf19c4468.png">

As I’m unable to reproduce this, I’m marking this Issue as Closed. Please do open a new one if you are able to reproduce this again.

**Closed as completed by dougaitken** 2022-07-29 15:32 UTC
Labels: component: payment request buttons, needs repro
