### ISSUE TITLE
webhook failure resulting in payment failure

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-stripe#2249] opened 2021-12-20 00:35 UTC
**Describe the bug**
In 4617767-zen the user reports that they are experiencing failed payments. The Stripe logs indicate that:

```
====Stripe Version: 5.9.0====
====Start Log====
Canceled webhook abort: Order was not processed by Stripe: 4596
====End Log====
```

I'm not clear if this is the same as #1196 

**To Reproduce**
1. I guess use Bancontact

**Expected behavior**
That a valid payment results in an order marked as paid rather than canceling for non-payment.

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - Stripe Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**

**Comment by cesarcosta99** [comment] 2021-12-21 12:27
@WillBrubaker I've performed a [checkout with Bancontact test](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#checkout-with-bancontact) on a fresh WP and plugin installations with both the [new checkout experience](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-new-checkout-experience-(UPE)) enabled/disabled and the two tests passed without any kind of errors. I'd appreciate if the user could perform a conflict test and provide more details so we can try to reproduce it.

**Comment by Hotpuppy** [comment] 2022-02-08 04:01
I have the same issue where a small number of orders timeout and the payment fails to post back.  

In reviewing the transactions there is a pattern.  The customer has a payment failure.  Either bad CVC, bad AVS, or just a charge decline.  They typically correct this in a couple of minutes and the charge completes successfully on Stripe.

In WC the transaction shows as "pending payment" and then "failed" because the payment did not post back in a timely manner.  These either require a manual correction in WC, or a refund in Stripe.  Often the customer is upset as well.  Especially if it's not manually caught before they get their statement.  My charges are all reasonably small ($6-$10) but it seems like there should be a more graceful way to handle these payment situations.

I found a stackoverflow post that suggested the timeout is set to 60 seconds in the PHP code of the plugin.  I have not personally verified this, but I'm mentioning it in case it's helpful.

**Comment by wjrosa** [comment] 2024-12-10 13:52
Hey @WillBrubaker ! I also tried to reproduce the issue with no success. As @cesarcosta99 said, maybe the merchant is having a conflict issue with other extensions. I will be closing this for now. Let us know if you are able to reproduce it or if you have more information that could help us do so.

**Closed as completed by wjrosa** 2024-12-10 13:52 UTC
Labels: priority: high, type: bug
