### ISSUE TITLE
Using Chrome / Android / Google Pay for addresses in Japan, etc. fail validation

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-stripe#568] opened 2018-03-06 13:07 UTC
_The following description added by @v18 2021-02-25:_

Noting that there are two separate issues here:

**1 - Unrecognized address field** - maybe not reproducible?
Receiving an address field that doesn't match what WooCommerce expects (e.g. "Shipping prefecture is not valid" - [screenshot](https://d.pr/qnDktM)). This has happened with addresses in Japan and Hong Kong.

I've not been able to reproduce - noted in this comment below: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/568#issuecomment-785613972.

**2 - Missing address field**

Some WooCommerce-required fields are not being asked in the shipping fields in Chrome. For example, as of 202-02-25, Google does not ask for a city address field in Chrome (`chrome://settings/addresses`). Here's what the form looks like:

<img width="457" alt="Screen Shot 2021-02-25 at 1 48 23 PM" src="https://user-images.githubusercontent.com/11487924/109105026-75b87f00-7770-11eb-9559-21922038d93b.png">

However, the city field is required by WooCommerce. When using a Japanese address with Google Pay, this is the error I see:

<img width="352" alt="error - city is required" src="https://user-images.githubusercontent.com/11487924/109105107-9a145b80-7770-11eb-88e9-f8f41968592e.png">

Going to keep these issues together now since Roy [mentioned earlier](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/723#issuecomment-421010326) that it's the same type of issue. Note: I haven't verified the cause of the each issue in the gateway

----

#### Affected ticket(s)

998457-zen

#### What I expected

To checkout with Android Pay using a shipping address in Japan.

#### What happened instead

The Android Pay address form only allows to choose a prefecture in Japanese characters (i.e. `東京都`). However, when I select one of the options and place the order, I'm getting an error message that Shipping Prefecture is not valid:

![Screenshot](http://cld.wthms.co/qnDktM+)
Screenshot: http://cld.wthms.co/qnDktM

Reproduced on Pressable, with Stripe 4.0.7 & WC 3.3.3

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by madeincosmos** [comment] 2018-03-06 14:58
I can test with Japanese too, but shouldn't it be possible to ship to Japan even from other countries / sites in other languages?

**Comment by roykho** [comment] 2018-03-06 15:01
So the issue I am assuming is WC doesn't accept Japanese characters for prefecture when its in English. I don't think this is something we can fix.

**Comment by roykho** [comment] 2018-03-22 03:36
I looked a bit more into this today and confirmed that WC Japanese prefectures are in English and Chrome Pay is trying to pass Japanese characters. Note that Apple Pay does not have this issue.

Chrome Pay has other quirkiness as well such as states in Ireland are in a different name than what WC is expecting so we added normalization for that. It seems we need to add one for Japan as well. It then becomes quite a mess to upkeep. I am sure there are other countries that have same issues that we have not been informed yet.

**Comment by madmath** [comment] 2018-04-25 12:55
Hello, 
Google Chrome team here. We have tried Google Pay + Japanese addresses on our test site (https://polykart.store) and it seems to work as expected. If you think of a way we can improve our browser implementation, please let us know.

**Comment by updistribute** [comment] 2018-06-11 12:16
Hi all,

I believe I'm running into similar issues, only that the address is a Hong Kong address.

Here's what I found --
Customers paid using Google Pay with a Hong Kong shipping address. Google pay worked as expected but failed during checkout. At checkout, an error is raised against the “state” field of shipping address.

Unlike USA address, there's no such thing as state in Hong Kong. So in Google Pay, "State" is not an option. Instead, there is an "Area" field.

About our website:
- The site language is Traditional Chinese.
- We tested the error using android phones in English and Chinese.
- We had customers paying with credit card & Apple pay. Both methods worked fine.

Hope you guys can help. Appreciate in advance!

Here are the screenshots::
-------------------------------
Step 1: Filling out shipping address in Google Pay
![androidpayissue-step000](https://user-images.githubusercontent.com/40169332/41230162-50f100f0-6db1-11e8-9a68-94713bda8944.jpg)

Step 2: Checking Out
![androidpayissue-step1](https://user-images.githubusercontent.com/40169332/41230163-51207d30-6db1-11e8-8557-f4df0a702121.jpg)

Step 3: Error
![androidpayissue-step2](https://user-images.githubusercontent.com/40169332/41230164-514ceda2-6db1-11e8-95f2-597c4df0ea80.jpg)

Step 4: Woocommerce display error message. "Shipping State is not valid. Please enter one of the following: [options in Chinese]" (which basically are the same values enabled in the "Area" field)
![androidpayissue-step3](https://user-images.githubusercontent.com/40169332/41230166-517fc010-6db1-11e8-87db-469d28231599.jpg)

**Comment by roykho** [comment] 2018-09-13 14:34
Just leaving a note. From my testing today, this issue only happens when I am using Chrome on the Android phone. This does not happen in Chrome desktop. It seems the prefecture dropdown is in the native language of the country selected when using Android but in Chrome desktop, the selection is in English.

**Comment by damiannep** [comment] 2020-02-28 05:25
Another case of this in 2730189-zen, with a Hong Kong credit card.

**Comment by solomonhk** [comment] 2020-02-28 08:31
I have exactly the same problem with Google Pay & Apple Pay.  Is there any solution?

**Comment by dougaitken** [comment] 2020-08-04 12:48
I tested this after this forum thread - https://wordpress.org/support/topic/error-for-google-pay/

This is more widespread than "Android Pay" as originally stated. 

I've tested this in three Chrome-based browser - the results are the same - the address details for Japan don't have a city field. However, the WooCommerce core checkout fields have city as a required field.

**How to replicate**

Payment Request button:
* go to `edge://settings/addresses` or `chrome://settings/addresses` or `brave://settings/addresses`
* Add new address
 * Set country as Japan
 * Note only `Country/region` / `Street address` / `Prefecture` are mentioned
* Try to check out with the Payment Request button, it will fail with a message about the shipping/billing city

Working checkout
* Add a product to cart then head to Checkout
* Use the same address but fill in the main WooCommerce checkout fields
* Use Stripe as the payment gateway
* Not the order will process as expected

> Google Chrome team here. We have tried Google Pay + Japanese addresses on our test site (https://polykart.store) and it seems to work as expected. If you think of a way we can improve our browser implementation, please let us know.

@madmath I just tested and the reason for this is your demo store isn't running on WooCommerce so it isn't a like for like replication. I just placed a test order `woo@woo.local` and it was successful, that's why I figured it out.

Do you or anyone have any contact with the Chrome team that could look into why City isn't part of the address fields for Japan? This isn't Chrome only but browsers based on Chrome such as Edge and Brave. 

Looking at various posts, the city is part of the address structure for Japanese addresses i.e. [Japanese addressing system on Wikipedia](https://en.wikipedia.org/wiki/Japanese_addressing_system#Address_order).

Moving to High as this impacts all Japanese customers using Payment Request buttons/APMs on WooCommerce sites.

FYI - Apple Pay isn't affected since AP has a field for County/City when adding an address.

**Comment by v18** [comment] 2021-02-25 05:02
I'm not able to reproduce the error with a Hong Kong address. I was able to use the following address during a test checkout and it worked:

<img width="275" alt="Screen Shot 2021-02-25 at 2 01 10 PM" src="https://user-images.githubusercontent.com/11487924/109105846-0c397000-7772-11eb-8824-f73ce6421d03.png">

@updistribute - are you still having trouble with addresses in Hong Kong when checking out?

**Comment by ricardo** [comment] 2021-03-03 21:38
> are you still having trouble with addresses in Hong Kong when checking out?

@v18, I was able to reproduce it:

![image](https://user-images.githubusercontent.com/5509901/109871040-84f46c80-7c49-11eb-8932-82546bced171.png)

This error can happen if you have WooCommerce translated (to Chinese in this case).

**Why it happens:**

WC core has this [states.php](https://github.com/woocommerce/woocommerce/blob/trunk/i18n/states.php) file, which provides an array of state codes and *translated* state values. We use this list to match the state value with the provided state from Chrome so we can provide the right state code for WC when calculating shipping methods.

E.g Chrome provides a state dropdown with the value of `Hong Kong Island`, but we expect `香港島` because the website is [translated to Chinese](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/zh-hk/default/?filters%5Bterm%5D=Hong+Kong+Island&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc).

I was digging a little bit and I found we have infinite variations of state translations across multiple languages, like `Isla de Hong Kong` in Spanish or `Ilha de Hong Kong` in Portuguese, making it impossible to match with Chrome's predefined values with the current approach allowed by WooCommerce.

**Comment by ricardo** [comment] 2021-03-03 21:38
We have two separate problems in this issue and I don't think any of them should be fixed in Stripe.

**For the missing City field in Japan:**

I don't think we can fix this in Stripe. We should probably open an issue in WooCommerce to see if we can make that field optional if the country is JP.

**For the state inconsistencies in HK and other countries:**

I can think of 2 different approaches:

1. We could open another WC core issue, asking to change the behavior of that states list, passing a parameter that enforces the text to not be translated, or even better, ask for the list to be compatible with [libaddressinput](https://github.com/google/libaddressinput), which is used by Chromium. Many gateway plugins could benefit from that now as more and more plugins are implementing the Payment Request API standard.

2. We could copy the states list from WC, removing the translations and adapting what's different from [libaddressinput](https://github.com/google/libaddressinput). I'm not a fan of fixing this in Stripe, because we we'd need to maintain this list and every plugin that implements Payment Request buttons would need to implement a similar list to properly fix these kinds of problems. This is basically the idea of #1477.

Ideally, Chrome should not use that dropdown field, just like Safari and Brave. The funny part is that they use that inconsistently. You don't have the dropdown when you manually add an address in `chrome://settings/addresses`, but you do have the dropdown in the Payment Request dialog. 🤷🏻‍♂️

@v18 , do you agree with opening these issues and (hopefully) having this issue fixed in WC core?

**Comment by v18** [comment] 2021-03-06 05:23
@ricardo - I agree about the JP address issue. And let's try approach # 1 for the other address problems.

**Comment by ricardo** [comment] 2021-03-26 21:21
Closing this because the issue with Japan will be fixed in [woocommerce#29373](https://github.com/woocommerce/woocommerce/issues/29373) and the issue with Hong Kong is a separate problem which is better described in #1477.

**Closed by ricardo** 2021-03-26 21:21 UTC
Labels: bundle: payment request buttons, component: payment request buttons, priority: high, status: blocked, type: bug
