### ISSUE TITLE
The Automattic\WooCommerce\Admin\API\Options::get_options function is deprecated since version 3.1. 

### ISSUE THREAD

**Issue by jacoswan** [woocommerce/woocommerce-gateway-stripe#2371] opened 2022-06-25 07:55 UTC
## Describe the bug

The error above is recorded in server-level logs when accessing Stripe settings. The notice above are recorded in server error logs when using specifically Stripe, hence reporting it here. If it's still a core issue, I'm happy to move it or reopen the original report. 

I could not recreate it on a local development site, but in addition to the user's report from Siteground sites, I could recreate it on both a Pressable and WPCOM Biz site (environments below). 

A similar (the same?) issue was [described in this core report](https://github.com/woocommerce/woocommerce/issues/32863) and subsequently fixed [and rolled out in 6.6.0 here](https://github.com/woocommerce/woocommerce/pull/32891).  

## To Reproduce
1. Install and activate WooCommerce and Stripe
2. Navigate to the WC > Settings > Payments > Stripe
3. Stripe doesn't have to be Enabled, just visiting the settings page causes the error. 
4. View the server error_logs, it seems to generate two lines everytime those settings are accessed. 

```
[25-Jun-2022 07:38:44 UTC] The Automattic\WooCommerce\Admin\API\Options::get_options function is deprecated since version 3.1.
[25-Jun-2022 07:38:44 UTC] The Automattic\WooCommerce\Admin\API\Options::get_options function is deprecated since version 3.1.
```

## Expected behavior

No deprecation notices

## Actual behavior
Deprecation notice 

#### From the report in 5322082-zen where the error was recreated: 
 - WordPress Version: 6.0
 - WooCommerce Version: 6.6.1 
 - Stripe Plugin Version: 6.4.1
 - Browser [e.g. chrome, safari] and Version: n/a
 - Any other plugins installed: No
- PHP version: 7.4.30
- Server: Apache

#### Initial test on localhost, could not recreate: 
 - WordPress Version: 6.0
 - WooCommerce Version: 6.6.1 
 - Stripe Plugin Version: 6.4.1
 - Browser [e.g. chrome, safari] and Version: Chrome, Firefox
 - Any other plugins installed: No
- PHP version: 8.1.5
- Server: Apache

#### Test 2 on Pressable:
 - WordPress Version: 6.0
 - WooCommerce Version: 6.6.1 
 - Stripe Plugin Version: 6.4.1
 - Browser [e.g. chrome, safari] and Version: Chrome, Firefox
 - Any other plugins installed: (Drop-ins) advanced-cache.php, object-cache.php
- PHP version: 8.1.7
- Server: nginx

### Test 3 on WPCOM (Biz): 
 - WordPress Version: 6.0
 - WooCommerce Version: 6.6.1 
 - Stripe Plugin Version: 6.4.1
 - Browser [e.g. chrome, safari] and Version: Chrome, Firefox
 - Any other plugins installed: Akismet, Jetpack, WooCommerce Stripe Gateway,  WooCommerce, (drop ins) advanced-cache.php, object-cache.php
- PHP version: 7.4.30
- Server: nginx

**Comment by EjayhanFernandes** [comment] 2022-06-28 11:41
The user here is experiencing the same issue 5331858-zen.

**Comment by ricardo** [comment] 2022-07-01 18:07
Found out the problem comes from [this snippet](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/9a30800f2aab8e280b61a4f7ed97885f5ba81a56/client/settings/customization-options-notice/index.js#L19-L50) which tries to get/update an option using WooCommerce Admin's store. Apparently that's the only place we're doing that in the plugin, and it's for displaying a UPE notice introduced in #1794.

Turns out WC Admin has deprecated the update/get of options [that are not default from WC](https://github.com/woocommerce/woocommerce-admin/blob/78d0e10a99676c92650a5248917207e7304f5c1b/src/API/Options.php#L96-L102).

It doesn't seem right that we're setting a custom option using WC Admin's store (`wc/admin/options`).

I guess there are 2 ways to solve this:
- Create a selector on our own store (`wcstripe/data`) and an AJAX endpoint to dismiss the notice - Might be cumbersome to refactor it now - We probably should have used something from [this existing class](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/1cff7dd463f165354e7ef665a75b7eb9c72b853f/includes/admin/class-wc-stripe-admin-notices.php).
- Remove the notice entirely, which would be easier (WCPay doesn't have it).

**Comment by edoriv** [comment] 2023-02-23 23:06
Hate to reopen an old issue but I'm using WooCommerce Version 7.4.0  and WooCommerce Stripe Gateway Version 7.1.0 

Found this in my recent error logs several times

[23-Feb-2023 18:56:39 UTC] The Automattic\WooCommerce\Admin\API\Options::get_options function is deprecated since version 3.1.

**Comment by xue28** [comment] 2023-05-22 14:27
6315823-zen

**Comment by Babylon1999** [comment] 2023-06-25 16:53
zd-6421604

**Comment by Babylon1999** [comment] 2023-09-13 16:18
one more in zd-6800181

**Comment by shameemreza** [comment] 2023-10-23 03:06
Another report: zd-7145251

**Comment by WillBrubaker** [comment] 2023-12-29 03:06
7476262-zen

**Comment by thuautp** [comment] 2024-01-18 04:11
7602140-zen

**Comment by annemirasol** [comment] 2024-09-20 19:07
Closing, as I am no longer able to reproduce.

Stripe plugin 8.70
WooCommerce 9.3.1
WordPress 6.6.2

**Closed as completed by annemirasol** 2024-09-20 19:07 UTC
Labels: type: bug, priority: medium
