### ISSUE TITLE
Bug: SEPA Direct Debit / Javascipt swaps digits in wrong order (Mobile Firefox)

### ISSUE THREAD

**Issue by webaffin** [woocommerce/woocommerce-gateway-stripe#977] opened 2019-08-28 18:33 UTC
I found a nasty bug in your plugin. It only occurs on Firefox Mobile when typing the IBAN number for SEPA direct debit. Google Chrome Mobile, on the other hand, works.

Description:

When typing the IBAN number, e.g. de0443…, after typing the 6th character (here: “3”) the javascript tries to normalize the input (characters to uppercase, space between digits etc.). In Firefox Mobile this is done erroneously, because it swaps the last two digits and positions the cursor on the wrong position (not after the last digit, instead at the digit before the last one).

Result:

`DE04 34` and the cursor is positioned, where I place the underscore here: `DE04 3_4`

Expected Result:

`DE04 43` and the cursor is positioned, where I place the underscore here: `DE04 43_`

Browser: Firefox (for mobile) 68.0.2
OS: Android 8.0.0
AdBlocker: deactivated
Browser-Cache:  #emptied

**Comment by webaffin** [comment] 2019-10-09 10:05
Problem is still there and easy to reproduce. I've tested it again. Without any plugins activated except WooCommerce and Stripe: same behaviour!

In Germany Mobile Firefox is quite popular, about 15 % of the people use it (https://gs.statcounter.com/browser-market-share/all/germany).

**Comment by v18** [comment] 2021-03-04 02:50
I'm not able to reproduce this issue. When using Firefox for Android 86.1.1 on Pixel 2, Android version 11. I'm able to type this string: `DE0443` and it looks like this:

<img src="https://user-images.githubusercontent.com/11487924/109903839-b3bd2200-7cdf-11eb-80a4-d43cd017f9ea.png" width="200">

I'm going to close this issue for now, but if it's still happening please feel free to re-open.

**Closed by v18** 2021-03-04 02:50 UTC
Labels: component: LPMs/APMs, component: stripe checkout, priority: low
