### ISSUE TITLE
Express Checkout Buttons Missing on Pay for Order checkout

### ISSUE THREAD

**Issue by cmaskaler** [woocommerce/woocommerce-gateway-stripe#2582] opened 2023-03-23 04:28 UTC
Express Checkout Apple and Google Pay dont work on pay for order checkout (form-pay.php)
I have managed to put it by putting some code of form-pay.php but the correct order price numbers don't show. If I load the order to cart, it works correctly, but when completing the order, a new order is created so this is surely what we want. We need Stripe to make it work by default. Woocommerce Payments plugin also had this issue and fixed it last summer. Do the same:
[Express Checkout Buttons Missing on Pay for Order screen](https://github.com/Automattic/woocommerce-payments/pull/4264)

**Comment by dougaitken** [comment] 2023-04-03 16:56
Duplicate of #2345 and I see you've commented there so I'm closing this one @cmaskaler

**Closed as not planned by dougaitken** 2023-04-03 16:56 UTC
Labels: component: payment request buttons
