### ISSUE TITLE
Error SCA Rest

### ISSUE THREAD

**Issue by septk** [woocommerce/woocommerce-gateway-stripe#1162] opened 2020-04-04 15:30 UTC
I’m using a custom endpoint that call process_payment($order_id) in WC_Gateway_Stripe class. If I pay with a normal card (4242 4242 4242 4242) the response is success, but if I pay with a card with 3D (4000000000003220) the response is success too, but in my admin panel show that the order is outstanding.

How can I process a Woocommerce Stripe REST payment with 3D secure flow?

Thank you

**Comment by dwainm** [comment] 2020-05-15 14:54
Seems related to https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1201

**Comment by septk** [comment] 2020-05-19 08:31
Did you understand/read my issue? It is not related to #1201 . My problem is processing 3D/SCA Payments, not with CVC.

**Comment by dwainm** [comment] 2020-05-21 08:38
Yes I did, but If you read my reply again, I said that It "seems" related and not it "is" related.

In both instances the order is outstanding. The cause may differ but the underlying reasons may be the same. I'm highlighting the other issue so we can keep it in mind as we look into this.

**Comment by v18** [comment] 2021-05-07 04:18
Thanks for the report, @septk. I'm able to check out using the test card `4000000000003220`, and the order is marked as `Processing`. Here's what I see:

<img width="272" alt="processing-order-status" src="https://user-images.githubusercontent.com/11487924/117397239-a407c700-af36-11eb-900f-6b8bf5182134.png">

I'm going to close this issue for now. If there's still any issue with checking out with any 3DS card, feel free to re-open this issue or open a new issue. Please make sure to include the steps you take to see the problem.

**Closed by v18** 2021-05-07 04:18 UTC
Labels: component: SCA, priority: low, type: bug
