### ISSUE TITLE
Payment status isn't updated after stripe sends webhook

### ISSUE THREAD

**Issue by mowsen** [woocommerce/woocommerce-gateway-stripe#1119] opened 2020-01-17 14:53 UTC
**Describe the bug**
The plugin doesn't update the product status after stripe sends a "charge.succeeded". I have only had the chance to verify it for the payment method: SOFORT

In the logs I get: 

2020-01-17T14:46:48+00:00 DEBUG 
====Stripe Version: 4.3.1====
====Start Log====
Could not find order via charge ID: py_1G0vScAhVU2GDYkDAtV5lrYV
====End Log====

Even though an order with that charge ID exists:

![image](https://user-images.githubusercontent.com/45080170/72621162-05bab100-3941-11ea-88d6-61fad287fe49.png)

**Reproduce behavior:**
1. Checkout a product with SOFORT
2. Wait until stripe sends the "charge.succeeded" webhook
3. Product isn't updated

**Environment:**
 - WordPress Version 5.3.2
 - WooCommerce Version 3.8.1
 - Stripe Plugin Version 4.3.1

**Comment by septk** [comment] 2020-04-08 14:30
+1

**Comment by dougaitken** [comment] 2020-04-30 10:23
Looks like this is related to #951 - can you add some details to that Issue if possible please @mowsen @septk 

Thanks!

**Comment by v18** [comment] 2021-03-06 06:09
I'm not able to reproduce this. When I check out with SOFORT, I can see that the webhook of the type `charge.succeeded` is correctly handled and the order is marked as `processing`. Here are the order notes I see:

<img width="269" alt="Screen Shot 2021-03-06 at 3 08 40 PM" src="https://user-images.githubusercontent.com/11487924/110197282-de4cdd80-7e8d-11eb-9176-5f81f02bf66d.png">

I'm going to close this issue for now, but feel free to re-open if the issue is still happening. I would also contacting WooCommerce support about it so they can help you troubleshoot in case we can't reproduce the issue on our end.

**Closed by v18** 2021-03-06 06:09 UTC
Labels: component: webhooks, priority: low, type: bug
