### ISSUE TITLE
API is significantly out-dated

### ISSUE THREAD

**Issue by devdg** [woocommerce/woocommerce-gateway-stripe#2655] opened 2023-07-08 23:48 UTC
A number of features have been rolled out into the Stripe API since the 2019-09-09 version which this plugin uses. A number of changes around PaymentIntent which could (and do appear to) lead to double-charging have been implemented in the API version from last November.

Please update this plugin to support the latest API version which  has major improvements.

No other alternative exists but to use this plugin with woocommerce.

**Comment by adamj7** [comment] 2023-08-06 02:54
It's actually 8 upgrades to the Stripe API according to https://stripe.com/docs/upgrades#2019-09-09

Please update the plugin to the latest API version (currently sitting at 2022-11-15)

**Comment by M-Falken** [comment] 2023-09-12 14:52
Hi
this is now at
[2023-08-16](https://stripe.com/docs/upgrades#2023-08-16)
PaymentIntents and SetupIntents now have automatic_payment_methods enabled by default, which allows you to configure payment method settings from the Dashboard—no code required.

**Comment by lkraav** [comment] 2024-02-22 09:22
Duplicate of #1207

**Closed as completed** 2024-08-29 12:36 UTC
