### ISSUE TITLE
Order marked Failed after Completed due to error on updating PaymentIntent post-payment

### ISSUE THREAD

**Issue by ptrsmk** [woocommerce/woocommerce-gateway-stripe#2686] opened 2023-08-21 17:43 UTC
When a payment is made using an updated card after a failed payment, the order is marked completed and then marked Failed due to a 400 error response from the API.

**To Reproduce**
1. Go to a subscription with an invalid payment method.
2. Click on Subscription Actions and Process a Renewal
3. After the renewal fails, log in as the customer and pay for the order with a new, valid payment method.
4. The payment will go through, the order will be marked completed, but then a request to update the PaymentIntent's payment_method will be initiated and the site will receive a 400 error response like the following:
```
{
  "error": {
    "code": "payment_intent_unexpected_state",
    "doc_url": "https://stripe.com/docs/error-codes/payment-intent-unexpected-state",
    "message": "This PaymentIntent's payment_method could not be updated because it has a status of succeeded. You may only update the payment_method of a PaymentIntent with one of the following statuses: requires_payment_method, requires_confirmation, requires_action.",
    "param": "payment_method",
    "payment_intent": {...
```

**Expected behavior**
Either the plugin should not attempt to update the payment_method, or, at the least, a 400 error received due to failure to update the PaymentIntent shouldn't cause a successfully paid for order to be marked failed.

**Environment (please complete the following information):**
 - WordPress Version 6.2.2
 - WooCommerce Version 8.0.2
 - Stripe Plugin Version 7.5.0
 - Any other plugins installed

[SystemStatusReport_sophiainstitute.com_2023-08-21T17-42-05.txt](https://github.com/woocommerce/woocommerce-gateway-stripe/files/12399215/SystemStatusReport_sophiainstitute.com_2023-08-21T17-42-05.txt)

**Comment by gogasan24ru** [comment] 2024-06-11 10:20
We have encountered the same behavior recently as well. Is there any progress on that?

**Comment by ARAGRAGMED** [comment] 2024-06-24 13:04
Same issue any updates please ?

**Comment by wjrosa** [comment] 2024-12-05 14:02
Hi folks! Is this still happening to you? I did multiple tests here and could not reproduce the issue. Maybe this is related to the legacy checkout experience, which is deprecated. Let me know if not

**Comment by wjrosa** [comment] 2024-12-11 16:38
I will be closing this for now. Let us know if we should re-open it.

**Closed as completed by wjrosa** 2024-12-11 16:38 UTC
Labels: priority: high, type: bug
