### ISSUE TITLE
WP 6.4 update causing potential Stripe API, WP-Admin, and performance issues

### ISSUE THREAD

**Issue by wpniall** [woocommerce/woocommerce-gateway-stripe#2751] opened 2023-11-08 13:20 UTC
**Describe the bug**
After the WP 6.4 update, several people have reported issues with the Stripe plugin:

- [Plugin causing site performance issues after WordPress 6.4 Update](https://wordpress.org/support/topic/plugin-causing-site-performance-issues-after-wordpress-6-4-update/)
- [Not able to access admin with stripe plugin active](https://wordpress.org/support/topic/not-able-to-access-admin-with-stripe-plugin-active/)
- [Plugin causing error wp-admin](https://wordpress.org/support/topic/plugin-causing-error-wp-admin/)

Live mode:
```
Your customers cannot use Stripe on checkout, because we couldn’t connect to your account. Please go to your settings and, set your Stripe account keys.
```

Test mode:
```
There was a problem connecting to the Stripe API endpoint.
```

The backend also slows down and some merchants can't even access the WP-Admin. Downgrading WordPress solves the issue.

**To Reproduce**
1. Update WordPress to v6.4
2. Error appears either in live or test mode

**Note:** It's yet unclear what's causing the issue but several people have the same issue and a few said conflict testing didn't help. Myself and a few colleagues are unable to replicate the issue (all on different hosting platforms).

**Expected behavior**
Existing Stripe keys should work after updating to WP 6.4

**Screenshots**
N/A

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - Stripe Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**
N/A

**Comment by xue28** [comment] 2023-11-08 14:29
https://wordpress.org/support/topic/plugin-causing-site-performance-issues-after-wordpress-6-4-update/

**Comment by mustardBees** [comment] 2023-11-08 14:56
We're seeing this too on a client site. A quick look with Query Monitor, there is a ~70s HTTP call which appears to be related.

**Comment by shameemreza** [comment] 2023-11-08 15:12
Another report here: https://wordpress.org/support/topic/customers-are-not-able-to-pay-via-stripe-due-to-the-6-4-update/

7278508-zen

**Comment by shameemreza** [comment] 2023-11-08 15:38
Another report here: https://wordpress.org/support/topic/plugin-causing-error-wp-admin

7278707-zen

**Side note:** A user claimed that after manually disabling the Stripe plugin, they were able to access the dashboard.

**Comment by rob-vandenberg** [comment] 2023-11-08 16:07
Same problem here. Site became extremely slow after upgrade to 6.4.
Disabling the Stripe Gateway plugin makes the site fast again.
Enabling it and it is slow again.

Not saying it’s a bug in the plugin, after all it was working fine before the upgrade to 6.4, but there is definately a compatibility issue between the plugin and WP 6.4.

**Comment by faroutride** [comment] 2023-11-08 16:08
I'm having the same issues after upgrade to WP 6.4.

1. "Your customers cannot use Stripe on checkout, because we couldn’t connect to your account. Please go to your settings and, set your Stripe account keys".
2. Backend extremely slow.

Deactivating the plugin solves the issue.

**Comment by shameemreza** [comment] 2023-11-08 16:27
Another report here: https://wordpress.org/support/topic/this-plugin-is-incompatible-with-wordpress-6-4

7279053-zen

**Comment by 74MR47** [comment] 2023-11-08 17:25
Another report:

ZD: 7279156

Forum Thread: 👉 [Activating Apple pay crashes last WP](https://wordpress.org/support/topic/activating-apple-pay-crashes-last-wp/)

**Comment by survivalrealty** [comment] 2023-11-08 18:13
<img width="1185" alt="Screen Shot 2023-11-08 at 10 13 23 AM" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/37254077/36bc7aa4-6628-4c35-a0c0-a8705fc979f9">
Experiencing similar issue. WP backend has been extremely laggy, occasional server errors, and getting:

> Your customers cannot use Stripe on checkout, because we couldn't connect to your account. Please go to your settings and, set your Stripe account keys.

Going to `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings`, I only see blank boxes where the Stripe credentials and other fields should be.

This fix needs to be *high* priority, I'm sure I'm not the only person losing revenue right now.

**Comment by faroutride** [comment] 2023-11-08 18:21
> This fix needs to be _high_ priority, I'm sure I'm not the only person losing revenue right now.

This. I enabled PayPal now, as I don't want to revert back to WP6.3 to make Stripe work again.

**Comment by dingod** [comment] 2023-11-08 18:40
I am also having this bug. Losing mad sales. Ultra-high priority please! I am reverting to 6.3.2.

**Comment by 74MR47** [comment] 2023-11-08 18:41
Another report:

ZD: 7279724

Forum Thread: 👉 [WordPress 6.4 version and issues with this plugin](https://wordpress.org/support/topic/wordpress-6-4-version-and-issues-with-this-plugin/)

**Comment by beaulebens** [comment] 2023-11-08 20:00
This is likely being caused by a change in WordPress, which is being reverted/hotfixed [here](https://github.com/WordPress/Requests/issues/838). As soon as that is available (or if someone wants to apply the PR directly), please confirm if you're still seeing this issue on impacted sites.

**Comment by beaulebens** [comment] 2023-11-08 21:43
WordPress has a release candidate available in case anyone is in a position to test/confirm: https://make.wordpress.org/core/2023/11/08/wordpress-6-4-1-rc1-is-now-available/

**Comment by mostafasoufi** [comment] 2023-11-08 23:23
I even tried to set a proxy `WP_PROXY_HOST` but didn't work, just fixed by rolling back to the previous version by:

```
wp core update --version=6.3.2 --force
```

**Comment by Obesepete** [comment] 2023-11-09 00:21
Had the same issue, rolled back to 6.3.1, immediately everything worked again. Updated all API keys also.

**Comment by rob-vandenberg** [comment] 2023-11-09 01:39
I tried the new version 6.4.1 and it solved the problem for me. 
The site is fast again and the Stripe Gateway is working normally.

**Comment by faroutride** [comment] 2023-11-09 01:43
Same here, issue solved with WP 6.4.1.

**Comment by shameemreza** [comment] 2023-11-09 03:06
Another report here: 7280641-zen.

Suggested to upgrade WordPress to 6.4.1.

**Comment by shameemreza** [comment] 2023-11-09 03:16
Perhaps Another report here: https://wordpress.org/support/topic/major-issue-with-curl-28-timeouts/

7281239-zen

**Comment by shameemreza** [comment] 2023-11-09 03:24
Another report: 7281493-zen

**Comment by james-allan** [comment] 2023-11-09 07:00
Thanks everyone for the reports and your work to test can confirm the issue and fix.

WordPress 6.4.1 has now been officially released and by all accounts that has resolved the performance issues. **Please update to WordPress 6.4.1 as soon as possible.**

If you continue to experience problems, slowdowns or connectivity issues, please get in contact.

**Closed as completed** 2023-11-09 07:01 UTC
