### ISSUE TITLE
Bump tested up to 3.7.0

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-stripe#984] opened 2019-09-07 09:43 UTC
#### Affected ticket(s)
2327651-zen

#### What I expected
For WooCommerce Stripe to officially support WooCommerce 3.7.0

#### What happened instead

The tested up to header is still on 3.6.4: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/woocommerce-gateway-stripe.php#L12

**Comment by allendav** [comment] 2019-09-17 19:12
Yeah :) This one has taken longer. Duplicate of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/922 which should release this week

**Closed** 2019-09-17 19:13 UTC
Labels: Priority: Low, [Type] Bug
