### ISSUE TITLE
Refund doesn't take care of API errors as native WC refund way

### ISSUE THREAD

**Issue by amritansh24** [woocommerce/woocommerce-gateway-stripe#898] opened 2019-06-20 07:12 UTC
#### Affected ticket(s)
N/A

#### What I expected
Whenever any kind of API error comes up during the refund call, it should alert the user about the failure and discard the refund. 

#### What happened instead
Even process_refund() returned an API error, there was not an alert about the failure of refund & the refund order in WooCommerce made successfully. 

#### Steps to reproduce the issue

Here is my video explaining the issue by switching to live mode just after the purchase before performing the refund. So that there was surely an API error during refund. 
https://www.dropbox.com/s/nfad53slh615aua/stripe_refund.mp4?dl=0

Additional note: Gateways like PayPal standard returns an object of WP_Error class from process_refund() whenever error returned from the API and then WooCommerce checks for WP_Error and delete the refund order created in WooCommerce. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by wjrosa** [comment] 2024-12-13 20:17
Hi @amritansh24 ! Your reported method (`process_refund `) has been updated multiple times since your issue was created. We have a [try...catch block](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L1123) for a while now, which returns the expected `WP_Error` class.

I tried to reproduce a bug similar to what you reported, but I couldn't. Here's what happened to me:
![Image](https://github.com/user-attachments/assets/fd92550c-12ed-4992-8ee1-09e91c2d9425)

(working as expected)

Closing this for now. Let us know if you still have issues.

**Closed by wjrosa** 2024-12-13 20:17 UTC
Labels: priority: high, type: bug
