### ISSUE TITLE
Custom name is not working after upgrade to 5.8 

### ISSUE THREAD

**Issue by FunkyCss** [woocommerce/woocommerce-gateway-stripe#2183] opened 2021-11-24 14:59 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'Payments - Settings '
2. Click on 'Click on new checkout experience and after you enabled it and saved , unckeck it and save again'
3. Go to settings and try to change the name ( one field is missing ) 
4. Go to checkout page and you will see that your new custom name is not working.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version 5. 8
 - WooCommerce Version 5.9 
 - Stripe Plugin Version 5.8.1
 - Browser - Chrome 
 - Any other plugins installed

**Additional context**

**Comment by FunkyCss** [comment] 2021-11-24 15:02
After the upgrade for 5.8 my custom text on the checkout page is not working anymore.

There is a default ( not translated  ) -  " Pay with credit card / debit card "

Also the field input seems to have disapeard. inside the dashboard.


To replicate that issue please upgrade to 5.8 or 5.8.1 , 

Pick the Use the new checkout experience - after disable it again.

Try to change the custom name for the checkout page, go to checkout page , there is the default.

**Comment by FunkyCss** [comment] 2021-11-24 15:11
In the first visit seems that they work OK , but my guess is that the new checkout experience brakes things up when first has been selected. So keep this on mind that in the first sight you will see everything fine , but it is not.

**Comment by dougaitken** [comment] 2022-07-29 20:10
I appreciate some time has passed since the original comment, thanks for your patience. 

It is possible that this issue has been fixed by a more recent release as I’ve been unable to replicate the issue you described using the latest release of the core WooCommerce plugin and the [WooCommerce Stripe Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/). 

As I’m unable to reproduce this, I’m marking this Issue as Closed. Please do open a new one if you are able to reproduce this again.

**Closed as completed by dougaitken** 2022-07-29 20:10 UTC
