### ISSUE TITLE
Inline messages are hidden when adding keys

### ISSUE THREAD

**Issue by PanosSynetos** [woocommerce/woocommerce-gateway-stripe#2544] opened 2023-02-03 11:16 UTC
**Describe the bug**
There is a negative margin on `.wcstripe-inline-notice`, making the notice to be somewhat hidden.

Happens on both self-hosted and atomic sites.
See screenshot

![image](https://user-images.githubusercontent.com/2484390/216590136-a2798b4c-564c-4d2d-8227-3956c236bf00.png)

**Comment by reykjalin** [comment] 2023-02-17 05:04
Closing as a duplicate of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2470

**Closed as completed by reykjalin** 2023-02-17 05:04 UTC
