### ISSUE TITLE
Gateway not updating billing address for a saved card when placed an order

### ISSUE THREAD

**Issue by kuldeep3** [woocommerce/woocommerce-gateway-stripe#1682] opened 2021-08-13 19:56 UTC
**Describe the bug**
When a user places an order and adds a card as a payment method and saves that card for a future transaction, stripe uses the billing address added by the user while checking out. If the user again places another order using the same card but with a different billing address, then the stripe doesn't update the user billing address from the checkout fields. Instead, it fetches the billing address that is attached to the saved card on stripe's servers which results in a zip code validation error for users.

**To Reproduce**
1. Place an order and proceed to checkout.
2. On the checkout page, fill in the billing address and add a new payment method and then click on save this payment method for the future.
3. After successfully placing an order, create another order with a different billing address and choosing the same card that was used in the previous order.
4. Check stripe logs, there you will find that the billing address on the latest order is not reflected correctly, it shows the billing address that has been already attached to the saved card on stripe's server.

**Expected behavior**
Whenever the customer creates an order and uses a previously saved card on the order, then the billing address should be updated as per the address added by the customer while checking out or that is stored in the customer profile.

**Screenshots**

https://user-images.githubusercontent.com/37093310/129411904-4e655547-bb36-4d37-8fa5-47934f4728db.mp4

**Environment (please complete the following information):**
 - WordPress Version - 5.7.2
 - WooCommerce Version - 5.3.1
 - Stripe Plugin Version - 5.2.0
 - Browser [e.g. chrome, safari] and Version - Chrome 92.0.4515.131

**Additional context**
--NA--

**Comment by nagpai** [comment] 2021-08-14 09:37
Can you confirm if you did these tests with only WooCommerce core plugin and WooCommerce Stripe Payment Gateway plugin active on either StoreFront or TwentyTwenty one theme?

A bug should be logged here in GH only if you are able to reproduce this under the test conditions mentioned above.  If you are unable to replicate it in the test set-up. It would point to a conflict caused by a third party theme or a plugin.

**Comment by nagpai** [comment] 2021-08-14 09:53
I am unable to replicate the error on a test site with Storefront theme, WooCommerce 5.5.2 and Stripe 5.3.0.

**Comment by kuldeep3** [comment] 2021-08-14 11:58
@nagpai I am able to reproduce this with only the WooCommerce core plugin and WooCommerce Stripe Payment Gateway plugin active on the Twenty Twenty-One v1.2 theme.

https://user-images.githubusercontent.com/37093310/129445589-218887a1-f6fa-42fa-aa58-e20d955510f4.mp4

**Comment by kuldeep3** [comment] 2021-08-14 13:17
@nagpai 

For order **142**, the billing address is:
Cleever Street 213
98D
Alaska, AK 95001

For order **143**, the billing address is:
Cleever Street 555
98C
Benton, KY 42025

But you can see in the Stripe logs that the address is the same in both cases (the first order's address)

**Comment by WillBrubaker** [comment] 2021-08-14 23:59
I'm able to reproduce it.

**Comment by kuldeep3** [comment] 2021-08-17 06:20
@WillBrubaker Thanks. 

Do you think if there is a workaround regarding this issue as customers are facing problems because they can't place an order with the updated address?

Maybe if we could add more labels like priority high/critical for this issue, it will get some more attention, and it can be fixed soon.

**Comment by joashrajin** [comment] 2021-11-17 09:41
+1 4218298-zd-woothemes

**Comment by melek** [comment] 2021-12-31 20:16
I've added a 'High' priority tag, as the card management functions should really behave for customers as expected. 4218298-zen still looking for a response.

**Comment by pauljacobson** [comment] 2022-03-02 07:38
Given that we don't have a time estimate for when this issue will be addressed, just adding a request to update us when this is addressed so we can create a follow-up ticket to 4218298-zen

**Comment by wyter** [comment] 2023-04-17 11:41
6193126-zen

The merchant has a workaround currently - they've disabled Zip validation in Stripe and the affected customer is able to pay.

**Comment by mattallan** [comment] 2024-05-22 08:20
I can reproduce this issue on the latest version with both UPE enabled and disabled (using the same test data as above in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1682#issuecomment-898893602)

Assigning this to myself.

**Closed as completed** 2024-06-14 01:38 UTC
Labels: priority: high, type: bug
