### ISSUE TITLE
Apple Pay Express Checkout fails for countries which do not have a billing state. 

### ISSUE THREAD

**Issue by julianengel** [woocommerce/woocommerce-gateway-stripe#2618] opened 2023-05-14 17:07 UTC
**Describe the bug**
When using the Express Checkout option with Apple Pay, the payment fails and throws the following error: 

`Cannot checkout: "Billing country is a required field`

**To Reproduce**
1. Go to 'Cart'
2. Click on 'Apple Pay'
3. Enter your shipping address, (in our case Cyprus or Poland)
4. Complete the payment 
5. Error appears in the Woo Notice section.

**Expected behavior**
Payment should go through without issue, as Billing State is not an option in those countries. 

**Environment (please complete the following information):**
 - WordPress Version: 6.2
 - WooCommerce Version: 7.7.0
 - Stripe Plugin Version: by WooCommerce – 7.4.0 
 - Browser [e.g. chrome, safari] and Version: Safari

**Additional context**
This is the same issue which used to happen with [https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/724](Issue 724 for Paypal). This was resolved and merged in with [https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/725](Merge 725.)

**Current Workaround**

The current workaround is lifted from the documentation and was linked to in one of the other issues, for anyone stuck with the same issue as we were. 

https://woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/

and in practice, we use the following code:
```

// Hook in to resolve stripe issue with billing state not existing
add_filter( 'woocommerce_default_address_fields' , 'custom_override_default_address_fields' );

// Our hooked in function - $address_fields is passed via the filter!
function custom_override_default_address_fields( $address_fields ) {
     $address_fields['state']['required'] = false;

     return $address_fields;
}
```

**Comment by wjrosa** [comment] 2024-12-04 19:05
As a collateral fix, I created https://github.com/woocommerce/woocommerce/pull/53459. When using an address from Poland, the state field is already optional in WC.

As for the main issue, I cannot reproduce the original error message. So, it was probably fixed on later versions. I will follow up with the PR above.

**Closed as completed** 2024-12-05 13:19 UTC
Labels: priority: high, type: bug, component: payment request buttons
