### ISSUE TITLE
Prevent line item change for authorized payment

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce-gateway-stripe#1231] opened 2020-06-09 16:50 UTC
With Authorized payments, not set to capture immediately, customers can edit the price of line items for the On-Hold order, but this does not change the authorized amount in Stripe. 

Upon changing the order status to Processing, the original authorized amount is processed. 

The expectation would be for a way to inform the customer that changes to a pending payment or on-hold order will not change the authorized amount.

**Comment by v18** [comment] 2021-05-08 07:45
Part of the issue here is that the order status is changed to `on-hold` when the charge is authorized but not captured. [WooCommerce Core allows editing](https://docs.woocommerce.com/document/managing-orders/#editing-or-adding-order-items) an order only when the status is `on hold` or `pending`:

> Apart from refunding, order items can not be edited, unless the order status is “Pending payment”, or “On hold.”

However, the `on hold` order status in general makes sense for the payment status ([doc](https://docs.woocommerce.com/document/managing-orders/#order-statuses)):

> On hold — Awaiting payment – stock is reduced, but you need to confirm payment.

**Comment by wjrosa** [comment] 2024-12-30 18:35
Closing as duplicate of https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3646

**Closed by wjrosa** 2024-12-30 18:35 UTC
Labels: priority: high, type: enhancement, needs design
