### ISSUE TITLE
No error shown in woocommerce for refunding a higher amount than available. 

### ISSUE THREAD

**Issue by MarkHaynes** [woocommerce/woocommerce-gateway-stripe#1315] opened 2020-10-01 14:14 UTC
**Describe the bug**
If the user attempts to refund items that are equal to more than the amount available this errors inside of stripe. However in woocommerce no error is shown and it appears as though the refund went through successfully. There is no error shown in the notes either.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create and pay for order.
2. Add more items to order after it has been created.
3. Attempt to refund all items. 

**Expected behaviour**
A message should appear saying refund failed etc. 

**Environment (please complete the following information):**
 - Latest Wordpress
 - Latest Woocommerce
 - Latest Stripe
 - Chrome

**Additional context**
Example of the error in stripe:

Error message
"message": "Refund amount (£93.90) is greater than charge amount (£54.45)"
"type": "invalid_request_error"

**Comment by vbelolapotkov** [comment] 2020-10-06 10:21
Hey @MarkHaynes, thanks for reporting this! I've tried to reproduce it and the only way I was able to is by doing the following:

1. Create and pay for order (order is in `Processing` state).
2. Manually change order state to `Pending payment` because the order in `Processing` state is not editable.
3. Increase items quantity, save the order and change order status to `Processing`.
4. Make a refund for more items than there were purchased.

Is that similar to what you're doing?

Anyway, I confirm that this is a bug and there is a corresponding message in the logs.

**Comment by MarkHaynes** [comment] 2020-10-06 12:05
Hey @vbelolapotkov 

That sounds spot on to me!

Heres our Stripe log through woo if it helps:

`
2020-09-16T15:46:05+00:00 DEBUG 
====Stripe Version: 4.5.2====
====Start Log====
Info: Beginning refund for order ch_1GfUIuLD9U4dPy2iK6U3EeSf for the amount of 93.90
====End Log====


2020-09-16T15:46:05+00:00 DEBUG 
====Stripe Version: 4.5.2====
====Start Log====
payment_intents/pi_1GfUIuLD9U4dPy2iw8Cf1QD9 request: Array
(
)

====End Log====


2020-09-16T15:46:05+00:00 DEBUG 
====Stripe Version: 4.5.2====
====Start Log====
refunds request: Array
(
    [amount] => 9390
    [metadata] => Array
        (
            [reason] => RULE OF 6
        )

    [charge] => ch_1GfUIuLD9U4dPy2iK6U3EeSf
)

====End Log====


2020-09-16T15:46:06+00:00 DEBUG 
====Stripe Version: 4.5.2====
====Start Log====
Error: Refund amount (£93.90) is greater than charge amount (£54.45)
====End Log====
`

**Comment by v18** [comment] 2021-05-08 09:55
We now show an error when the refund amount is greater than the amount charged, as a modal in the browser:

<img width="433" alt="error_refunding" src="https://user-images.githubusercontent.com/11487924/117535062-ff1ce500-b02e-11eb-968d-3a0a0b252fcb.png">

Closing as fixed.

**Closed by v18** 2021-05-08 09:55 UTC
Labels: priority: low, type: bug
