### ISSUE TITLE
stripe_customer_id is missing from subscriptions after WC 3.0 update

### ISSUE THREAD

**Issue by kristinaplauche** [woocommerce/woocommerce-gateway-stripe#267] opened 2017-05-23 20:45 UTC
#### Affected ticket(s)

577912-zd-woothemes

#### What I expected

This isn't so much of a bug report as a question. Prospress asked us to ask if you have seen this. I cannot replicate.

We expect for the Stripe Customer ID to be saved on the subscription after the update to WooCommerce 3.0. 

#### What happened instead
Customer ID is missing. 
![screenshot](http://cld.wthms.co/dO9Is2+)
Image link: http://cld.wthms.co/dO9Is2

When customer tries to update the Next Payment date, they get an error that says the customer ID is missing. 

#### Steps to reproduce the issue

I can't. Sorry.  This is really more of a question. @mattyza Thank you!

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by mattyza** [comment] 2017-05-24 07:27
Thanks @kristinaplauche. Labelling as a high priority bug for now, so we can ensure we're not missing out on a possible bug.

@roykho - could I ask you to please test and see if you can reproduce this, as your first priority?

**Comment by roykho** [comment] 2017-05-24 17:12
During a normal subscriptions order, both those information are saved within the subscriptions meta. However there indeed is an issue only when/if a payment failed and customer goes to make a payment again with valid payment method, it does not update the order with the new payment information. Working to get this fixed now.

**Comment by james-allan** [comment] 2017-05-25 07:59
> However there indeed is an issue only when/if a payment failed and customer goes to make a payment again with valid payment method, it does not update the order with the new payment information. Working to get this fixed now.

@roykho are you referring to paying for a failed renewal or parent/initial order? We have an open issue on Subscriptions related to not updating payment meta after paying for a failed renewal payment. It's related to having the retry system enabled. PR: https://github.com/Prospress/woocommerce-subscriptions/pull/2141

If it is the same issue you should be able to close this one.

Regarding the initial report from @kristinaplauche, I've added a note to the ticket. The tldr version is that it looks like this was caused by a very, very late upgrade from Subscriptions 1.5.x which is about 2 years old. 

The Stripe Card ID which has been blurred out in Kristina's screenshot also has a `tok_` prefix rather than `card_`. Is that an old format?

**Comment by roykho** [comment] 2017-05-25 13:39
@james-allan - so the issue I am seeing here is when you manually go to an active subscription with  wrong/invalid Stripe customer id/card id and you use the action "Process renewal". This creates a new order along with the same wrong/invalid Stripe customer id/card id. So far so good as that is the expected behavior. Now if I go to pay for the order, I expect the order to have an updated Stripe customer id/card id and also triggers the "update failed payments" hook for subs to also have updated Stripe customer id/card id for future recurring charges. But for some reason, that is not happening. Even though the order does receive the correct information, something after the fact updates over it again with the old information.

**Comment by james-allan** [comment] 2017-05-25 13:50
@roykho Right. Before paying for the order is its status failed? The "update failed payments" hook only triggers for orders which had a failed status before they were paid for. 

The issue we're currently fixing is caused by our retry system because it sets the status to pending-payment which means paying for the order while there is a retry scheduled, doesn't trigger that hook.

**Comment by roykho** [comment] 2017-05-25 14:17
@james-allan - yes the order status is "failed". From tracing the process, right up to before `$order->payment_complete()` is fired, both the subscription and order has the updated valid Stripe customer ID/card ID. So that tells me it is indeed updated correctly. But right after `$order->payment_complete()`, they both gets reverted back to the old invalid Stripe customer id/card id.

**Comment by roykho** [comment] 2017-05-25 14:41
My hunch is how we're saving the meta. Instead of using update_post_meta, perhaps we need to set via the wrapper and call `$order->save()`...Testing this.

**Comment by roykho** [comment] 2017-05-25 15:02
@james-allan - ok this is solved. update_post_meta does not work here as when the payment is completed, the order only updates whats in the "changes" internal variable. And it will update the order post metas again with what it has internally thus it overrode the "update_post_meta" calls from before.

**Closed** 2017-05-25 15:03 UTC
Labels: [Pri] High, [Type] Bug
