### ISSUE TITLE
[Deferred intent] Card - Ensure refunds work as expected

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2765] opened 2023-11-17 21:31 UTC
Not sure if this flow would need any tweaks, but adding it anyway to confirm.

### Acceptance criteria
- The following flows must work as described:
  - [Merchant > Full refund](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#full-refund)
  - [Merchant > Partial refund](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#partial-refund)
  - [Merchant > Refund failure](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#refund-failure)
- The e2e test for Full refund must continue to work
- Test both regular and 3DS cards

**Comment by james-allan** [comment] 2023-12-08 06:04
I've tested the following flows on the latest `add/deferred-intent` branch. 

 - [x] [Merchant > Full refund](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#full-refund)
 - [x] [Merchant > Partial refund](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#partial-refund)
 - [x]  [Merchant > Refund failure](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#refund-failure)
 - [x] 3DS/SCA payment fully refunded.

I've ran e2e tests, however they have all failed. I'll have to look into it further, however I suspect they are failing for other reasons. eg cannot complete a purchase in order to refund it.

**Comment by james-allan** [comment] 2023-12-08 06:08
> I'll have to look into it further, however I suspect they are failing for other reasons.

Just to attach some additional details about that theory. The are failing because of these errors: 

<img width="500" alt="Screenshot 2023-12-08 at 4 05 38 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/b90df7dc-a4fa-4308-8bcb-4a5a3d60c166">

with screenshots like this one: 
<img width="500" alt="Screenshot 2023-12-08 at 4 06 49 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/dcc48f93-243c-4996-a51b-b46d49b9c304">

At first glance this looks like it's unable to recognise the cart is empty - perhaps related to the block cart page, rather than the classic cart page.

**Comment by james-allan** [comment] 2023-12-11 02:03
> At first glance this looks like it's unable to recognise the cart is empty - perhaps related to the block cart page, rather than the classic cart page.

So I've confirmed that. The e2e test is looking for the old style WooCommerce notice with the `.cart-empty .woocommerce-info` class. 

eg: 

<img width="838" alt="Screenshot 2023-12-11 at 12 02 25 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/02af3585-1424-4eef-9fdc-38454a4b26c5">

That element doesn't exist on the block enabled sites.

**Comment by james-allan** [comment] 2023-12-12 03:07
I updated my jurassic ninja site to make the default cart and checkout page classic shortcode and that fixed the issues there. I'm still unable to confirm if e2e tests are working. I get the following error:


```
TypeError: Cannot read properties of undefined (reading 'data')

  105 |
  106 | 		expect( charge.refunded ).toBeTruthy();
> 107 | 		expect( charge.refunds.data[ 0 ].id ).toBe( stripeRefundId );
      | 		                       ^
  108 | 	} );
  109 | } );
  110 |

    at /public/wp-content/plugins/woocommerce-gateway-stripe/tests/e2e/tests/order/full-refund.spec.js:107:26
    at runMicrotasks (<anonymous>)
    at /public/wp-content/plugins/woocommerce-gateway-stripe/tests/e2e/tests/order/full-refund.spec.js:101:2
```

For some reason, after processing a refund, the charge response from Stripe indicates that the charge has been refunded (`refunded => true`), however it doesn't respond with any refund data. However when I fetch the charge directly on the JN site is does respond with refund data so 🤷‍♂️ 

The same error occurs on `develop` so I don't think this is particularly related deferred intents or split upe.

**Comment by a-danae** [comment] 2023-12-17 19:59
Thanks for the thorough investigation and for diving into the failing e2e tests, @james-allan! 🙂 

Given that manually testing the flows went as expected and that the e2e tests fail in `develop` as well, we could mark refunds as "working" for cards and create a separate issue for adjusting the failing e2e tests in the branch for the project. Does that sound good to you? Glad to handle it differently.

**Comment by james-allan** [comment] 2023-12-18 00:15
Yeah I think that's a good idea. Refunds do work via the UIs so it's a e2e bug. Given that, it's a good idea to close this general refunds issue for a more specific e2e one.  

- New issue: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2802

**Closed as completed** 2023-12-18 00:54 UTC
