### ISSUE TITLE
Stripe module loads methods at start of app bootstrap causing `is_checkout()` to return wrong values

### ISSUE THREAD

**Issue by cjnewbs** [woocommerce/woocommerce-gateway-stripe#2254] opened 2021-12-24 16:17 UTC
**Describe the bug**
When the `woocommerce-stripe-gateway` plugin is enabled calls to the `wc-ajax=checkout` and `wc-ajax=update_order_review`. endpoints, payment methods loaded via the `woocommerce_payment_gateways` filter the `is_checkout()` function returns `false`
This is because `add_action( 'wp', [ $this, 'maybe_process_upe_redirect' ] );` is run from `\WC_Stripe_Intent_Controller::__construct` causing payment methods to be loaded right at the beginning of the application bootstrap process.

**To Reproduce**
1. Enable `woocommerce-stripe-gateway`
2. Add items to cart and head to the checkout.
3. When the `update_order_review` AJAX call is run any payment gateway calling `is_checkout()` gets `false` returned.
4. Additionally attempting to place the order when any payment method calls to `is_checkout()` also returns `false`,
5. If logic is dependant on `is_checkout()` then the method will break.

**Expected behavior**
Calls to `is_checkout()` should return `true`

**Environment (please complete the following information):**
 - WordPress Version: 5.8.2
 - WooCommerce Version: 5.8.0
 - Stripe Plugin Version: 5.8.1
 - Google Chrome Version 96.0.4664.110 (Official Build) (x86_64) (However this happens on all browsers)

**Comment by asumaran** [comment] 2022-01-19 00:52
@cjnewbs this is the expected behavior. `is_checkout()` doesn't work for AJAX requests. You should be using `wp_doing_ajax()` instead.

**Comment by asumaran** [comment] 2022-06-20 22:16
Closing this since this is a not a bug and there's no new reports of this being a problem.

**Closed as completed by asumaran** 2022-06-20 22:16 UTC
