### ISSUE TITLE
Duplicate charges with Woo subs with Stripe Gateway 7.0

### ISSUE THREAD

**Issue by marlonsabala** [woocommerce/woocommerce-gateway-stripe#2474] opened 2022-11-10 19:37 UTC
Hey guys, I'm no developer, but this seemed the right place to post this.

I noticed that right after the auto update of Stripe Gateway to version 7.0.0 all Woo Subscription renewals got charged twice.

This resulted on some banks blocking the card (understandably as they see two identical charged coming through). It also caused all sorts of other issues with customers and of course, we lost some money with refund fees.

I have reverted to 6.9.0

**Comment by josephsellers** [comment] 2022-11-10 22:04
Hi @marlonsabala, thanks for posting this issue. 

I have had the same issue today (also with Stripe Gateway 7.0, also with subscription renewals). I was lucky and was working on stuff so noticed it pretty much straight away but still had some payments go through twice. 

I have also reverted to 6.9.0 which appears to have solved the issue. 

I can add a few small details which may help:

1. This is an issue of duplicate payments, not duplicate orders. 
2. The payments are being sent twice by the Scheduled Actions and appear twice in the WooCommerce Logs. 
3. The successful payment notes are being added in Order Notes for both payments.
4. There doesn't appear to be any error in any logs related to this.

**Comment by reykjalin** [comment] 2022-11-11 03:11
Thanks for reporting this! We've received other reports but we're struggling to reproduce the issue so we're not sure what exactly is happening.

In the meantime the recommendation would be to revert to 6.9.0. @marlonsabala @josephsellers can you confirm that reverting to version 6.9.0 fixes the issue?

**Comment by reykjalin** [comment] 2022-11-11 03:30
Quick update: I was finally able to reproduce the issue. We'll start working on a fix and get a patch release out ASAP.

**Comment by reykjalin** [comment] 2022-11-11 06:05
We've just released v7.0.1 with a fix for the duplicate charges. You may see duplicate order notes in some cases (something we'll look into as part of a separate issue) but there should be no duplicate charges anymore.

We sincerely apologize for the inconvenience this must have caused!

**Comment by josephsellers** [comment] 2022-11-11 09:32
Hi @reykjalin, yeah this disappeared on downgrading to 6.9.0. 

Thank you so much for a quick fix!!

I have upgraded to 7.0.1 and will keep an eye on it.

**Comment by lkraav** [comment] 2022-11-11 09:36
I was running 7.0.0 for 1-2 days, and do not seem to have any duplicate payments. I don't have UPE (updated checkout experience?) enabled. Does it confirm this problem hit UPE only?

**Comment by josephsellers** [comment] 2022-11-11 09:37
Hi @lkraav, nope I wasn't using UPE. 

Are you using subscriptions? It appears it only affects subscription renewals.

**Comment by thisissandip** [comment] 2022-11-11 10:43
Hi everyone, 

A new version of Stripe - 7.0.1 has been released just now that [fixes this issue](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2475).

Can you please update the Stripe plugin to 7.0.1 version and check the same?

**Comment by thisissandip** [comment] 2022-11-11 10:44
5702216-zen

**Comment by josephsellers** [comment] 2022-11-11 11:18
Hello!

Just a quick update. I upgraded to 7.0.1 a couple of hours ago and since then 6 renewal payments have gone through without any issue and without duplication. It appears (at least on my setup) that this is fixed now. 

Thanks again!!

**Comment by marlonsabala** [comment] 2022-11-11 15:49
Same here. 7.0.1 seems to fix things. And I don't have UPE on either.

**Comment by orhanfernandes** [comment] 2022-11-14 00:33
5705354-zen

**Comment by aaryandeveloper** [comment] 2022-11-14 11:37
I have 7.0.1 version, still have same issue 
I am using latest version of WooCommerce and WordPress.
Can you please tell me how to fix ?

**Comment by josephsellers** [comment] 2022-11-14 12:12
Hi @aaryandeveloper,

Hmm, 7.0.1 fixed it for me straight away. It appears [from this](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2475) that the issue was that the Stripe gateway was registered twice in readiness for some other Stripe feature which resulted in the charge being sent to Stripe twice. That has been reverted now which fixed the issue for my site straight away. 

If you are still having duplicate payments going through I would check if you have any other instance of your site somewhere (a backup, a staging site, etc). This has happened to me several times before and is super frustrating. I guess I am saying I doubt it is exactly the same issue because this precise issue is fixed for me and others on 7.0.1, but there are several other reasons why duplicate payments can be sent.

**Closed as completed** 2022-11-15 04:49 UTC
Labels: priority: critical, type: bug
