### ISSUE TITLE
Live Stripe Credit Card Fields Not Displaying With Test Card Saved To Account

### ISSUE THREAD

**Issue by billrobbins** [woocommerce/woocommerce-gateway-stripe#910] opened 2019-07-03 17:51 UTC
#### Affected ticket(s)

zen-2141241

#### What I expected

When going to check out as a logged in user with the test credit card number saved to my account, I expect to see the credit card fields.  This is when the site has _live_ checkout.   

#### What happened instead

The credit card fields are not displayed, nor is a message given explaining why they are missing.

#### Steps to reproduce the issue

* Enable test mode on the store.
* Save the test credit card number to the user account.
* Change the store to live mode.
* Attempt to check out while logged in as that user.

Not allowing checkout with a saved test card under live conditions is good.  What's happening could be better communicated to the user though.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by tommyshellberg** [comment] 2019-07-10 13:17
@billrobbins are you able to reproduce this on your own site? I'm not able to. If I add a saved card while in TEST mode and then switch to LIVE, the credit card form shows but it will have the test card still saved:

![](https://cld.wthms.co/UPGh4u)

If you try to check out you'll get this warning:

>No such source: src_1EufbqFCbUgeVdGxmoEI9CQY; a similar object exists in test mode, but a live mode key was used to make this request.

**Comment by v18** [comment] 2021-03-04 02:33
I'm going to close this issue since I can't repro. Here are the steps I tried:


1. Use test mode
2. Log in as a customer
3. Ensure that there's a test credit card saved for the account
4. Switch to live mode
5. Add product and go to check out
6. I am able to see the credit card fields

**Closed by v18** 2021-03-04 02:33 UTC
Labels: priority: low, type: bug
