### ISSUE TITLE
`Invalid data store` Fatal Error on main Stripe Settings Page

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gateway-stripe#1361] opened 2020-11-10 16:36 UTC
**Describe the bug**

After cloning from Github I'm seeing a fatal error on the settings page for Stripe.

```
Fatal error: Uncaught Exception: Invalid data store. in /srv/www/wordpress-one/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php:107 Stack trace: #0 /srv/www/wordpress-one/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(139): WC_Data_Store->__construct('admin') #1 /srv/www/wordpress-one/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/admin/class-wc-stripe-inbox-notes.php(30): WC_Data_Store::load('admin-note') #2 /srv/www/wordpress-one/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-apple-pay-registration.php(121): WC_Stripe_Inbox_Notes::notify_of_apple_pay_domain_verification_if_needed() #3 /srv/www/wordpress-one/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-apple-pay-registration.php(70): WC_Stripe_Apple_Pay_Registration->init_apple_pay() #4 /srv/www/wordpress-one/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-apple-pay-registration.php(342): in /srv/www/wordpress-one/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php on line 107
```

This doesn't appear to be affecting the version on .org so is likely from a recent commit. 

**To Reproduce**
1. New install with WooCommerce and Stripe 
2. Go to the settings page here: wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe
3. Fatal error is show

**Environment (please complete the following information):**
 - WordPress Version 5.5.3
 - WooCommerce Version 4.8.0
 - Stripe Plugin Version 4.5.3 (from master)

**Comment by dechov** [comment] 2020-11-11 00:38
Thank you for reporting – I reproduced it with WC 4.7 and 4.6 as well.

This was caused by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1337: I'd previously only tested that with the WooCommerce Admin feature plugin activated, which masks the issue as it apparently adds the `admin-note` data store [[source](https://github.com/woocommerce/woocommerce-admin/blob/daa599b0d02d9c06849888ec6252179d5c1b457a/src/API/Init.php#L135)] (via [this code](https://github.com/woocommerce/woocommerce-admin/blob/main/src/FeaturePlugin.php#L174)) at an earlier point.

I believe **this is now fixed** with the merge of https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1357, which happens to move the caller function to a later hook.

FYI @jrodger in case this affects https://github.com/Automattic/woocommerce-payments/pull/1044 (though hopefully it wouldn't since I was probably just loading it way too early)

**Comment by dechov** [comment] 2020-11-13 21:53
This is fixed as far as I can tell, as noted above – please re-open if encountered after recent changes.

**Closed by dechov** 2020-11-13 21:53 UTC
Labels: Priority: High
