### ISSUE TITLE
statement_descriptor support

### ISSUE THREAD

**Issue by michaelholloway** [woocommerce/woocommerce-gateway-stripe#130] opened 2016-12-15 17:49 UTC
Do you plan to add support for the statement descriptor field?
https://support.stripe.com/questions/how-do-statement-descriptors-work-with-platforms

Because our stripe account is used for a few of our shops, we'd like to be able to override the statement descriptor to assist our customers in identifying the source of their purchase and minimizing chargebacks and confusion. You'll see in the article above that "...this can be customized on a per-charge basis—something we recommend for all Stripe Connect charges." 

Please include support for this field. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment] 2016-12-16 03:20
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/9b2fd44cc5fad167ecf87a1d46b9531a7db9c816

**Closed by roykho** 2016-12-16 03:20 UTC
Labels: [Pri] Normal, [Type] Enhancement

**Comment by vizanto** [comment] 2017-08-03 09:02
It doesn't look like the `statement_descriptor` field is actually used?
```
"statement_descriptor": {
      "id": "statement_descriptor",
      "label": "Statement Descriptor",
      "description": "Extra information about a charge. This will appear on your customer’s credit card statement.",
      "type": "text",
      "value": "Local WP Dev",
      "default": "",
      "tip": "Extra information about a charge. This will appear on your customer’s credit card statement.",
      "placeholder": ""
    },
```

https://github.com/woocommerce/woocommerce-gateway-stripe/tree/master/docs/api

**Comment by vizanto** [comment] 2017-08-03 09:11
(I don't see it in stripe dashboard in the POST request body)

**Comment by roykho** [comment] 2017-10-26 22:42
@geeklore I would wait for 4.0 to launch before revisiting this again as much has changed in this department.

**Comment by geeklore** [comment] 2017-10-26 22:47
Awesome! Thanks for the update!

**Comment by jesucarr** [comment] 2017-11-14 12:34
I can confirm this is still not working, and no code to fix it in the 4.0 branch either. The problem is that the description is being sent only in the "description" parameter, but not in the "statement_descriptor" parameter. 

It would be as easy as duplicate [this line](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/23d8d4baaa60881d3a94fc5fd6b1ddf0efd4e201/includes/class-wc-gateway-stripe.php#L603) for "statement_descriptor". 

Please reopen this issue so this can be done for the next update.

**Comment by roykho** [comment] 2017-11-14 14:51
@jesucarr how did you determine it didn't work in 4.0?

**Comment by vizanto** [comment] 2017-11-15 02:26
Well it obviously will not work when the actual Stripe parameter is not used in code anywhere:
https://github.com/woocommerce/woocommerce-gateway-stripe/issues/130#issuecomment-319911592

**Comment by roykho** [comment] 2017-11-15 02:31
@vizanto you're looking at master, we're talking about 4.0 branch that will be released soon.

**Comment by vizanto** [comment] 2017-11-15 02:33
Tagged milestone is 3.1.0 and nobody answered my comment from august, so I didn't know.
