### ISSUE TITLE
Scheduled Action Error - Uncaught Error: Call to a member function get_meta() on bool

### ISSUE THREAD

**Issue by JoshThomsonx** [woocommerce/woocommerce-gateway-stripe#2602] opened 2023-04-24 12:49 UTC
**Describe the bug**
Getting the following error:
scheduled action 334240 (subscription payment) failed to finish processing due to the following error: Uncaught Error: Call to a member function get_meta() on bool in /wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php:572

**To Reproduce**
N/A

**Expected behavior**
The renewal scheduled action to successfully go through.

**Screenshots**
![Screenshot 2023-04-24 at 13 46 57](https://user-images.githubusercontent.com/97533442/234000356-31f5d47e-c571-4b5b-9e4b-87884346032f.png)

**Environment (please complete the following information):**
 - WordPress Version: 6.2
 - WooCommerce Version: 7.6.0
 - Stripe Plugin Version: 7.3.0
 - Browser [e.g. chrome, safari] and Version: Happens in all browsers but I am using Firefox v113.0b3
 - Any other plugins installed: Quite a few but this issue happens regardless of other plugins being enabled.

**Additional context**
N/A

**Comment by jacoswan** [comment] 2023-04-27 08:05
Also reported in 6239561-zen - lost the merchant during fact-finding, so posting this for now and will update when they reply with additional info. 

Their Subscription renewals are failing, apparently since updating Stripe. 

> 04-27-2023 @ 07:06:53 - scheduled action 982377 (subscription payment) failed to finish processing after 300 seconds

With this error in the fatal-error log: 

```
2023-04-27T07:08:39+00:00 CRITICAL Uncaught Error: Call to a member function get_meta() on bool in /home/customer/www/the_site.co.uk/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php:572
Stack trace:
#0 /home/customer/www/the_site.co.uk/public_html/wp-includes/class-wp-hook.php(308): WC_Stripe_Payment_Gateway->add_subscription_information_to_intent(Array, Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(stdClass))
#1 /home/customer/www/the_site.co.uk/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#2 /home/customer/www/the_site.co.uk/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php(1704): apply_filters('wc_stripe_gener...', Array, Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(stdClass))
#3 /home/customer/www/the_site.co.uk/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions
in /home/customer/wwwthe_site.co.uk/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php on line 572
```

Site features a child theme, code snippets plugin, caching, and importer though, so there's potential for conflict. 

SSR: 
<details> 
```
`
### WordPress Environment ###

WordPress address (URL): https://www.the_site.co.uk
Site address (URL): https://www.the_site.co.uk
WC Version: 7.6.0
REST API Version: ✔ 7.6.0
WC Blocks Version: ✔ 9.8.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.85.0
OpenSSL/3.0.8

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.0
WC Database Prefix: wp_
Total Database Size: 994.40MB
Database Data Size: 649.17MB
Database Index Size: 345.23MB
wp_woocommerce_sessions: Data: 2.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 15.52MB + Index: 4.33MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 102.63MB + Index: 58.16MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_410_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 30.14MB + Index: 21.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 12.11MB + Index: 11.06MB + Engine InnoDB
wp_bn_countries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bn_country_ip_addresses: Data: 7.52MB + Index: 2.52MB + Engine InnoDB
wp_bn_info_blurbs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bn_ip_addresses: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bn_spider_user_agents_keywords: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bn_user_agents_keywords: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_bn_whitelisted_ip_addresses: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bn_whitelisted_user_agents_keywords: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.27MB + Index: 0.27MB + Engine InnoDB
wp_comments: Data: 63.59MB + Index: 37.05MB + Engine InnoDB
wp_gdpr_request_records: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_layerslider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_layerslider_drafts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_layerslider_revisions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_masterslider_options: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_masterslider_sliders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_options: Data: 6.36MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 316.86MB + Index: 154.33MB + Engine InnoDB
wp_posts: Data: 37.52MB + Index: 16.03MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 27.55MB + Index: 22.06MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 0.91MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 3.52MB + Index: 1.92MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 5.52MB + Index: 6.06MB + Engine InnoDB
wp_wc_order_stats: Data: 7.52MB + Index: 5.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 2.52MB + Index: 2.00MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_amazon_buyer_index: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_WP_SEO_404_links: Data: 0.52MB + Index: 0.30MB + Engine MyISAM
wp_WP_SEO_Cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_WP_SEO_Redirection: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_WP_SEO_Redirection_LOG: Data: 0.07MB + Index: 0.01MB + Engine MyISAM
wp_yoast_indexable: Data: 1.06MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 307
cookielawinfo: 7
edge: 10
employees: 3
mkhb_header: 1
nav_menu_item: 28
oembed_cache: 1
page: 38
post: 23
product: 25
product_variation: 40
revision: 731
shipment: 27327
shop_coupon: 10
shop_order: 55224
shop_order_refund: 606
shop_subscription: 798
wpcf7_contact_form: 1
wpcode: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

LayerSlider: by Kreatura Media – 7.6.8
All-in-One WP Migration Unlimited Extension: by ServMask – 2.49
All-in-One WP Migration: by ServMask – 7.73
Artbees Themes Captcha: by Jose Rodriguez  – 1.0
Better Search Replace: by WP Engine – 1.4.2
Bot Nemesis: by Dan Anton & Gregory Ortiz – 1.6
Child Theme Generator: by Serafino Corriero – 2.2.7
Classic Editor: by WordPress Contributors – 1.6.3
Contact Form 7: by Takayuki Miyoshi – 5.7.6
Facebook for WooCommerce: by Facebook – 3.0.19
Flexible Shipping: by Octolize – 4.21.1
Gift Up!: by Gift Up! – 2.19.2
Health Check & Troubleshooting: by The WordPress.org community – 1.6.0
WPCode Lite: by WPCode – 2.0.10
WPBakery Page Builder (Modified Version): by Michael M - WPBakery.com – 6.10.0
Jupiter Core: by Artbees – 1.0.4
Jupiter Donut: by Artbees – 1.4.3
SiteGround Optimizer: by SiteGround – 7.3.1
Trustpilot-reviews: by Trustpilot – 2.5.914
Two Factor Authentication: by David Anderson
original plugin by Oskar Hane and enhanced by Dee Nutbourne – 1.14.14

GDPR Cookie Consent: by markwt – 2.0.1
WooCommerce Address Validation: by SkyVerge – 2.10.0
Codisto Channel Cloud: by Codisto – 1.3.65
DPD UK & DPD Local Labels and Tracking: by Octolize – 2.0.4
WooCommerce Amazon Pay: by WooCommerce – 2.4.1
WooCommerce Stripe Gateway: by WooCommerce – 7.3.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.7.1
WooCommerce PayPal Payments: by WooCommerce – 2.0.4
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.5.2
WooCommerce Protected Categories: by Barn2 Plugins – 2.6.1
WooCommerce Shipment Tracking: by WooCommerce – 2.3.1
WooCommerce Subscriptions: by WooCommerce – 5.0.1
WooCommerce: by Automattic – 7.6.0 (update to version 7.6.1 is available)
Yoast SEO: by Team Yoast – 20.6
410 for WordPress: by Samir Shah – 0.8.7
WP Crontrol: by John Blackbourn & contributors – 1.15.2
WP GDPR Fix Pro: by TEKNIKFORCE – 4.0

### Inactive Plugins (1) ###

User Role Editor: by Vladimir Garagulya – 4.63.3

### Dropin Plugins (1) ###

object-cache.php: Memcached

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #611 - /shop/
Basket: #613 - /cart/
Checkout: #616 - /checkout/
My account: #1431 - /my-account/
Terms and conditions: #1146 - /terms-conditions/

### Theme ###

Name: ChildTheme
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Jupiter
Parent Theme Version: 6.10.2
Parent Theme Author URL: http://themeforest.net/user/artbees
WooCommerce Support: ✔

### Templates ###

Overrides: jupiter/framework/admin/customizer/woocommerce/templates/cart/cart.php version 3.8.0 is out of date. The core version is 7.4.0
jupiter/framework/admin/customizer/woocommerce/templates/cart/proceed-to-checkout-button.php version 2.4.0 is out of date. The core version is 7.0.1
jupiter/framework/admin/customizer/woocommerce/templates/checkout/form-shipping.php
jupiter/framework/admin/customizer/woocommerce/templates/checkout/review-order.php
jupiter/framework/admin/customizer/woocommerce/templates/checkout/terms.php
jupiter/framework/admin/customizer/woocommerce/templates/global/quantity-input.php version 4.0.0 is out of date. The core version is 7.4.0
jupiter/framework/admin/customizer/woocommerce/templates/loop/add-to-cart.php
jupiter/framework/admin/customizer/woocommerce/templates/order/order-details-item.php

Outdated Templates: ❌
                    
                    
                        Learn how to update

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://www.the_site.co.uk
Subscriptions-core Library Version: 5.5.0
Subscription Statuses: wc-active: 128
wc-pending-cancel: 2
wc-pending: 2
wc-on-hold: 298
wc-cancelled: 368

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United Kingdom (UK)

### Subscriptions by Payment Gateway ###

Amazon Pay: wc-active: 9
wc-cancelled: 6
wc-on-hold: 8

PayPal: wc-active: 11
wc-cancelled: 23
wc-on-hold: 7

other: wc-active: 2
wc-cancelled: 121
wc-on-hold: 82
wc-pending-cancel: 1

Stripe: wc-active: 94
wc-cancelled: 85
wc-on-hold: 103
wc-pending-cancel: 1


### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

Amazon Pay: products
refunds
subscriptions
subscription_date_changes
subscription_suspension
subscription_reactivation
subscription_cancellation
multiple_subscriptions
subscription_payment_method_change_customer
subscription_amount_changes

PayPal: refunds
products
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions


### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: GB
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: ✔
Reference Transactions: ✔
Used PayPal Checkout plugin: ✔
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-27 19:05:39 +00:00
Options: ✔
Notes: 131
Onboarding: completed

### Address Validation ###

Active Provider: Loqate (legacy - UK)
Configured: ✔
API Username: 
Debug Mode: No
Geocode Addresses: No
Classify Addresses: No
Force Customer to look-up address via Postcode: No

### Action Scheduler ###

Complete: 50,006
Oldest: 2023-03-27 07:12:13 +0000
Newest: 2023-04-27 07:09:01 +0000

Failed: 335
Oldest: 2019-10-10 10:16:33 +0000
Newest: 2023-04-26 11:41:09 +0000

Pending: 147
Oldest: 2023-04-27 07:16:53 +0000
Newest: 2023-08-14 06:05:12 +0000


### Status report information ###

Generated at: 2023-04-27 07:09:58 +00:00
`
```
</details>

**Comment by n9yty** [comment] 2023-04-27 15:16
I also saw this, I was wondering if it was related to the other issue to subscriptions without a parent order (#2601).

We are in a tough spot. Moving to 7.3.0 broke our subscription renewals, and since we reverted to 7.2.0 we are getting some customers who cannot place an order due to a "Source not found" with a pm_ value, like it is trying to use a payment method as source instead of card. Support has been less than zero help.

**Comment by ryanr14** [comment] 2023-05-01 13:31
6241839-zen

**Comment by ryanr14** [comment] 2023-05-01 14:08
6250236-zen

**Comment by Mxchael** [comment] 2023-05-01 21:02
6251650-zen

**Comment by stevewest15** [comment] 2023-05-01 23:40
One of our customers is impacted by this issue (ticket 6251650). Wish WC or WP would have sent an email to WP admin/store manager to alert them of this issue. 

Hope there is a fix for this issue soon.

**Comment by n9yty** [comment] 2023-05-02 00:22
No hurry to fix it apparently

**Comment by AashikP** [comment] 2023-05-02 04:17
Another report in 6252411-zen

**Comment by AashikP** [comment] 2023-05-02 06:37
**Steps to replicate:**

1. Create a manual Subscription with Stripe and Add Customer and Payment details
2. Set the Subscription to Active (don't add any parent order)
3. Try to process renewal for the Subscription
4. Find this error in the logs:

```
2023-05-02T06:34:28+00:00 CRITICAL Uncaught Error: Call to a member function get_meta() on bool in /srv/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php:572
Stack trace:
#0 /wordpress/core/6.2/wp-includes/class-wp-hook.php(308): WC_Stripe_Payment_Gateway->add_subscription_information_to_intent(Array, Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(stdClass))
#1 /wordpress/core/6.2/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#2 /srv/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php(1704): apply_filters('wc_stripe_gener...', Array, Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(stdClass))
#3 /srv/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php(285): WC_Stripe_Payment_Gateway->create_and_confirm_intent_for_off_session(Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(stdClass), '20.00')
#4 /srv/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php(189): WC_Stripe_Payment_Gateway->process_subscription_payment('20.00', Object(Automattic\WooCommerce\Admin\Overrides\Order), true, false)
#5 /wordpress/core/6.2/wp-includes/class-wp-hook.php(308): WC_Stripe_Payment_Gateway->scheduled_subscription_payment('20.00', Object(Automattic\WooCommerce\Admin\Overrides\Order))
#6 /wordpress/core/6.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#7 /wordpress/core/6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /srv/htdocs/wp-content/plugins/woocommerce-subscriptions/includes/gateways/class-wc-subscriptions-payment-gateways.php(97): do_action('woocommerce_sch...', '20.00', Object(Automattic\WooCommerce\Admin\Overrides\Order))
#9 /srv/htdocs/wp-content/plugins/woocommerce-subscriptions/includes/gateways/class-wc-subscriptions-payment-gateways.php(81): WC_Subscriptions_Payment_Gateways::trigger_gateway_renewal_payment_hook(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#10 /wordpress/core/6.2/wp-includes/class-wp-hook.php(308): WC_Subscriptions_Payment_Gateways::gateway_scheduled_subscription_payment(7953)
#11 /wordpress/core/6.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#12 /wordpress/core/6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#13 /srv/htdocs/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/admin/class-wcs-admin-meta-boxes.php(244): do_action('woocommerce_sch...', 7953)
#14 /wordpress/core/6.2/wp-includes/class-wp-hook.php(308): WCS_Admin_Meta_Boxes::process_renewal_action_request(Object(WC_Subscription))
#15 /wordpress/core/6.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#16 /wordpress/core/6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#17 /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-actions.php(173): do_action('woocommerce_ord...', Object(WC_Subscription))
#18 /wordpress/core/6.2/wp-includes/class-wp-hook.php(308): WC_Meta_Box_Order_Actions::save(7953, Object(WP_Post))
#19 /wordpress/core/6.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#20 /wordpress/core/6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#21 /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-meta-boxes.php(258): do_action('woocommerce_pro...', 7953, Object(WP_Post))
#22 /wordpress/core/6.2/wp-includes/class-wp-hook.php(310): WC_Admin_Meta_Boxes->save_meta_boxes(7953, Object(WP_Post))
#23 /wordpress/core/6.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#24 /wordpress/core/6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#25 /wordpress/core/6.2/wp-includes/post.php(4715): do_action('save_post', 7953, Object(WP_Post), true)
#26 /wordpress/core/6.2/wp-includes/post.php(4817): wp_insert_post(Array, false, true)
#27 /wordpress/core/6.2/wp-admin/includes/post.php(439): wp_update_post(Array)
#28 /wordpress/core/6.2/wp-admin/post.php(227): edit_post()
#29 {main}
  thrown in /srv/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php on line 572
```

**Comment by jacoswan** [comment] 2023-05-02 07:19
Another reported in 6252544-zen

**Comment by adxmeliora** [comment] 2023-05-02 08:26
Also having this issue.... critical for my client's website.

**Comment by imodouglas** [comment] 2023-05-02 08:41
This is the same with issue #2595 which has been fixed and should be released soon.

**Comment by glagonikas** [comment] 2023-05-02 09:13
@imodouglas do we have an ETA for releasing this? It's obviously a major issue considering how many reports there have been (and knowing even more people wouldn't have noticed)

**Comment by imodouglas** [comment] 2023-05-02 12:24
AFAIK, there is no ETA for the next release but I anticipate it should be out in a few days.

**Comment by n9yty** [comment] 2023-05-02 13:18
Such a sad response considering this is a critical and vital function of an e-commerce store. We tried to roll back to 7.2.0 and that caused other issues, there is no escape here except to fix the problem and there doesn’t seem to be the proper sense of urgency to do so.

**Comment by Mxchael** [comment] 2023-05-02 22:09
6255498-zen

**Comment by xue28** [comment] 2023-05-04 07:31
6259883-zen

**Comment by pallavic27** [comment] 2023-05-04 10:16
Hi,

I have WooCommerce Stripe Gateway V7.3.0 and WooCommerce V7.6.1 and WooCommerce subscriptions V4.9.1.

Noticed that from last few days stripe renewals are not happening. So checked in WooCommerce -> Status -> Scheduled Actions. The subscription payment is in pending status and it is not firing on the scheduled date. E,g – For Apr month renewals have not been fired.

woocommerce_scheduled_subscription_payment is in Pending status

I am not getting fatal error related to get_meta() though. And the issue is with all stripe renewals (not the issue of parent order does not exist) from last 3 months. 

When this issue will be fixed and is there a quick solution to this? I searched for woocommerce_scheduled_subscription_payment hook in Scheduled Actions tab and there are more than 100 records. Do I have to run it one by one or is there any automated way?

**Comment by glagonikas** [comment] 2023-05-04 10:37
@pallavic27 version 7.4.0 was released yesterday and it's meant to be fixing this issue so try updating and see how it goes.

**Comment by pallavic27** [comment] 2023-05-04 11:18
@glagonikas 

I saw new version is released. But it is for 'Issue processing renewals for subscriptions without parent orders.'.

I have different issue so not sure whether it will help. Also someone from plugin support team mentioned today that this is known issue and redirected here. New plugin was already released that time. So not sure.

**Comment by glagonikas** [comment] 2023-05-04 12:02
@pallavic27 sounds like your issue is not related to this thread tho? Not sure why they redirected you here, but to avoid confusion, maybe you should search for similar issues here https://github.com/woocommerce/woocommerce-gateway-stripe/issues and possibly raise a new one if none exist?

**Comment by foosantos** [comment] 2023-05-05 00:51
6239088-zen

**Comment by felipevelzani** [comment] 2023-05-05 00:54
I see this is actually a duplicate issue of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2595, as mentioned before. 

I'm closing this one and you can refer to the main issue for updates.

**Closed as completed by felipevelzani** 2023-05-05 00:54 UTC
Labels: type: bug, impact: high
