### ISSUE TITLE
Google Pay not recognizing existing user account on checkout.

### ISSUE THREAD

**Issue by avantegarde** [woocommerce/woocommerce-gateway-stripe#2430] opened 2022-09-22 14:15 UTC
**Describe the bug**
When using Google Pay (Express Checkouts) while logged out b

**To Reproduce**

1. Be a new user (Google Pay email not associated with any user in WordPress) – check out using Gpay.
    - A new account is created during the checkout and is automatically logged in (password sent separately in email) – Working as intended.
2. Log out and clear the cookies. Or come back later after the cookie has expired. The goal is to make WordPress & WooCommerce think you are a "guest" who is not logged in.
3. Attempt to make a purchase using Google Pay.
4. See error: “There was an error processing your order”.

If you attempt steps 1-4 above but instead use the Stripe Credit Card fields, you will receive the "An account is already registered with your email address. Please log in." notification.

**Expected behavior**
This should behave the same as when using the credit card fields. When the customer attempts to pay with Google Pay and they have an existing account, it should close the Google Pay popup and then show the "An account is already registered with your email address. Please log in." notification.

**Screenshots**
Actual Behavior
<img width="625" alt="Markup 2022-09-22 at 10 05 35" src="https://user-images.githubusercontent.com/3516737/191768842-809b637d-46f8-4624-a945-565964c8f51d.png">

Expected Behavior
<img width="1251" alt="Markup 2022-09-22 at 10 07 52" src="https://user-images.githubusercontent.com/3516737/191769352-fdc094b4-3f22-431f-bbe3-fb6f9b6cba0a.png">

WooCommerce Account Settings
<img width="1147" alt="Markup 2022-09-22 at 10 09 55" src="https://user-images.githubusercontent.com/3516737/191769848-98c9e261-fafa-4762-bf0c-17d5d1123ec7.png">

**Environment (please complete the following information):**
 - WordPress Version 6.0.2
 - WooCommerce Version 6.9.3
 - Stripe Plugin Version 6.7.0
 - Chrome Version 105.0.5195.125

**Additional Information**
Ticket -> 5571384-zd-woothemes

**Comment by charlesrr** [comment] 2022-09-22 17:10
I was the person that reported this to the Woo team originally. Please note that I was only able to test with GPay. It's possible the same issue would happen with ApplePay.

**Comment by tijosh** [comment] 2022-09-23 19:00
I believe this problem is due to the First Name | Last Name billing fields being required. I've been testing this and can't check out with Google Pay in Test Mode:

![image](https://user-images.githubusercontent.com/35117248/192038801-68502976-868e-4c50-b9ee-43467a69a21e.png)

![image](https://user-images.githubusercontent.com/35117248/192038718-8ccb4e01-1e5c-402b-b1cc-006d65452a9c.png)

If I make First Name and Last Name not required using another plugin, I can check out successfully. I don't know if this applies to Live Mode as well.

**Comment by charlesrr** [comment] 2022-09-27 11:01
> I believe this problem is due to the First Name | Last Name billing fields being required. I've been testing this and can't check out with Google Pay in Test Mode:
Snip
> If I make First Name and Last Name not required using another plugin, I can check out successfully. I don't know if this applies to Live Mode as well.

That sounds unrelated from this issue. I can checkout fine with GPay as long as there is no matching user in the system already.

**Comment by anastas10s-afk** [comment] 2022-11-17 11:04
5719339-zen

**Comment by charlesrr** [comment] 2022-11-18 20:07
Is there any way to get the importance of this issue upgraded? The issue renders the Express Checkout pointless. If I turn on express checkout, it just confuses all my repeat customers, so I've had to disable it. In the Learndash group I'm in, there are other people who also wish they could use Express Checkout but can't because of this. It seems like it should just be changing an error message text, so could be quite a quick fix, although I’m not a coder, so I’m probably deluded!

**Comment by hp7** [comment] 2022-11-24 13:25
This issue occurs with Apple Pay as well; however the expected behavior/solution is flawed as well. 

The Solution should allow the users transaction through even when a matching account is found. Especially if the allow guest checkout function is active in Woocommerce. 

If a matching account is found, just add it to the accounts records or just treat it as any other guest checkout. 

GPay and Apple Pay are financial transaction tools not account creation tools

**Comment by sarbouw** [comment] 2022-11-27 20:32
5737478-zd

**Comment by charlesrr** [comment] 2022-11-30 09:34
> This issue occurs with Apple Pay as well; however the expected behavior/solution is flawed as well.
> 
> The Solution should allow the users transaction through even when a matching account is found. Especially if the allow guest checkout function is active in Woocommerce.
> 
> If a matching account is found, just add it to the accounts records or just treat it as any other guest checkout.
> 
> GPay and Apple Pay are financial transaction tools not account creation tools

I don't like that idea. It allows someone to enter a transaction on someone else's account. Apple Pay lets you change the email to whatever

**Comment by hp7** [comment] 2022-11-30 14:14
> > This issue occurs with Apple Pay as well; however the expected behavior/solution is flawed as well.
> > The Solution should allow the users transaction through even when a matching account is found. Especially if the allow guest checkout function is active in Woocommerce.
> > If a matching account is found, just add it to the accounts records or just treat it as any other guest checkout.
> > GPay and Apple Pay are financial transaction tools not account creation tools
> 
> I don't like that idea. It allows someone to enter a transaction on someone else's account. Apple Pay lets you change the email to whatever

Then make it a guest checkout without assigning to an account and allow the user to add the order to their account later by verifying the matched email address that was used from Apple Pay or Google Pay

**Comment by charlesrr** [comment] 2022-12-01 11:52
> > > This issue occurs with Apple Pay as well; however the expected behavior/solution is flawed as well.
> > > The Solution should allow the users transaction through even when a matching account is found. Especially if the allow guest checkout function is active in Woocommerce.
> > > If a matching account is found, just add it to the accounts records or just treat it as any other guest checkout.
> > > GPay and Apple Pay are financial transaction tools not account creation tools
> > 
> > 
> > I don't like that idea. It allows someone to enter a transaction on someone else's account. Apple Pay lets you change the email to whatever
> 
> Then make it a guest checkout without assigning to an account and allow the user to add the order to their account later by verifying the matched email address that was used from Apple Pay or Google Pay

I don't allow guest checkout - an order has to either create an account or be linked to an account so that wordpress can enrol them on the digital course product. Users are used to logging in before making additional purchases or being reminded to login (when using credit card method) - Just need the same reminder for express checkout method - a simple change to a line of text that would avoid confusion and solve the issue straight away. If the whole thing needs redesigning as you suggest (which would include credit card payments too), that can come later in a separate bug report.

**Comment by anastas10s-afk** [comment] 2023-08-17 10:30
6667831-zd from what I gather

**Comment by diamondcollective** [comment] 2023-08-17 11:10
Is there any further progress on this issue? I've tested removing my billing first and last name using:

`    $checkout_fields['billing']['billing_last_name']['required'] = false;
    $checkout_fields['billing']['billing_first_name']['required'] = false;`

However this does not fix the issue either, I've tried looking for errors in my console and it doesn't even show up in there or inspect element anywhere either so not sure how to go about debugging this further.

I contacted support and gave them everything they asked for and they just told me to turn it off and check this ticket here for updates even though no one from woocommerce is assigned to it and there's no milestones for fixing their issue.

**Comment by charlesrr** [comment] 2023-08-20 11:23
Sadly not that I'm aware of. If I turn on express checkout, it causes too much confusion for my customers, so I can't use it. I guess now that woocommerce payments is a thing, they might not be too bothered about other options.

**Comment by charlesrr** [comment] 2024-02-16 12:43
Does anyone know if there is an alternative plugin that handles express checkout with stripe properly?

**Comment by charlesrr** [comment] 2024-03-25 15:21
I've tested a replacement plugin: "Stripe Payment Plugin for WooCommerce". It solves this issue. If you try to pay by gpay while NOT logged in but there is an account with the details already registered in wordpress, it says "An account is already registered with your email address. Please log in". So I'm ditching the official plugin.

**Closed as completed** 2024-09-10 15:01 UTC
Labels: type: bug, component: payment request buttons, priority: medium
