### ISSUE TITLE
Payments displayed as “disabled” under account setting when upgrading from 5.7.0

### ISSUE THREAD

**Issue by Petbeginners** [woocommerce/woocommerce-gateway-stripe#2175] opened 2021-11-20 18:18 UTC
Hi,

There seems to be a bug with the payments displaying as “disabled” under account settings when updating the plugin from 5.7.0 to 5.8.0, with all the Stripe credentials properly filled in.

Under Settings -> Account details -> Payments: Disabled
Deposits: Enabled
Webhooks: Enabled

The Payments icon still appears as disabled even after everything is filled in correctly – see screenshot https://snipboard.io/TQ0wfR.jpg

Steps to reproduce issue:
1) Update Stripe woocommerce plugin from 5.7.0 to 5.8.0
2) Under settings -> account details, the payments still show as disabled even though the account keys and webhook details have already be pre-filled in

**Comment by aheckler** [comment] 2021-11-22 15:09
The UI here does seem suboptimal, even in Test Mode. Before:

![Screenshot taken on 2021-11-22 at 15 05 20 UTC](https://user-images.githubusercontent.com/5512652/142885340-16926f11-1aa5-4407-bea6-8d5f9ed48f4a.jpeg)

I see no real warnings, and my site works fine in test mode. I can accept test payments and so on.

After:

![Screenshot taken on 2021-11-22 at 15 06 11 UTC](https://user-images.githubusercontent.com/5512652/142885360-991226fc-c760-4f9d-ac86-57f53b7bd527.jpeg)

My site still works fine in Test Mode, but the warnings are disconcerting, especially since I can indeed take test payments.

**Comment by apmwebdev** [comment] 2021-11-24 22:24
Another user running into the same issue here: https://wordpress.org/support/topic/bug-payments-disabled-after-updating-to-5-8-0/#post-15100602

**Comment by ahfant** [comment] 2021-11-27 12:30
Facing the same issue as well - would be keen to know if there is an expected resolution time for this? Thanks in advance!

**Comment by nagpai** [comment] 2021-12-01 13:42
I was seeing a similar view as @aheckler on my test site. Using this option 

![image](https://user-images.githubusercontent.com/4162931/144244699-a6bce3cc-da61-42d0-9993-6f9c3f25a851.png)


I disconnected the account, and reconnected it. When I clicked `Edit account keys` The keys fields were blank. I had to enter them again and I now see 
![image](https://user-images.githubusercontent.com/4162931/144244857-f47d783f-9bb1-49c7-a711-46a01614bd1b.png)

**Comment by nagpai** [comment] 2021-12-01 13:56
Sorry deleted my earlier comment. I had accidentally connected another live account I had and was unable to replicate the issue on that. I was able to change the status by a disconnect and reconnect, and adding the keys again

In case of my test account (US as country) , I am getting same results as @aheckler  (sorry tagging you too much today ;) )

**Comment by dsvwilson** [comment] 2021-12-02 22:08
Issue reported in 4535436-zd

**Comment by wyter** [comment] 2021-12-15 19:33
Also reported in 4611979-zd

**Comment by thisissandip** [comment] 2021-12-17 16:25
Another report in 4618847-zd

**Comment by aheckler** [comment] 2021-12-17 21:18
4573201-zen

**Comment by wpniall** [comment] 2021-12-18 14:09
4618760-zen

**Comment by sukafia** [comment] 2021-12-18 16:53
Payout disabled for 33268381-hc. Stripe confirmed everything is fine on their end & referred to us.

**Comment by phillipcornwell** [comment] 2021-12-18 22:46
Deposits disabled for 4576515-zd-woothemes. Stripe tells them that side of things are okay and referred the to us.

**Comment by nicdwilson** [comment] 2021-12-19 00:50
4621189-zen

**Comment by Snaacks** [comment] 2021-12-20 02:04
Another user in https://wordpress.org/support/topic/bug-payments-disabled-after-updating-to-5-8-0/#post-15178917 reporting this issue.

**Comment by martynmjones** [comment] 2021-12-22 12:53
4619899-zen

**Comment by anant1811** [comment] 2021-12-23 09:55
Also reported in #4619615-zen

**Comment by sukafia** [comment] 2021-12-24 10:07
4635279-zen

**Comment by raifd** [comment] 2021-12-27 14:06
4639946-zd also

**Comment by darcie** [comment] 2021-12-29 18:29
33405806-hc

**Comment by namiokuzono** [comment] 2021-12-29 20:26
4642065-zen

**Comment by chrism245** [comment] 2021-12-30 13:15
33415565-hc

**Comment by kvvsi** [comment] 2021-12-31 00:54
4647453-z

**Comment by chrism245** [comment] 2021-12-31 15:46
4647690-zen

**Comment by diegocurbelo** [comment] 2021-12-31 19:33
This `Disabled` status is displayed when the `card_payments` account capability is not `active` in Stripe:
<img width="222" alt="Screen Shot 2021-12-31 at 16 01 20" src="https://user-images.githubusercontent.com/407542/147836378-bf8eb952-6dcb-4213-bef2-c4d72ebee706.png">

Those account `capabilities` are obtained (and [cached for 2 hours](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4f47751f5dd3d26eb245878a936f96510a11d2e4/includes/class-wc-stripe-account.php#L79)) from Stripe's Accounts API: `https://api.stripe.com/v1/account` [Stripe docs here](https://stripe.com/docs/api/accounts/object).

```
{
  "id": "acct_xxx",
  "object": "account",
  "business_profile": { ... },
  "capabilities": {
    "card_payments": "active",
    "transfers": "active",
    "ideal_payments": "inactive",
    "p24_payments": "inactive",
    "sepa_debit_payments": "inactive",
  },
  "payouts_enabled": true,
  ...
  "type": "standard"
}
```

This `inactive` means that additional information is necessary to enable the payment method, and can be verified/completed at: https://dashboard.stripe.com/settings/payment_methods
<img width="948" alt="Screen Shot 2021-12-31 at 16 24 53" src="https://user-images.githubusercontent.com/407542/147836960-1dc27867-66fe-4888-ab5b-ecc6dfc9f3de.png">

---

Can we can ask the next merchant with this problem, to verify that they have the Cards payments information complete?
It should look like this:
<img width="946" alt="Screen Shot 2021-12-31 at 16 24 37" src="https://user-images.githubusercontent.com/407542/147836958-bbc98c2c-5226-4be5-91f0-4c6d4d82db87.png">

And also confirm the API response... it can be tested out from the terminal with:
```
curl https://api.stripe.com/v1/account -u sk_live_key:
```
_(notice the `:` after the stripe key at the end)_

**Comment by nataib** [comment] 2022-01-04 05:51
> 
> Can we can ask the next merchant with this problem, to verify that they have the Cards payments information complete? It should look like this: <img alt="Screen Shot 2021-12-31 at 16 24 37" width="946" src="https://user-images.githubusercontent.com/407542/147836958-bbc98c2c-5226-4be5-91f0-4c6d4d82db87.png">
> 
> And also confirm the API response... it can be tested out from the terminal with:
> 
> ```
> curl https://api.stripe.com/v1/account -u sk_live_key:
> ```
> 
> _(notice the `:` after the stripe key at the end)_


I checked my Stripe account API and it looks like the capabilities are all active.
<img width="279" alt="Screen Shot 2022-01-04 at 1 30 40 PM" src="https://user-images.githubusercontent.com/89171666/148014195-986de59e-54a3-4137-8421-d214ee4ab623.png">

When I go to Stripe Payment methods page, Card payment hasn't been turned on. At the top of the page there's a warning about switching to the latest version of Checkout or Payment Element. I presume I'm using the old Stripe API? My site has been accepting Stripe payments the whole time even though the woocommerce settings says payments are "disabled" (I connected Stripe to the website 5+ years ago, it's only recently the settings changed to disabled, but no interruption of accepting payments).

<img width="1248" alt="Screen Shot 2022-01-04 at 1 32 49 PM" src="https://user-images.githubusercontent.com/89171666/148014984-580121e0-fd39-4e8e-a2ce-a7962d031534.png">

**Comment by EjayhanFernandes** [comment] 2022-01-04 07:16
Similar issue here: 4653932-zen. Asked the merchant to verify if they have the Cards payments information complete. Update: The user decided to proceed with WooCommerce Payments instead and seems to work fine for them.

**Comment by yuumgo** [comment] 2022-01-11 15:10
I have managed to correct this notice by creating a new API secret key, however the site (new installation) still does not receive payments showing the error: **The card was declined**

I have also verified that the cards are activated on the stripe desktop as suggested by diegocurbelo

**Comment by thisissandip** [comment] 2022-01-12 08:21
4679768-zen

**Comment by chrism245** [comment] 2022-01-14 14:52
4683702-zen

**Comment by ghost** [comment] 2022-01-17 22:13
https://wordpress.org/support/topic/payouts-disabled-3/

**Comment by chrism245** [comment] 2022-01-17 22:57
4692433-zen

**Comment by arichardsmith** [comment] 2022-01-18 01:07
We have this issue too. In our case both test payments and live payments work fine.

Despite card payments working fine, calling `https://api.stripe.com/v1/account` with both test and live keys doesn't show `card_payments` in the capabilities list.
Calling `https://api.stripe.com/v1/accounts/{account_id}/capabilities/card_payments` shows the capability is unrequested along with some required information that we have already added:
```json
{
  "id": "card_payments",
  "object": "capability",
  "account": "{account_id}",
  "future_requirements": {
    ... all empty
  },
  "requested": false,
  "requested_at": null,
  "requirements": {
    "alternatives": [

    ],
    "current_deadline": null,
    "currently_due": [
      "person_ID.phone",
      "person_ID.relationship.title",
      "relationship.director"
    ],
    "disabled_reason": "requirements.fields_needed",
    "errors": [

    ],
    "eventually_due": [
      "person_ID.phone",
      "person_ID.relationship.title",
      "relationship.director"
    ],
    "past_due": [
      "person_ID.phone",
      "person_ID.relationship.title",
      "relationship.director"
    ],
    "pending_verification": [

    ]
  },
  "status": "unrequested"
}
```

I spoke to stripe support. They said payments are working fine and there are no errors in their logs, so everything seems fine to them.

**Comment by sukafia** [comment] 2022-01-18 16:55
4697529-zen

**Comment by thuautp** [comment] 2022-01-19 10:34
4700420-zen

**Comment by EjayhanFernandes** [comment] 2022-01-19 11:30
4700533-zen

**Comment by orhanfernandes** [comment] 2022-01-20 06:25
Another one on 4703208-zen

**Comment by joashrajin** [comment] 2022-01-21 09:43
+1 33477760-hc

**Comment by sukafia** [comment] 2022-01-24 09:08
4714402-zen

**Comment by sukafia** [comment] 2022-01-24 10:59
4714581-zen

**Comment by EricaKuschel** [comment] 2022-01-24 22:34
21947998-hc

**Comment by amElnagdy** [comment] 2022-01-25 10:40
4717664-zen

**Comment by grig-23** [comment] 2022-01-25 14:03
4716996-zen - same with Stripe 6.0.0, there was no upgrade though - version 6.0.0 of Stripe plugin was installed on a fresh WordPress/WooCommerce install.

**Comment by kvvsi** [comment] 2022-01-25 18:08
4716317-z

**Comment by aheckler** [comment] 2022-01-25 18:32
4718873-zen

**Comment by SirDarcanos** [comment] 2022-02-01 10:39
4738948-zen

**Comment by dsvwilson** [comment] 2022-02-02 13:33
25642600-hc

**Comment by namiokuzono** [comment] 2022-02-04 18:28
4749582-zen

**Comment by melek** [comment] 2022-02-04 22:03
4750560-zen
4745661-zen

**Comment by RiaanKnoetze** [comment] 2022-02-05 10:32
@diegocurbelo - It seems this issue, despite not affecting underlying payments (test or live), is generating a lot of seemingly unnecessary support interactions. Is there anything we can do from Happiness' side to resolve these or do you have a fix in the works already? Maye it needs a higher priority based on the confusion it is currently causing for merchants?

**Comment by thisissandip** [comment] 2022-02-10 11:26
4765303-zen

**Comment by EricaKuschel** [comment] 2022-02-11 21:30
During my review of this report, I noticed that both `Test` and `Live` were enabled at the same time in the initial screenshot. If test is enabled, one would hope that `live` payments were disabled, no?

4686488-zen

**Comment by rashedripon** [comment] 2022-02-15 09:07
Reported 4772491-zen

**Comment by thisissandip** [comment] 2022-02-17 05:31
4763129-zen

**Comment by kaushikasomaiya** [comment] 2022-02-17 07:12
Reported in 4776519-zen

**Comment by neilmccreadie** [comment] 2022-02-18 10:37
34260185-hc

**Comment by kimerlin81** [comment] 2022-02-18 18:50
And another one - 4792295-zd-woothemes

**Comment by senff** [comment] 2022-02-22 20:37
4792230-zen

**Comment by stuartduff** [comment] 2022-02-26 13:17
33401790-hc

**Comment by amElnagdy** [comment] 2022-03-01 10:32
12910857-hc

**Comment by orhanfernandes** [comment] 2022-03-01 23:15
34252504-hc

**Comment by kaushikasomaiya** [comment] 2022-03-05 10:21
4826709-zen

**Comment by amElnagdy** [comment] 2022-03-07 17:23
4836736-zen

**Comment by aheckler** [comment] 2022-03-08 19:45
4811630-zen

**Comment by wyter** [comment] 2022-03-10 10:58
4846936-zen

**Comment by chrism245** [comment] 2022-03-10 15:32
4840807-zen

**Comment by EjayhanFernandes** [comment] 2022-03-12 10:03
4851206-zen

**Comment by sokulski** [comment] 2022-03-15 00:22
Howdy. I know y'all have this marked as high priority, but I was having an unrelated Stripe issue and this sent me on a red-herring journey for a nice chunk of time.

While it is a cosmetic issue, it sure was annoying to discover that it was leading me astray.

**Comment by amElnagdy** [comment] 2022-03-15 17:26
4841413-zen

**Comment by toupper** [comment] 2022-03-17 11:52
4862650-zen

**Comment by felipevelzani** [comment] 2022-03-27 17:35
34915829-hc

**Comment by grig-23** [comment] 2022-03-29 08:11
4888380-zen

**Comment by shohanhossainnab** [comment] 2022-03-29 09:00
Another report: 4891735-zen

**Comment by aheckler** [comment] 2022-03-30 19:45
4903333-zen

**Comment by EjayhanFernandes** [comment] 2022-03-31 00:07
4907990-zen

**Comment by devvnawaz** [comment] 2022-04-03 15:06
4914441 - zen

**Comment by chrism245** [comment] 2022-04-04 19:20
35004254-hc

**Comment by MarcGuay** [comment] 2022-04-05 18:59
Running into this with v6.3.0.  API calls to fetch my account data do not show `card_payments` in the list of `capabilities`.  Spoke to Stripe support and they said that there is no way to change this after account creation.

**Comment by rashedripon** [comment] 2022-04-06 14:41
4923243-zen

**Comment by caseymilne** [comment] 2022-04-08 13:17
I think what @MarcGuay mentions there sounds right because my Stripe account is also from many years ago and I see a range of these notices also. I see "payments off" in test mode, and in live mode I see both "payments off" an "payouts off". 

I also contacted Stripe and they found all aspects of account working including webhooks, but the plugin reports webhook failures as well. 

In total the install has 4 different false debug reports on 2 screens. For the webhooks, refresh does nothing and it reports a webhook failure from days ago even though dozens of successful webhooks have been tested since. Sorry if that's a separate issue, but it seems like it might be related to the notices about payment/payout status because again the API calls seem to fail.

**Comment by thekingsprojects** [comment] 2022-04-09 18:58
Another case here: 4935141-zen

**Comment by sukafia** [comment] 2022-04-11 09:03
4918390-zen

**Comment by neilmccreadie** [comment] 2022-04-12 13:36
4938542-zen

**Comment by darcie** [comment] 2022-04-16 21:49
4951097-zen

**Comment by dreamtooloud** [comment] 2022-04-19 19:52
4958276-zen

**Comment by wyter** [comment] 2022-04-21 12:09
4964000-zen

**Comment by devvnawaz** [comment] 2022-04-24 02:19
4949847-zen

**Comment by jaxr** [comment] 2022-04-25 17:02
4966972-zen

**Comment by NathalyaVides** [comment] 2022-04-27 17:11
5165591-zen

**Comment by senff** [comment] 2022-04-28 01:04
5169895-zen

**Comment by neilmccreadie** [comment] 2022-04-29 13:33
5173252-zen

**Comment by namiokuzono** [comment] 2022-04-30 03:46
35332765-hc

**Comment by tijosh** [comment] 2022-05-02 18:25
5184921-zen

**Comment by namiokuzono** [comment] 2022-05-04 01:23
5184836-zen

**Comment by felipevelzani** [comment] 2022-05-04 11:37
35376672-hc

**Comment by stuartduff** [comment] 2022-05-05 15:26
5190241-zen

**Comment by stuartduff** [comment] 2022-05-06 12:06
5192977-zen

**Comment by stuartduff** [comment] 2022-05-09 11:36
5180416-zen

**Comment by namiokuzono** [comment] 2022-05-09 21:32
5184836-zen

**Comment by amElnagdy** [comment] 2022-05-11 14:26
5205408-zen

**Comment by wyter** [comment] 2022-05-13 12:37
5205398-zen, asked them to await the fix to be shipped

**Comment by stuartduff** [comment] 2022-05-16 13:39
5216770-zen

**Comment by johndcoy** [comment] 2022-05-18 15:49
5221707-zen

**Comment by chrism245** [comment] 2022-05-19 15:57
5224970-zen

**Comment by thisissandip** [comment] 2022-05-20 07:06
5227233-zen

**Comment by amElnagdy** [comment] 2022-05-23 16:15
The issue is Closed and I might not be able to locate the related PR that fixes the issue with the **Payouts** - not the Payments being disabled while they're working.

In #2342, it says 
>This fixes the "Payments" status but https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2175 also has people mentioning that the "Payouts" status is showing "Disabled" incorrectly, which this PR does not address.

What am I missing here?

Another report with the **Payouts** (Stripe 6.4) in 5236366-zen

**Comment by grig-23** [comment] 2022-05-26 10:21
Re-opening since the PR only fixes half of the bug, although let us know if the "payouts are disabled" part requires a separate bug report.

**Comment by EvanDotPro** [comment] 2022-06-22 19:55
> Re-opening since the PR only fixes half of the bug, although let us know if the "payouts are disabled" part requires a separate bug report.

@grig-23 I did update the PR to address both "charges" and "payouts" before it was merged, so I'm going to close this again. I'm going to close this again for now but please feel free to re-open it and clarify if I'm missing anything. Thanks!

**Closed as completed by EvanDotPro** 2022-06-22 19:55 UTC
Labels: type: bug, impact: high
