### ISSUE TITLE
Double Stripe charge on one WooCommerce Order

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-stripe#489] opened 2018-01-29 17:02 UTC
#### Affected ticket(s)

922637-zen
916240-zen
914097-zen
924166-zen
927916-zen

#### What I expected

One Stripe charge and transaction per WooCommerce order

#### What happened instead

Orders paid for by Stripe are showing two Stripe transaction IDs and have been charged twice.

#### Steps to reproduce the issue

No accurate steps but only theme would be that this only happens in Live mode

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by thorsten-stripe** [comment] 2018-01-31 21:22
@roykho this could be due to the idempotency key change. If the webhook handler and the synchronous handler get executed at the same time this could happen, because they now both use unique idempotency keys. @roykho can you investigate?

**Comment by roykho** [comment] 2018-01-31 21:32
@thorsten-stripe this is already taken care of by adding a delay to the webhook processor. Not foolproof but it will prevent issues when both the request and webhook fires at the same time.

**Comment by roykho** [comment] 2018-01-31 21:51
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/c31b68b251c64f9162c8094e314cf81313b54014

Please re-open if same issues arises.

**Comment by zhollenbeak** [comment] 2018-02-08 20:20
@roykho We've had a similar error on a Subscriptions customer site since updating to the latest version of Stripe 4.0.5. Multiple charge attempts are happening on a single order, and multiple emails are going out to customer and admin. Luckily, only one charge has gone through, and it looks like Stripe has rejected the rest.

Here's the error:

```
02-07-2018 @ 09:12:09 - ====Start Log====
Error: stdClass Object
(
    [error] => stdClass Object
        (
            [type] => idempotency_error
            [message] => Keys for idempotent requests can only be used with the same parameters they were first used with. Try using a key other than '1917-src_1BsteDHcJVmA1MkawgR0Ik36' if you meant to execute a different request.
        )

)

====End Log====
```


We can continue to work directly with the customer. Please let me know what other information I can get you to help speed things along.

**Comment by roykho** [comment] 2018-02-08 20:32
cc @thorsten-stripe

**Comment by roykho** [comment] 2018-02-08 20:42
@zhollenbeak are you using webhooks? Also is this happening on every one of the subscriptions order or just some? And lastly which specific emails are going out?

**Comment by thorsten-stripe** [comment] 2018-02-09 12:48
@roykho from what I can see on my end, this is an initial 3DS charge.
It looks like the webhook handler got there first, created the charge, and then the request is initiated again (from the subs handler?) with additional metadata params:

```
  "metadata": {
    "customer_name": "xxx",
    "customer_email": "xxx",
    "order_id": "1917",
    "payment_type": "recurring",
    "site_url": "xxx"
  },
```

`payment_type` and `site_url` being the parameters that are being added. That's why the "Keys for idempotent requests can only be used with the same parameters they were first used with. Try using a key other than '1917-xxx' if you meant to execute a different request." error is thrown.

So it sounds like the webhook handler is creating the charge differently than the redirect return handler

**Comment by zhollenbeak** [comment] 2018-02-09 21:17
Hi @roykho, Thanks for the response! I just checked the customer's site:
- no webhooks. 
- The only email I could get my hands on is a screen shot of the admin Failed Order notification https://cl.ly/pQ4W
- The stripe logs only show this one order which generated the idempotency error. More orders have processed yesterday and today without issue. 

I went ahead and copied all of the stripe logs related to the 1917 order transaction, hope that helps!

```02-07-2018 @ 09:11:39 - ====Start Log====
sources/src_1Bste5HcJVmA1MkaVU6b05m6
====End Log====


02-07-2018 @ 09:11:39 - ====Start Log====
customers/cus_CHSZV5XHjHGAiV/sources request: Array
(
    [source] => src_1Bste5HcJVmA1MkaVU6b05m6
)

====End Log====


02-07-2018 @ 09:11:41 - ====Start Log====
customers/cus_CHSZV5XHjHGAiV request: Array
(
    [default_source] => src_1Bste5HcJVmA1MkaVU6b05m6
)

====End Log====


02-07-2018 @ 09:11:41 - ====Start Log====
Info: Begin creating 3DS source...
====End Log====


02-07-2018 @ 09:11:41 - ====Start Log====
sources request: Array
(
    [amount] => 27000
    [currency] => usd
    [type] => three_d_secure
    [owner] => stdClass Object
        (
            [name] => Christine McComb
            [email] => christinemccomb@gmail.com
            [phone] => 317 727 8811
            [address] => Array
                (
                    [line1] => 12412 Burke Drive
                    [line2] => 
                    [state] => IN
                    [city] => Carmel
                    [postal_code] => 46032
                    [country] => US
                )

        )

    [three_d_secure] => Array
        (
            [card] => src_1Bste5HcJVmA1MkaVU6b05m6
        )

    [redirect] => Array
        (
            [return_url] => https://thelittlecatholicbox.com/checkout/order-received/1917?key=wc_order_5a7b091998cc6&utm_nooverride=1&order_id=1917
        )

)

====End Log====


02-07-2018 @ 09:11:42 - ====Start Log====
Info: Redirecting to 3DS...
====End Log====


02-07-2018 @ 09:11:57 - ====Start Log====
Info: (Redirect) Begin processing payment for order 1917 for the amount of 270.00
====End Log====


02-07-2018 @ 09:11:57 - ====Start Log====
sources/src_1BsteDHcJVmA1MkawgR0Ik36
====End Log====


02-07-2018 @ 09:11:57 - ====Start Log====
charges request: Array
(
    [currency] => usd
    [amount] => 27000
    [description] => The Little Catholic Box - Order 1917
    [statement_descriptor] => Little Catholic Box
    [capture] => true
    [expand[]] => balance_transaction
    [metadata] => Array
        (
            [customer_name] => Christine McComb
            [customer_email] => christinemccomb@gmail.com
            [order_id] => 1917
        )

    [customer] => cus_CHSZV5XHjHGAiV
    [source] => src_1BsteDHcJVmA1MkawgR0Ik36
)

====End Log====


02-07-2018 @ 09:11:58 - ====Start Log====
Info: (Webhook) Begin processing payment for order 1917 for the amount of 270.00
====End Log====


02-07-2018 @ 09:11:58 - ====Start Log====
charges request: Array
(
    [currency] => usd
    [amount] => 27000
    [description] => The Little Catholic Box - Order 1917
    [statement_descriptor] => Little Catholic Box
    [capture] => true
    [expand[]] => balance_transaction
    [metadata] => Array
        (
            [customer_name] => Christine McComb
            [customer_email] => christinemccomb@gmail.com
            [order_id] => 1917
            [payment_type] => recurring
            [site_url] => https://thelittlecatholicbox.com
        )

    [customer] => cus_CHSZV5XHjHGAiV
    [source] => src_1BsteDHcJVmA1MkawgR0Ik36
)

====End Log====


02-07-2018 @ 09:11:59 - ====Start Log====
Processing response: stdClass Object
(
    [id] => ch_1BsteTHcJVmA1Mkab3KQ6UwH
    [object] => charge
    [amount] => 27000
    [amount_refunded] => 0
    [application] => 
    [application_fee] => 
    [balance_transaction] => stdClass Object
        (
            [id] => txn_1BsteVHcJVmA1Mka2H8XTZgG
            [object] => balance_transaction
            [amount] => 27000
            [available_on] => 1518134400
            [created] => 1518012717
            [currency] => usd
            [description] => The Little Catholic Box - Order 1917
            [exchange_rate] => 
            [fee] => 813
            [fee_details] => Array
                (
                    [0] => stdClass Object
                        (
                            [amount] => 813
                            [application] => 
                            [currency] => usd
                            [description] => Stripe processing fees
                            [type] => stripe_fee
                        )

                )

            [net] => 26187
            [source] => ch_1BsteTHcJVmA1Mkab3KQ6UwH
            [status] => pending
            [type] => charge
        )

    [captured] => 1
    [created] => 1518012717
    [currency] => usd
    [customer] => cus_CHSZV5XHjHGAiV
    [description] => The Little Catholic Box - Order 1917
    [destination] => 
    [dispute] => 
    [failure_code] => 
    [failure_message] => 
    [fraud_details] => stdClass Object
        (
        )

    [invoice] => 
    [livemode] => 1
    [metadata] => stdClass Object
        (
            [customer_name] => Christine McComb
            [customer_email] => christinemccomb@gmail.com
            [order_id] => 1917
        )

    [on_behalf_of] => 
    [order] => 
    [outcome] => stdClass Object
        (
            [network_status] => approved_by_network
            [reason] => 
            [rule] => allow_if_3d_secure__enabled
            [seller_message] => Payment complete.
            [type] => authorized
        )

    [paid] => 1
    [receipt_email] => 
    [receipt_number] => 
    [refunded] => 
    [refunds] => stdClass Object
        (
            [object] => list
            [data] => Array
                (
                )

            [has_more] => 
            [total_count] => 0
            [url] => /v1/charges/ch_1BsteTHcJVmA1Mkab3KQ6UwH/refunds
        )

    [review] => 
    [shipping] => 
    [source] => stdClass Object
        (
            [id] => src_1BsteDHcJVmA1MkawgR0Ik36
            [object] => source
            [amount] => 27000
            [client_secret] => src_client_secret_CHSZ2IHSkZWf9ms2l3RUHZ9q
            [created] => 1518012719
            [currency] => usd
            [flow] => redirect
            [livemode] => 1
            [metadata] => stdClass Object
                (
                )

            [owner] => stdClass Object
                (
                    [address] => stdClass Object
                        (
                            [city] => Carmel
                            [country] => US
                            [line1] => 12412 Burke Drive
                            [line2] => 
                            [postal_code] => 46032
                            [state] => IN
                        )

                    [email] => christinemccomb@gmail.com
                    [name] => Christine McComb
                    [phone] => 317 727 8811
                    [verified_address] => 
                    [verified_email] => 
                    [verified_name] => 
                    [verified_phone] => 
                )

            [redirect] => stdClass Object
                (
                    [failure_reason] => 
                    [return_url] => https://thelittlecatholicbox.com/checkout/order-received/1917?key=wc_order_5a7b091998cc6&utm_nooverride=1&order_id=1917
                    [status] => succeeded
                    [url] => https://hooks.stripe.com/redirect/authenticate/src_1BsteDHcJVmA1MkawgR0Ik36?client_secret=src_client_secret_CHSZ2IHSkZWf9ms2l3RUHZ9q
                )

            [statement_descriptor] => 
            [status] => consumed
            [type] => three_d_secure
            [usage] => single_use
            [three_d_secure] => stdClass Object
                (
                    [card] => src_1Bste5HcJVmA1MkaVU6b05m6
                    [authenticated] => 
                    [customer] => 
                )

        )

    [source_transfer] => 
    [statement_descriptor] => Little Catholic Box
    [status] => succeeded
    [transfer_group] => 
)

====End Log====


02-07-2018 @ 09:12:00 - ====Start Log====
Info: (Webhook) Begin processing payment for order 1917 for the amount of 270.00
====End Log====


02-07-2018 @ 09:12:00 - ====Start Log====
charges request: Array
(
    [currency] => usd
    [amount] => 27000
    [description] => The Little Catholic Box - Order 1917
    [statement_descriptor] => Little Catholic Box
    [capture] => true
    [expand[]] => balance_transaction
    [metadata] => Array
        (
            [customer_name] => Christine McComb
            [customer_email] => christinemccomb@gmail.com
            [order_id] => 1917
            [payment_type] => recurring
            [site_url] => https://thelittlecatholicbox.com
        )

    [customer] => cus_CHSZV5XHjHGAiV
    [source] => src_1BsteDHcJVmA1MkawgR0Ik36
)

====End Log====


02-07-2018 @ 09:12:04 - ====Start Log====
Info: (Webhook) Begin processing payment for order 1917 for the amount of 270.00
====End Log====


02-07-2018 @ 09:12:04 - ====Start Log====
charges request: Array
(
    [currency] => usd
    [amount] => 27000
    [description] => The Little Catholic Box - Order 1917
    [statement_descriptor] => Little Catholic Box
    [capture] => true
    [expand[]] => balance_transaction
    [metadata] => Array
        (
            [customer_name] => Christine McComb
            [customer_email] => christinemccomb@gmail.com
            [order_id] => 1917
            [payment_type] => recurring
            [site_url] => https://thelittlecatholicbox.com
        )

    [customer] => cus_CHSZV5XHjHGAiV
    [source] => src_1BsteDHcJVmA1MkawgR0Ik36
)

====End Log====


02-07-2018 @ 09:12:08 - ====Start Log====
Info: (Webhook) Begin processing payment for order 1917 for the amount of 270.00
====End Log====


02-07-2018 @ 09:12:08 - ====Start Log====
charges request: Array
(
    [currency] => usd
    [amount] => 27000
    [description] => The Little Catholic Box - Order 1917
    [statement_descriptor] => Little Catholic Box
    [capture] => true
    [expand[]] => balance_transaction
    [metadata] => Array
        (
            [customer_name] => Christine McComb
            [customer_email] => christinemccomb@gmail.com
            [order_id] => 1917
            [payment_type] => recurring
            [site_url] => https://thelittlecatholicbox.com
        )

    [customer] => cus_CHSZV5XHjHGAiV
    [source] => src_1BsteDHcJVmA1MkawgR0Ik36
)

====End Log====


02-07-2018 @ 09:12:08 - ====Start Log====
Info: (Webhook) Begin processing payment for order 1917 for the amount of 270.00
====End Log====


02-07-2018 @ 09:12:08 - ====Start Log====
charges request: Array
(
    [currency] => usd
    [amount] => 27000
    [description] => The Little Catholic Box - Order 1917
    [statement_descriptor] => Little Catholic Box
    [capture] => true
    [expand[]] => balance_transaction
    [metadata] => Array
        (
            [customer_name] => Christine McComb
            [customer_email] => christinemccomb@gmail.com
            [order_id] => 1917
            [payment_type] => recurring
            [site_url] => https://thelittlecatholicbox.com
        )

    [customer] => cus_CHSZV5XHjHGAiV
    [source] => src_1BsteDHcJVmA1MkawgR0Ik36
)

====End Log====


02-07-2018 @ 09:12:09 - ====Start Log====
Error: stdClass Object
(
    [error] => stdClass Object
        (
            [type] => idempotency_error
            [message] => Keys for idempotent requests can only be used with the same parameters they were first used with. Try using a key other than '1917-src_1BsteDHcJVmA1MkawgR0Ik36' if you meant to execute a different request.
        )

)

====End Log====
```

**Comment by roykho** [comment] 2018-03-08 04:03
@NickGreen yes please give us exact steps to replicate.

**Comment by zhollenbeak** [comment] 2018-03-08 20:52
Hi! I'm tracking the cases reporting the 'idempotent' errors and found one of these was on an older version of stripe, another was indeed just a failed payment. The one I am currently researching was on Stripe 4.0.7 when the idempotent error occurred, however the strange thing is that the error was not captured in the stripe error logs. 
Here is the note we find on the order - https://cl.ly/q2vH
Here is the corresponding stripe error logs entry which does not capture the 'idempotent' error - https://cl.ly/q2Zi
I've confirmed there are no webhooks on this site. 
This may be immaterial, but the customer did state that they seem to have this problem with clients that use AMEX cards.

**Comment by NickGreen** [comment] 2018-03-10 00:53
@roykho It's really hard to lay out exact steps to replicate, since we are now seeing so many sites with the same issue, and all of the details are slightly different.

One common thread that we are seeing is that there will often be a payment failure in the notes first, then for each retry, there will be an idempotent failure. Often, the final payment will be noted to succeed, but the order is never switched to 'processing.'

Many of these tickets say that they've been sent to us from Woo Support, so I'm reluctant to ask them to open another ticket in the Woo system. However, would it be helpful to do so, so you could have access to their sites?

We are now getting about 2 new tickets with these errors daily.

**Comment by NickGreen** [comment] 2018-03-10 01:10
Another detail is that the subscription notes are showing all of these errors, but the Stripe logs are not.

**Comment by roykho** [comment] 2018-03-10 01:19
@NickGreen do you know if these "save cards" were from the legacy Stripe plugin? Were you able to replicate this yourself?

**Comment by NickGreen** [comment] 2018-03-10 01:32
Checking an example sub, the payment token starts with `src_`, so I think that means it's not from the legacy plugin. (the old one used `card_` I think)

We've not been able to replicate this error locally yet.

**Comment by NickGreen** [comment] 2018-03-10 01:38
Checking an example sub, the payment token starts with `src_`, so I think that means it's not from the legacy plugin. (the old one used `card_` I think)

We've not been able to replicate this error locally yet.

**Comment by iamgabrielma** [comment] 2018-03-11 09:54
Seems we're seeing the same issue in 1007481-zen , we have asked for staging site + credentials in order to be able to test this further. The user's cards all seem to get declined and they are having trouble updating the payment. 

Re-opening the issue for now. You had any chance to look into it @roykho  ?

**Comment by roykho** [comment] 2018-03-11 14:23
@iamgabrielma did you test this yourself? Were you able to replicate?

**Comment by iamgabrielma** [comment] 2018-03-13 11:18
> did you test this yourself? Were you able to replicate?

I wasn't able to replicate this for the moment.

From the customer, this seems only happening only with Subscriptions and Stripe. I have added credentials and a note to the orders with problems on 1007481-zen). There we can see how this is declined 7 times before it went through and once it goes through there's multiple charges (customer says), but Logs are empty at the moment at the staging site, so I have asked if they happen to have any other log on the live site that could help us narrow the issue with Stripe, or if there was an error message we can check into.

Also I'm unsure if the multiple declined attempts are related or not, as seems in the other tickets linked here there's no mention of that.

We have asked for exact steps to replicate this on staging and see if we can dig further. If you have any advice or idea on the best way to try to replicate this please let us know.

**Comment by roykho** [comment] 2018-03-13 20:39
@iamgabrielma can you please check if customer is using webhook?

**Comment by mdmoore** [comment] 2018-03-14 20:44
@roykho No webhooks are being used.  We have some more information from the user on how these cards are appearing in Stripe:

>Newer subscribers – have a card stored in sources only. Starts with src and has a status of chargeable

>One older subscribe has a card stored in the card section, status default. No card stored in sources

>Older subscriber has a card stored in the card section, status default . Card also stored in sources with status chargeable

>One very old subscriber, payment failed, he has card stored in both card and source

>One of the more recent failed payments has card stored in both – bank reason for decline is pickupcard

I'm not sure if that's helpful.  I haven't been able to reproduce and this a new one for me.

**Comment by roykho** [comment] 2018-03-14 20:51
@mdmoore - and they are getting charged twice per successful charge?

**Comment by mdmoore** [comment] 2018-03-14 20:58
Prospress reported multiple charges and transaction IDs, though I can't find those orders myself.  I'll find out.

**Comment by mdmoore** [comment] 2018-03-15 16:52
@roykho Apprently there was confusion and this user was never experiencing duplicate charges.  

>What we have is more related to increased card declines – such as when the same card has gone through previously bank report stating “wrong card number” etc, general declines after months of going through fine on same card – wrong details in source, card updates not updating. Also order status not updating correctly when payment fails (or not).

**Comment by roykho** [comment] 2018-03-16 17:21
Potential fix for this in 4.1 branch here https://github.com/woocommerce/woocommerce-gateway-stripe/tree/release/4.1

It fixes the idempotency issue causing exhausted retries.

**Comment by joelwills** [comment] 2018-03-16 17:22
Adding 1011362-zen as they have the `idempotency_error` too (but not double charges)

**Comment by roykho** [comment] 2018-06-06 20:40
@seanreloaded please open a new thread with reproducing steps and more detail per what customer stated as this thread gives no information on that.

**Closed by roykho** 2018-06-06 20:40 UTC
Labels: [Pri] High, [Type] Bug
