### ISSUE TITLE
New Checkout Experience (UPE) Orders stuck in Pending Payment when customer creates account during checkout.

### ISSUE THREAD

**Issue by avantegarde** [woocommerce/woocommerce-gateway-stripe#2559] opened 2023-02-28 16:23 UTC
**Describe the bug**
When using the New Checkout Experience (UPE) and guest checkout is not enabled, but account creation is allowed during checkout, orders will receive a status of `Pending Payment` in WooCommerce. The payment is, however, successfully processed in Stripe.

- The order notes only display the initial payment intent message but nothing further.
- When the `Allow customers to place orders without an account` checkbox is ticked, the issue is resolved.

**To Reproduce**
1. Enable the New Checkout Experience
2. Navigate to the **WooCommerce > Settings > Accounts & Privacy** page.
3. **Untick** the `Allow customers to place orders without an account` checkbox
4. **Tick** the `Allow customers to create an account during checkout` checkbox
5. Place an order on the website in an incognito window with a new email address that does not have an account on the site.
6. You will be taken to the order confirmation/thank you page
7. Check the order status on the **WooCommerce > Orders** page. It will have a status of `Pending Payment`
8. Check the payment in the Stripe dashboard. It will be successful.

**Expected behavior**
When placing an order with a new account and account creation enabled on checkout, the order should be processed correctly, order status set to `Processing`, and order notes to reflect the correct events from Stripe.

**Screenshots**
Using these account settings, orders are set to `Pending Payment` but processed correctly by Stripe.

<img width="1271" alt="Markup 2023-02-28 at 10 49 43" src="https://user-images.githubusercontent.com/3516737/221911839-bc5d8b7b-4ac8-4bc3-8160-cb5c4547feb9.png">

Order stuck on `Pending Payment` with no order notes indicating the transaction was successful.

<img width="1795" alt="Markup 2023-02-28 at 11 00 11" src="https://user-images.githubusercontent.com/3516737/221912235-de2b3eb2-79a9-4725-b712-8cda1f3c007c.png">

Stripe events showing the order was successful.

<img width="1493" alt="Markup 2023-02-28 at 11 00 56" src="https://user-images.githubusercontent.com/3516737/221912325-79ef10b8-d3bb-4e65-b5d0-1a64fe2627f9.png">

When the `Allow customers to place orders without an account` checkbox is ticked, the issue is resolved and orders process as expected.

<img width="1253" alt="Markup 2023-02-28 at 10 47 32" src="https://user-images.githubusercontent.com/3516737/221911720-08f0496d-e3f3-4451-8904-5bd1e7c680d9.png">

**Environment (please complete the following information):**
 - WordPress Version 6.1.1
 - WooCommerce Version 7.4.0
 - Stripe Plugin Version 7.1.0
 - Browser Chrome 110.0.5481.177
 - Only WooCommerce and Stripe active with the Storefront Theme.

**Additional context**
5985968-zen

**Current workarounds**
- enable the `Allow customers to place orders without an account` checkbox.
- Disable the New Checkout Experience.

**Comment by avantegarde** [comment] 2023-03-03 15:03
**Update:** I'm also seeing the same behavior when UPE is enabled and the following account settings are enabled:

<img width="1170" alt="Screen Shot 2023-03-03 at 9 52 58 AM" src="https://user-images.githubusercontent.com/3516737/222751829-3869bded-b78e-44a8-960f-5e200aac32f9.png">

Orders are processed normally if you checkout as a guest. But if you tick the `Create an account` checkbox and enter a password. The order is set to `Pending Payment` in WooCommerce but successful in Stripe. Order notes only show the payment intent creation.

It's also worth mentioning that in all of the test where the order is set to `Pending Payment` the **Transaction ID** is missing in the billing details for the order in WooCommerce.

<img width="486" alt="Markup 2023-03-03 at 10 02 35" src="https://user-images.githubusercontent.com/3516737/222754127-440e75bc-19fe-4013-8aa7-33c199d24396.png">

It seems there is an issue with UPE and account creation within WooCommerce somewhere.

5980218-zen

**Comment by avantegarde** [comment] 2023-03-03 15:29
**Update:** I spent a significatn amount of time testing this out and was able to narrow it down to the account creation during checkout and UPE being enabled.

- If account creation and UPE is enabled and the customer decides to create an account during checkout, the order is set to `Pending Payment` but is successful in Stripe.

- If either UPE or account creation during checkout is disabled, the orders and transactions are processed as expected.

**Comment by avantegarde** [comment] 2023-03-03 19:00
5960697-zen

**Comment by James91** [comment] 2023-03-13 13:12
+1

**Comment by avantegarde** [comment] 2023-03-15 20:07
6038236-zen

**Comment by wyter** [comment] 2023-03-20 12:46
6028900-zen

**Comment by rossviviano** [comment] 2023-03-21 16:07
6059602-zen

**Comment by wyter** [comment] 2023-03-22 07:29
6059251-zen

**Comment by kubiqsk** [comment] 2023-04-03 14:51
exactly my problem in the last weeks - please fix this asap, because customers are writing emails, that they created order and they can not download their content and I have to go and complete each order manually and write them sorry responses

**Comment by xue28** [comment] 2023-04-03 15:04
6169039-zen

**Comment by kubiqsk** [comment] 2023-04-03 15:10
Maybe this will help someone temporary - it will send you an email about new pending order with links where you can directly check the status on Stripe and also link to Woo directly where you can quickly change status manually

```php
add_action( 'woocommerce_new_order', function( $order_id, $order ){
	if( $order->get_status() === 'pending' ){
		$subject = 'New Payment Pending Order: #' . $order_id;
		$message = 'A new payment pending order has been received. Order ID: ' . $order_id;
		$message .= "\n";
		$message .= 'Check the payment status on Stripe here:';
		$message .= "\n";
		$message .= 'https://dashboard.stripe.com/search?query=' . $order_id;
		$message .= "\n";
		$message .= 'and if it is Succeeded, then go and change the order status in WooCommerce manually here:';
		$message .= "\n";
		$message .= admin_url('/post.php?post=' . $order_id . '&action=edit');
		wp_mail( get_option('admin_email'), $subject, $message );
	}
}, 10, 2 );
```

**Comment by WillBrubaker** [comment] 2023-04-04 06:14
6171446-zen

ETA some search terms:

Could not find order via charge ID:

Charge ID is not added to the order notes

log lacks ""Begin processing UPE redirect payment" message

**Comment by stoltzrx** [comment] 2023-04-04 08:23
6171998-zen

**Comment by coolsatinder** [comment] 2023-04-04 15:26
+1 facing same issue

**Comment by wyter** [comment] 2023-04-05 05:25
6084789-zen

**Comment by redbasel** [comment] 2023-04-05 12:24
same issue

**Comment by theabhig** [comment] 2023-04-09 04:58
6083010-zen

**Comment by avantegarde** [comment] 2023-04-13 17:50
6050552-zen

**Comment by wyter** [comment] 2023-04-17 05:59
6204089-zen

**Comment by rvmclaughlin** [comment] 2023-04-26 14:13
Same issue for me too.

**Comment by thenbrent** [comment] 2023-05-04 05:40
I'm labeling this bug as critical given it can result in paid orders going unfulfilled. With that status, it can be picked up in the first set of Stripe issues handled by the new team.

Some further discussion for A12s on this issue here: p1678273828864889-slack-C7U3Y3VMY

**Comment by orhanfernandes** [comment] 2023-05-11 06:21
6261549-zen

**Comment by Maxtab** [comment] 2023-05-11 16:23
I'm having exactly the same problem on my up-to-date Woocommerce (plugin also up-to-date). The logs were not very interesting about this problem, but indeed, I note that only my orders whose account creation is made during the purchase process are concerned, orders as invite users or on already existing accounts are not impacted.

**Comment by maxlaf** [comment] 2023-05-11 18:54
6240893-zen

**Comment by Brianmitchtay** [comment] 2023-05-11 18:59
6273458-zen

**Comment by sukafia** [comment] 2023-05-15 08:19
6291072-zen

**Comment by jacoswan** [comment] 2023-05-15 09:53
6066506-zen
6291268-zen

**Comment by wyter** [comment] 2023-05-17 07:46
6271204-zen

**Comment by rbgly** [comment] 2023-05-17 08:17
6295636-zen

**Comment by johndcoy** [comment] 2023-05-24 17:08
6215734-zen

**Comment by theabhig** [comment] 2023-05-28 07:14
6291385-zen

**Comment by theabhig** [comment] 2023-05-30 06:56
6310411-zen

**Comment by jaxr** [comment] 2023-05-30 19:38
6345921-zen

**Comment by dreamtooloud** [comment] 2023-06-06 20:18
6335201-zen

**Comment by dreamtooloud** [comment] 2023-06-08 17:47
6379246- zen 

This user also has the following error on their site: 

![Screenshot 2023-06-08 at 3 03 12 PM](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/37193213/ef4081cb-ba05-49a4-b8db-a9ab74b7eef0)

**Comment by redbasel** [comment] 2023-06-08 18:02
Yes we still have this error. Thank you

**Comment by dreamtooloud** [comment] 2023-06-08 21:06
6383332-zen ( ticket: 385819-zen)

Still confirming, but it has all the same symptoms of 6379246-zen and that same error message.

**Comment by dreamtooloud** [comment] 2023-06-09 14:58
6378419-zen (potentially another report here. We've deactivated UPE and are waiting to see if that clears the issue. Otherwise, this user's situation fits the symptoms outlined in this issue).

**Comment by rbgly** [comment] 2023-06-13 12:19
6402813-zen

**Comment by Brianmitchtay** [comment] 2023-06-13 20:24
6359090-zen looks to be experiencing this as well (Along with some other symptoms that may be related to improperly configured webhooks, or could be another bug if they persist with UPE disabled and webhooks properly in place)

**Comment by jivaneo** [comment] 2023-06-13 20:43
Same here, PENDING when a new account is created during checkout, using Stripe Earlybird.
This is happening for quite a long time...
Any fix expected?

**Comment by thenbrent** [comment] 2023-06-15 01:29
>  Any fix expected?

A fix is in progress now in #2619.

**Closed as completed** 2023-06-15 01:57 UTC
Labels: priority: critical, type: bug

**Comment by wyter** [comment] 2023-06-20 05:18
For fix communication purposes, 6332007-zen

**Comment by wyter** [comment] 2023-07-03 10:24
6491000-zen

**Comment by kubiqsk** [comment] 2023-07-03 10:35
Why is this closed? Yesterday it happened again on my shop and I have everything up to date...

**Comment by stoltzrx** [comment] 2023-07-04 10:07
6487333-zen

**Comment by thenbrent** [comment] 2023-07-05 04:52
> Why is this closed? Yesterday it happened again on my shop and I have everything up to date...

@kubiqsk it has been closed because a fix has been merged in #2619. That fix hasn't shipped in the released version yet which is why it's still happening (a recent security incident slowed down the fixes release), but it will be shipped soon to address this issue.

**Comment by theabhig** [comment] 2023-07-21 07:46
Just adding that this may have also happened in 6550629-zen. I have let the merchant know a fix is coming soon although I'm not sure which version of Stripe they were using so am waiting on that info.

**Comment by wyter** [comment] 2023-07-23 05:48
6506726-zen

**Comment by wyter** [comment] 2023-07-26 12:45
6553941-zen

**Comment by oxwebdevelopment** [comment] 2023-07-28 00:54
Issue persists

**Comment by mskapusuz** [comment] 2023-07-28 03:52
Hello there,

We have the same issue on v7.4.1 

I diagnosed the issue and verified it comes from `wc_stripe_process_redirect_order_nonce` nonce verification check and thus `WC_Stripe_UPE_Payment_Gateway::maybe_process_upe_redirect` bails, [ref](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/c666a7af84a0e751a7add1533450a59aa906d2ca/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L849)

The nonce string is received by the `wp_verify_nonce` well however it fails.

As I see, you released the [PR](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2619). but unfortunately, I can say, the issue persists on v7.4.1

Note: The issue happens only in the guest mode (the checkout has account creation)

If you need more details, I can give them to you.

For now, we disabled UPE.

Thanks in advance!
Mustafa

**Comment by dreamtooloud** [comment] 2023-08-03 17:31
Might have three more instances here (2 out of 3 are confirmed to be on v. 7.4.2): 

6604617-zen 
6570421-zen  (confirmed, same configuration UPE + Guest Checkout)
6594196-zen

Finalizing some information gathering and will update here if I can confirm its the same as this closed issue.

**Comment by theabhig** [comment] 2023-08-08 08:10
Possibly also happened in 6585471-zen

**Comment by wyter** [comment] 2023-08-21 06:47
Still happened to 6416802-zen while using Stripe version 7.5.0.

**Comment by nicklssb** [comment] 2023-08-29 18:50
This is happening live on one of the websites I manage currently.

**Comment by m0untaingoat** [comment] 2023-12-15 14:57
possibly still happening in 7424967-zen

**Comment by ldr2273** [comment] 2024-03-06 01:57
Seems to be occurring in 7815078-zen. @mattallan - any way we could re-open this for review as some merchants still seem to be affected? Thanks!

**Comment by solstudioim** [comment] 2024-03-15 08:05
Looks like 7868307-zd-a8c might be affected by this bug, no it's working for them with the New checkout experience and `allow customers to create an account during checkout` disabled

**Comment by RyanB28** [comment] 2024-05-31 11:25
Still having this issue on version 8.3.1.

**Comment by Matt-Welland** [comment] 2024-05-31 13:48
Also been made aware of this issue.

**Comment by fmasson-arkod** [comment] 2024-06-27 09:19
Hello, still got the issue as well. Same as described, using Stripe 8.4 , UPE Disabled. Order stays on pending after success payement

**Comment by SteveJonk** [comment] 2024-06-29 10:06
I have the same as @fmasson-arkod , it started happening on 8.4 for me :( .
Disabled upe for now, which works, but a fix in the near future would be nice.

**Comment by thomasjvu** [comment] 2024-07-16 21:03
8468769-zen

**Comment by fmasson-arkod** [comment] 2024-08-14 18:22
Hello, the issue still persist for me, did anyone manage to find a workaround ?

**Comment by aditi-icubes** [comment] 2025-09-01 12:36
This issue is still occurring for me. I’m using the WooCommerce Stripe Gateway plugin version 9.5.3. Has anyone found a solution to fix this?
