### ISSUE TITLE
SCA: "Save payment information to my account for future purchases" should work with SCA payments

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1440] opened 2021-01-06 01:46 UTC
Steps to repro
1. As customer, purchase subscription
2. Later, check out with non-subscription product
3. Use new card 4000002500003155
4. Check ‘Save payment information to my account for future purchases.’
5. As customer, make the new card the default card and say “Yes” when it asks you if you want to use that card for all subscriptions
6. As admin, renew a subscription. See that it uses the new card. And that it fails due to authentication_required

**Comment by asumaran** [comment] 2021-04-13 18:24
@v18 to be clear the subscription has to be created using the [woocommerce-subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/) plugin right?

**Comment by asumaran** [comment] 2021-04-13 21:18
@v18 First of all, I'm testing with the `trunk` branch.

Can you elaborate on how to renew a subscription? I'm not sure I'm doing the exact steps to reproduce the issue. I'm using the following option to renew a subscription:

<img src="https://user-images.githubusercontent.com/1025173/114621673-99794b00-9c72-11eb-9adc-b8499cde497a.png" width="327" >

I can see the subscription is renewed with **no errors** and the card used is the non default card (regular card). Even though the 3DS card is set as default. I'll look if this is intended behavior or not.

**Comment by v18** [comment] 2021-04-14 08:41
Thanks @asumaran! About this:

> I can see the subscription is renewed with no errors and the card used is the non default card (regular card). Even though the 3DS card is set as default. I'll look if this is intended behavior or not. 

Were you able to see this notice when setting the card as the default:

<img width="851" alt="yes-on-blue-alert" src="https://user-images.githubusercontent.com/11487924/114677655-7c617c80-9d45-11eb-80f4-6eba0f14a02f.png">

One way to check which card is the default is by going to My Account > Subscriptions as a customer, you'll see this:

<img width="631" alt="card-for-subscription" src="https://user-images.githubusercontent.com/11487924/114677389-39070e00-9d45-11eb-933f-c757a69070a1.png">

---

As for repro steps for the issue, I'm still able to repro on `trunk` by following these steps:

1. Check out with subscription product. Use test card `4242424242424242`.
2. Check out with non-subscription product, use new test card `4000002500003155` and check 'Save payment information to my account for future purchases.'
3. As customer go to My Account > Payment methods, at `my-account/payment-methods/`:
4. Click "Make default" on the 3155 card:
<img width="639" alt="make-default" src="https://user-images.githubusercontent.com/11487924/114677641-78355f00-9d45-11eb-9583-956e37daee3d.png">
5. Click on 'Yes' on the blue alert:
<img width="851" alt="yes-on-blue-alert" src="https://user-images.githubusercontent.com/11487924/114677655-7c617c80-9d45-11eb-80f4-6eba0f14a02f.png">
6. See that the right credit card is being used for the subscription by going to My Account > Subscriptions at `/my-account/subscriptions/`:
<img width="631" alt="card-for-subscription" src="https://user-images.githubusercontent.com/11487924/114677389-39070e00-9d45-11eb-933f-c757a69070a1.png">
7. As store owner, go to the 'Edit Subscription' page for the subscription purchased in step 1. Use 'Process renewal' from the drop-down and click the 'Update' button to process the renewal:
<img width="313" alt="process-renewal" src="https://user-images.githubusercontent.com/11487924/114677863-a9ae2a80-9d45-11eb-81ae-6ec475bffc78.png">
8. See failed order at the bottom of 'Edit Subscription' page:
9. On the 'Edit Order' page for the failed order, click on the Stripe charge ID to be taken to the Stripe charge. See the payment method is the `3155`  card and the payment was declined with the code `authentication_required`:
<img width="688" alt="stripe-error" src="https://user-images.githubusercontent.com/11487924/114678076-db26f600-9d45-11eb-8200-e7bb97bba172.png">

I also tested these instructions with PR #1507. I see some flaky behaviour in PR 1507:

✅ **Behaviour 1 - all good, and this bug is fixed**
1. Check out with subscription product. Use test card `4242424242424242`.
2. Check out with non-subscription product, use new test card `4000002500003155` and check 'Save payment information to my account for future purchases.'
3. As customer go to My Account > Payment methods, at `my-account/payment-methods/`
4. Click "Make default" on the 3155 card
5. Click on 'Yes' on the blue alert
6. See that the right credit card is being used for the subscription by going to My Account > Subscriptions at `/my-account/subscriptions/`
7. As store owner, go to the 'Edit Subscription' page for the subscription purchased in step 1. Use 'Process renewal' from the drop-down and click the 'Update' button to process the renewal
8. See that the payment went through successfully, and it used the correct card `3155`.


🚫 **Behaviour 2 - bug**
1. Check out with subscription product. Use test card `4242424242424242`.
2. Check out with non-subscription product, use new test card `4000002500003155` and check 'Save payment information to my account for future purchases.'
3. As customer go to My Account > Payment methods, at `my-account/payment-methods/`
4. Click "Make default" on the 3155 card
5. Click on 'Yes' on the blue alert
6. See that the right credit card is being used for the subscription by going to My Account > Subscriptions at `/my-account/subscriptions/`
7. As store owner, go to the 'Edit Subscription' page for the subscription purchased in step 1. Use 'Process renewal' from the drop-down and click the 'Update' button to process the renewal
8. See that the payment went through successfully, and it used the old card `4242` instead of the right card `3155`. Here's what it looks like on the Subscriptions page:
<img width="496" alt="subscriptions-after-renewal-went-through" src="https://user-images.githubusercontent.com/11487924/114679781-72d91400-9d47-11eb-925b-0818d06e5219.png">
And on Stripe:
<img width="604" alt="stripe-using-4242" src="https://user-images.githubusercontent.com/11487924/114679883-8d12f200-9d47-11eb-8f46-4f1b66039bd6.png">

It might be that this behaviour also exists on `trunk` - I haven't been able to repro in about 5 tries. But it might still exist on `trunk` since the buggy behaviour I observed in # 2 above doesn't always happen on `fix/3d-secure-card-saved-fail` either.

**Comment by asumaran** [comment] 2021-04-14 20:36
@v18 thanks for the detailed response. I'll try to reproduce the issue again.

**Comment by asumaran** [comment] 2021-04-15 00:26
@v18 I've tested both cases `#1` and `#2` on my branch `fix/3d-secure-card-saved-fail` and the renewal is successfully finished. I can confirm on Stripe it used the default payment method (3DS card). I'll do another pass and will try to confirm this has been fixed in `fix/3d-secure-card-saved-fail`

**Comment by v18** [comment] 2021-04-15 00:39
@asumaran - sounds good! Let me know, and I'll retest to see if I can still repro the original problem.

**Comment by asumaran** [comment] 2021-04-15 01:07
@v18 I double checked and I can see the problem now. When running "Process renewal" the card we use is not the default one. Although the renewal seems to be done successfully, we should be the default card to process the payment.

I can see on the logs on Stripe we are using the original source instead of the default one. I'll work on a fix!

**Comment by asumaran** [comment] 2021-04-15 01:48
@v18 I ran the steps again on my branch and can confirm the payment is done successfully with the 3DS card when is set as default payment method.

--- 

#### Sources:

`3155`: `src_1IgK2rJ5cIRIG92xbNzf8IS0`
`4242`: `src_1IgK1IJ5cIRIG92xhMNZiMGc`

#### Payments:

subscription product:
  Payment Intent: `pi_1IgK1OJ5cIRIG92xvPAV9NHi`
  Source: `src_1IgK1IJ5cIRIG92xhMNZiMGc` (`4242`)

non subscription product:
  Payment Intent: `pi_1IgK2xJ5cIRIG92x0XDdJI4V`
  Source: `src_1IgK2rJ5cIRIG92xbNzf8IS0` (`3155`)

Default payment method is `4242`

<img width="785" alt="Screen Shot 2021-04-14 at 8 34 58 PM" src="https://user-images.githubusercontent.com/1025173/114801219-e3405f00-9d60-11eb-8d7e-f0745555c4e2.png">

Make `3155` the default one:

<img width="622" alt="Screen Shot 2021-04-14 at 8 36 05 PM" src="https://user-images.githubusercontent.com/1025173/114801290-0b2fc280-9d61-11eb-927f-9d29a7144369.png">

Click "Yes" on dialog. Payment for subscription changed from `4242` to `3155`

<img width="290" alt="Screen Shot 2021-04-14 at 8 40 51 PM" src="https://user-images.githubusercontent.com/1025173/114801642-b5a7e580-9d61-11eb-993e-9033d48a7aca.png">

Running "Process renewal" we can confirm the payment was done with the (new) default payment method (`3155`)

<img width="1167" alt="Screen Shot 2021-04-14 at 8 42 57 PM" src="https://user-images.githubusercontent.com/1025173/114801778-00c1f880-9d62-11eb-8c2c-fdda33c4ddb4.png">

<img width="1001" alt="Screen Shot 2021-04-14 at 8 44 02 PM" src="https://user-images.githubusercontent.com/1025173/114801847-28b15c00-9d62-11eb-8b77-475b5d172e73.png">

**Comment by asumaran** [comment] 2021-04-15 01:53
@v18 #1507 is ready to merge and it seems it will also fix this issue. Do you want to double check yourself before I merge the PR and close this issue?

**Comment by v18** [comment] 2021-04-15 05:41
@asumaran thanks for double-checking. I'm no longer able to reproduce the bug mentioned above. I found a different bug in #1507 & reported it on the PR.

We can close this issue when PR 1507 merged 🎉

**Closed** 2021-04-15 21:44 UTC
Labels: component: SCA, good first issue, priority: high
