### ISSUE TITLE
Cart Contents lost upon login at checkout

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce-gateway-stripe#3226] opened 2024-06-26 17:58 UTC
**Describe the bug**
It appears [this same bug](https://github.com/Automattic/woocommerce-payments/issues/7992) exists in WooCommerce Stripe. When account settings require an account to checkout, the cart contents are cleared when logging in. This was fixed in WooPayments with [this fix](https://github.com/Automattic/woocommerce-payments/pull/8084).

**To Reproduce**
1. Configure WooCommerce account settings to require an account and do not allow account creation at checkout
2. Add a product to the cart
3. Proceed to checkout and log in
4. The cart is empty

**Expected behavior**
Cart contents should persist when logging in at checkout

**Screenshots**
**Account Settings**
![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/3473953/203cd736-facb-480d-a0f0-9c0738403422)

**Environment (please complete the following information):**
 - WordPress Version - 6.6.5
 - WooCommerce Version - 9.0.2
 - Stripe Plugin Version - 8.4.0
 - Browser [e.g. chrome, safari] and Version - Chrome Version 126.0.6478.115 (Official Build) (x86_64)
 - Any other plugins installed
Jetpack
 

**Additional context**
p1719281718889519-slack-C7U3Y3VMY

**Comment by annemirasol** [comment] 2024-09-25 19:27
Unable to reproduce this with the latest versions.

```
Stripe 8.7.0
WooCommerce 9.3.2
WordPress 6.6.2
```

**Comment by annemirasol** [comment] 2024-12-19 21:34
Closing, as I am unable to reproduce. Stripe 9.0.0 and WC 9.5.1

Things I have tried:
- with WooPayments (8.6.1) and Stripe enabled
- with only Stripe enabled
- with and without code snippet described in https://github.com/Automattic/woocommerce-payments/issues/7992
- with and without Jetpack
- on local container setup and Jurassic Ninja

Please re-open if issue persists.

**Closed as completed by annemirasol** 2024-12-19 21:34 UTC
Labels: type: bug, priority: medium, needs repro
