### ISSUE TITLE
[BNPL] Klarna / Affirm - No error message is displayed on the block checkout when the transaction is denied

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#3060] opened 2024-04-10 00:43 UTC
**Describe the bug**

When the transaction is denied by Klarna, the shopper is redirected to the checkout page but no error message is displayed.

This could be happening for Afterpay and Affirm too.

**To Reproduce**
1. Check out the branch `add/klarna-payment-method`
2. Make sure the currency store is USD, the Legacy checkout experience is disabled, and that Klarna is enabled
3. Ensure a page using the block checkout is selected as the default checkout page in WooCommerce, under Page setup > Checkout page, at `/wp-admin/admin.php?page=wc-settings&tab=advanced`
4. As a shopper, add a product to the cart, and go to the checkout page
6. In Klarna, log in with the following email address or phone number to get your transaction denied `	customer+denied@email.us` or `+13106354386`
7. Select Pay now and continue. You'll get a "Sorry, we couldn't approve this purchase" error
8. Select Pay in 4 and continue. You'll get another error message
9. Click on "Return to checkout"
10. Notice that you go back to the store, but no error message is displayed. On the Stripe logs, you'll see the following entries
```
Error when processing payment: Customer was declined by Klarna
Error: We're not able to process this payment. Please try again later.
```

**Expected behavior**
The shopper must have a user-friendly message when returning to the checkout page.

**Comment by wjrosa** [comment] 2024-04-25 20:58
The same issue happens with Affirm. See [this comment](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3083#issuecomment-2071553976). PR integrating Affirm [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3083).

**Comment by wjrosa** [comment] 2024-05-02 20:44
This seems to be a regression on https://github.com/woocommerce/woocommerce/issues/42787#issuecomment-2091514402 (see my comment).

This was first reported in https://github.com/Automattic/woocommerce-payments/issues/7792 for Giropay (moved [here](https://github.com/woocommerce/woocommerce-blocks/issues/12123), then [here](https://github.com/woocommerce/woocommerce/issues/42787)). Supposed fixed [here](https://github.com/woocommerce/woocommerce/pull/43753).

I pinged the Rubik team there, so I will be closing this since it is not specific to BNPL.

**Closed as completed by wjrosa** 2024-05-02 20:44 UTC
