### ISSUE TITLE
Layout issue with "Enter account keys (advanced)" dialog box

### ISSUE THREAD

**Issue by siliconforks** [woocommerce/woocommerce-gateway-stripe#2510] opened 2022-12-24 22:43 UTC
**Describe the bug**
In the dialog box that pops up when you click the "Enter account keys (advanced)" button, some of the content is cut off.

**To Reproduce**
1. Install WooCommerce and the WooCommerce Stripe Gateway plugin on a new site.
2. In the admin section, click "Plugins".
3. Under "WooCommerce Stripe Gateway", click "Settings".
4. Click "Enter account keys (advanced)".
5. A dialog box pops up.  There is a message near the top (highlighted in blue) which is getting cut off.

**Expected behavior**
It should be possible to read the text in the blue box.

**Screenshots**
![stripe](https://user-images.githubusercontent.com/1156399/209452520-a88b850c-c736-4139-a740-de9ab31caa0a.png)

**Environment (please complete the following information):**
 - WordPress Version: 6.1.1
 - WooCommerce Version: 7.2.2
 - Stripe Plugin Version: 7.0.1
 - Browser [e.g. chrome, safari] and Version: Firefox 108.0.1 (64-bit)
 - Any other plugins installed: no

**Additional context**
Note that in the screenshot above, there's no scroll bar anywhere or any way of scrolling up to read the content in the blue box that is getting cut off.

**Comment by dougaitken** [comment] 2023-01-23 10:27
Hey @siliconforks 

Thanks for opening this bug report, I can **confirm** the same on a brand new site in Safari.

The scroll bar isn't allowing this `wcstripe-inline-notice components-notice is-info` div to be shown. This is the same when opening the same modal later when keys are already saved.

The text is `To enable the live mode, get the account keys from your [Stripe Account](https://dashboard.stripe.com/apikeys).`. Toggling to Test Mode changes the text to `To enable the test mode, get the test account keys from your [Stripe Account](https://dashboard.stripe.com/test/apikeys).`

**Comment by reykjalin** [comment] 2023-02-17 05:04
Closing as a duplicate of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2470

**Closed as completed by reykjalin** 2023-02-17 05:04 UTC
Labels: priority: low, type: bug, needs design, type: ux debt, component: settings

**Comment by dougaitken** [comment] 2023-02-20 11:36
Fixed in #2555
