### ISSUE TITLE
Woocommerce Single product Detail page Apple pay button issue

### ISSUE THREAD

**Issue by officialsabbir** [woocommerce/woocommerce-gateway-stripe#352] opened 2017-08-28 05:24 UTC
On site website woocommerce product detail page, Stripe for Woocommcerce plugin was used. If you use Safari device to visit any product detail page, you can see Apple Pay button. However, it will stay on "Processing" in the first load. It works fine only if the page is refreshed. The problem will happen again if the browser cache is cleared.

What's the issue?

**Comment by mattyza** [comment] 2017-08-28 07:51
Hi @officialsabbir.

Is there a particular version of Safari you've seen this happen on? Also, is this Safari Desktop or Safari on iOS?

Thanks in advance. :)

**Comment by officialsabbir** [comment] 2017-08-28 08:50
I used ipad and iphone the same issue & the latest version.
I tested it in mobile devices. You can do the same.
I cleared safari cache. It will then wait forever

**Comment by asatnikscales** [comment] 2017-09-28 18:08
I'm seeing this same behavior with Safari on iOS.  First time visiting a single product page, tap on Buy with Apple Pay, Apple Pay opens, 'processing' spins for a while then the Apple Pay screen disappears.

If I reload the page it works fine.  If I clear the cache and visit the single product page again I see the same issue.

iPhone 7 Plus
Safari on iOS 11.0.1 (15A402)

This has been happening since the plugin was first released with Apple Pay support, I just didn't realize how to reproduce it.

**Comment by officialsabbir** [comment] 2017-09-28 18:51
thanks for your reply

safari latest version.. tested both phone & desktop.

**Comment by roykho** [comment] 2017-09-29 03:40
This has identified as a nonce check issue. Looking into it.

**Comment by roykho** [comment] 2017-10-04 15:50
Fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0

**Closed by roykho** 2017-10-04 15:50 UTC
Labels: [Pri] Low, [Type] Bug

**Comment by AJerm** [comment] 2017-11-06 20:15
I've spent so long trying to debug this issue before finding this thread. I've hidden the button on product pages with CSS until a fix is pushed out. Looking forward to an update soon :)

**Comment by CrowFox** [comment] 2018-07-05 16:38
Any update on this issue?   I am experiencing the exact same issue on a fresh install.   For now have disabled Apple Pay on Product pages - works fine on Cart and Checkout pages...
