### ISSUE TITLE
refunded items + uncaptured charges

### ISSUE THREAD

**Issue by doriansavage** [woocommerce/woocommerce-gateway-stripe#357] opened 2017-09-14 14:18 UTC
#### What I expected
The plugin is set with auth and charge later.

I order 2 items then the status is pending.
I go to the order and make an item as refunded (refunds auto via stripe don't work because auth late charges can't be partially released so I must use mannual refunds)
The total of the order is recalculated without that refunded product.
When I change "pending" to "processing" : only the new recalculated total cart is beeing charged

#### What happened instead
The full amount of the initial total order is beeing charged

------------------------------------

When in place of manually refund the item, but DELETE it from the order, then change status to proceed,  then the new order total is recalculated BUT this time, only the one item remaining is beeing charged from stripe, and the reste refunded...

so I don't understand why by deleting one item from an order, then the correct reduced amount is beeing charged from the UNCAPTURED charge and not when I mannualy refund one item...

Any ideas ? thx !

**Comment by roykho** [comment] 2017-09-14 15:42
Something is not right because you said the order status is "pending". If you set the settings to authorization only, the order status should not be in "pending" after the transaction but "on-hold". Please re-check.

**Comment by doriansavage** [comment] 2017-09-14 15:49
Yes you are right my english is not very good. It's "on-hold"

**Comment by roykho** [comment] 2017-09-14 15:52
So are you saying the issue is that an authorized only charge cannot be partially refunded?

**Comment by doriansavage** [comment] 2017-09-14 16:11
no. I know that an anthorized only charge cannot be partially refunded. It's even the fact on the stripe dashboard.

My issue is that when an order contains 2 items and so the status is "on-hold" and I see inside stripe dashboard 70$ UNCAPTURED

Case 1 : I delete one item from the order and change the status to "processing".
From Stripe dashboard I see :
€41.50 captured
€70 payment authorized

Case 2 : I refund from the wp order page the same item. so the new order total become 41.5€. Then I change the status to "processing"
From Stripe dashboard I see : 
€70 captured
€70 payment authorized

**Comment by doriansavage** [comment] 2017-09-14 16:12
I was expecting case 2 would react the same as Case 1 ?

**Comment by roykho** [comment] 2017-09-14 16:42
Ok so when you change the order like that which affects the total ( using re-calc ), it does not reflect on Stripe. I am not sure if they have a way to change the authorized amount via the API. So a work around for you is just to capture the original amount and then refund partially to reflect your order item changes.

**Comment by doriansavage** [comment] 2017-09-15 07:06
Hey ! I think I don't have to change the authorized amount ! The authorized amount stay $70.
The issue is that :
 - when I delete one item, and then put the order in-progress only new re-calc amount is charger ($35) and the rest refunded
- when I mannualy refund (without stripe) one item from the wordpress order details page (and so the new total order is re-calc) and put the order in-progress, then the full amount ($70) is charger from the card... then I would need to refund that item from Stripe dashboard... 

Do you understand the issue ?
Delete item = ok => only nex re-calc order total is charged from the auth
Refund item = no ok => aven after re-calc, the full amount is charged

**Comment by doriansavage** [comment] 2017-09-15 07:31
It seems like you don't send the correct total order amount to stripe when we use manual wordpress refunds...

http://prntscr.com/gldxz7
http://prntscr.com/gldy9q

**Comment by doriansavage** [comment] 2017-09-15 08:35
I added/edited this to the capture_payment function and its working like I want now : 

`$refund_amount = $order->get_total_refunded();
					if($refund_amount > 0){
						$order_total = ($order->get_total() * 100)-($refund_amount * 100);
					} else {
						$order_total = $order->get_total() * 100;
					}

					$result = WC_Stripe_API::request( array(
						'amount'   => $order_total,
						'expand[]' => 'balance_transaction',
					), 'charges/' . $charge . '/capture' );`

**Comment by roykho** [comment] 2017-09-15 13:47
Ok so from what I am understanding what the issue is, when you use authorization first and then later you change the amount different from the original authorized amount, when you capture, it is still the original amount instead of the "changed" amount via either manual amount change OR via deleting item which recalculates the amount. Is that description accurate?

So far this plugin has never altered the original authorized amount for charging and has been this way since perhaps version 1.x. I will take a look and see if changing it after authorization will affect anything else on capture.

**Comment by doriansavage** [comment] 2017-09-15 14:20
Almost :)
If I delete the item, then the changed amount is correctly also changed on stripe.
If I change the amount of items, then the changed amount is correctly also changed on stripe.
If I manually refund at least one item from the wordpress order page, then the changed amount is NOT correctly also changed on stripe.

The issue is that refunded total is not calculated when you charge the cart after an authorization.

**Comment by roykho** [comment] 2017-09-15 16:39
Right, it was not design to work that way from the beginning but I see how that could be an issue so I will look into this. Thanks for reporting.

**Comment by roykho** [comment] 2017-09-15 17:10
Fixed via https://github.com/woocommerce/woocommerce-gateway-stripe/commits/4.0.0

**Closed by roykho** 2017-09-15 17:10 UTC
Labels: [Pri] CRITICAL, [Type] Bug
