### ISSUE TITLE
Stripe API Outdated

### ISSUE THREAD

**Issue by gilesholder** [woocommerce/woocommerce-gateway-stripe#1169] opened 2020-04-15 14:47 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Stripe Dashboard > Developers'
2. See error using outdated API

**Expected behavior**
Latest API to be supported. Not a 6-month-old version.

**Screenshot**
![screencapture-dashboard-stripe-com-developers-1586961843571](https://user-images.githubusercontent.com/40209785/79350949-fba05280-7f2f-11ea-8922-8370bbc2480e.png)

**Environment (please complete the following information):**
 - WordPress Version - Latest
 - WooCommerce Version - Latest
 - Stripe Plugin Version - Latest

**Comment by dwainm** [comment] 2020-05-15 14:51
Hi @gilesholder . Please go ahead and click the upgrade button. The plugin support the latest version of the API. 

I'll close this issue as it is not a bug on our side but something that can be fixed by upgrading.

**Closed by dwainm** 2020-05-15 14:51 UTC
