### ISSUE TITLE
SEPA not shown on checkout

### ISSUE THREAD

**Issue by hesne** [woocommerce/woocommerce-gateway-stripe#3093] opened 2024-04-25 08:46 UTC
**Describe the bug**
When go to checkout SEPA is not shown as payment option. SEPA is enabled in stripe and woocommerce

**To Reproduce**
Just go to checkout. 

**Environment (please complete the following information):**
 - WordPress Version 6.5.2
 - WooCommerce Version 8.8.2
 - Stripe Plugin Version 8.2.0
 - Browser [e.g. chrome, safari] and Version Tested with Chrome, Firefox and Edge

**Additional context**
Disabled all other plugins. Bug still persists. Talked to stripe, they told me this is a bug in woocommerce stripe plugin.

**Comment by a-danae** [comment] 2024-04-25 20:51
Hey @hesne, thanks for the report. 

Following up with a few questions:

1. Is the Legacy experience disabled on your site? You can find this setting at the bottom of the Stripe settings page, at `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings`
2. You mentioned SEPA is enabled on Stripe. This means that this payment method is displayed as "Active" at https://dashboard.stripe.com/settings/payment_methods , correct?
![DkqQnb.png](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/481d0f87-9609-4d5c-ad63-c4e87e852122)

3. Is your store currency set to Euro?
4. Is this happening in previous versions of the Stripe extension?

I can't replicate the problem on my end. SEPA is displayed as an available payment method on the checkout page for both the Legacy and the Updated experiences. So any further information you could provide on this would be helpful!

**Comment by hesne** [comment] 2024-04-25 21:07
Thank you for answering. 
Question 1-3: yes
Question 4: I've done a downgrade to the version before latest. Nothing changed.

When I activate the legacy feature sepa will show in checkout but I cannot enter an IBAN. 

In my subscriptions I also cannot set the payment to sepa. All subscription has changed to manually. A nightmare!

**Comment by a-danae** [comment] 2024-05-07 18:53
Thanks for the details @hesne !

> In my subscriptions I also cannot set the payment to sepa. All subscription has changed to manually.

This behavior sounds similar to what's described in this other issue. Would you please confirm if that's the case? https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3081

**Comment by mattallan** [comment] 2024-09-17 04:46
I've tested the following different variables using the latest Stripe version:
- [x] With Stripe in test mode
- [x] With Stripe in live mode 
- [x] SEPA visible on shortcode checkout
- [x] SEPA visible on block checkout
- [x] Successfully used SEPA to purchase a simple product
- [x] Successfully used SEPA to purchase a subscription

@hesne I'm going to close this as there has been a number of fixes we've shipped that relate to SEPA.

Can you please update to the latest Stripe version and re-open this if the issue is still present?
Thanks!

**Closed as completed by mattallan** 2024-09-17 04:46 UTC
Labels: priority: high, type: bug, status: needs more info
