### ISSUE TITLE
Support for Maestro Card type

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-stripe#1167] opened 2020-04-14 07:33 UTC
**Describe the bug**

Maestro cards are supported by Stripe as shown on the cards landing page - https://stripe.com/payments/features#cards

Customers are reporting that longer Maestro cards are throwing an error:

2698377-zen
2844858-zen

**To Reproduce**

Without using a live payment card, this isn't reproducible since Stripe don't have a Maestro test card. 

**Expected behavior**

Clarification of card types accepted via our extension. Maestro is mentioned in the code but are we able to confirm that longer Maestro cards will be accepted with our use of the Stripe API?

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/29ad3bc597450948386a3654a31eeb799aab23a1/assets/images/maestro.svg#L8
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/99318bbbdbe101a8a4b6b9d4a0d5613ee0960665/assets/css/stripe-styles.scss#L53

**Additional context**

I reached out to Stripe support and they confirmed Maestro cards are accepted but they don't have a test card for us to use. 
I found other test cards for other providers but I don't know if they are payment gateway specific test cards or if when using a card number not in the standard xxxx-xxxx-xxxx-xxxx format, our extension rejects this as not a valid card number - Maestro cards can have between [12 and 19 digits](https://en.wikipedia.org/wiki/Payment_card_number)

Sidenote - we use an outdated card logo compared to the [correct one](https://en.wikipedia.org/wiki/Maestro_(debit_card)#Logos)

**Comment by melindahelt** [comment] 2020-08-27 13:52
13196008-hc requesting this

**Comment by cryptoiskey** [comment] 2020-10-24 01:38
I have been having this issue with many customers from Europe, they can't pay using Maestro. I have spoken to Stripe and they have confirmed Maestro is enabled.

**Comment by jrick1229** [comment] 2020-11-20 18:19
Requested in: https://wordpress.org/support/topic/maestro-card-payment-does-not-show-2/

**Comment by bozicek-png** [comment] 2020-11-22 09:58
I am having the same issue in Europe: Stripe says Maestro is supported while checkout page does not show Maestro icon and paying with Maestro is not possible (Maestro use 15 or 19 digits but Mastercard always use 16 digits). As I am using free WooCommerce plugin they refuse to provide assistance. Any ideas how to enable Maestro in WooCommerce & Stripe?

**Comment by anant1811** [comment] 2020-12-17 11:27
3581421-zen requesting this as well.

**Comment by kimgysen** [comment] 2021-04-17 10:35
I'm from Belgium and before using Stripe I want to know if it supports Maestro. Pretty sure many people in Europe are googling the same thing. Is this solved, or why isn't this priority anymore? Seems this misses out on a lot of potential customers.

**Comment by jerne36** [comment] 2021-10-13 09:02
Any news about this issue??

**Comment by dave-meyer** [comment] 2022-01-08 15:21
Are there any news about this issue?

**Comment by johntunnel** [comment] 2022-01-17 06:32
Does Stripe support Maestro payments in woocommerce? and working normally?

**Comment by haroldparis** [comment] 2022-03-18 10:12
Hi WooCommerce Team ! Having the same issue here. Is it patched ?

**Comment by johntunnel** [comment] 2022-03-18 11:30
> 

According to Stripe Meastro works in most EU countries, but is limited to Maestro cards which have also PIN code. Some older cards do not have PIN. Need to check for each country with Stripe.

**Comment by theabhig** [comment] 2022-10-21 09:14
Also requested in 5648135-zen

**Comment by rossviviano** [comment] 2022-10-22 11:49
Another request in 5650832-zen

**Comment by SimBotBiz** [comment] 2023-01-30 11:32
The status of this bug is not clear, are Maestro cards supported by the wc stripe plugin? Our customers are not able to use Maestro cards to pay.

**Comment by stoltzrx** [comment] 2023-06-21 10:06
Another request here: 6420326-zen

**Comment by wjrosa** [comment] 2024-04-12 15:34
This is a limitation on the Stripe side of things. I spoke with the Stripe team, and they explained that Maestro cards with 16 digits can be used normally in the regular credit card form (the brand icon will not be displayed through). 

If the card contains more than 16 digits or has no CVV, it can be used through the Bancontact payment method. For more information on Bancontact availability, please take a look at [this page](https://docs.stripe.com/payments/bancontact).

They are aware this is bad UX/UI, but due to the low volume of payments with this brand, an improvement has not been prioritized yet.

Closing this since it is not an issue with the extension itself.

**Closed by wjrosa** 2024-04-12 15:34 UTC
Labels: type: bug
