### ISSUE TITLE
Order charge incorrect – items missing (one-off issue on merchant site)

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gateway-stripe#2355] opened 2022-05-25 00:44 UTC
## Describe the bug
We've had a report of an order which was incorrectly charged. The order total was ~$437, and the amount charged via Stripe was $166. This total matches the cost of the first order item($159.86) + Stripe fee ($6.14), so there might have been an error calculating the total to charge. Merchant provided screenshots and logs to confirm the Stripe charge (`POST /v1/payment_intents` log) was $166, so the error is likely on the WooCommerce end. 

Note this order occurred in 2021, so may have been subsequently fixed in WooCommerce core, Stripe, or potentially on merchant site. Merchant has confirmed that no other orders have been affected. 

I'm logging the details in an issue for posterity, in case we see similar issues in future. 

## To Reproduce
Not reproducible at present.

## Additional context
Site currency: SGD

Ticket: 5208945-zen

**Comment by dougaitken** [comment] 2022-07-29 20:49
I appreciate some time has passed since the original comment Rua, thanks for your patience. 

Since I don't see other example, I agree it is possible that this issue has been fixed by a more recent release.

I’m marking this Issue as Closed but I welcome anyone to open a new Issue and reference this if they're able to reproduce this, and if so, please [contact WooCommerce.com support](https://woocommerce.com/my-account/create-a-ticket/)

Thanks

**Closed as completed by dougaitken** 2022-07-29 20:49 UTC
Labels: needs repro
