### ISSUE TITLE
Saved Cards under My-accounts in Stripe disappear on upgrading to WooCommerce 2.6.1 from WooCommerce 2.5.5

### ISSUE THREAD

**Issue by spraveenitpro** [woocommerce/woocommerce-gateway-stripe#19] opened 2016-06-21 08:18 UTC
Prior to upgrade with **WooCommerce 2.5.5 with Stripe 3.0.2**

![](http://cld.wthms.co/1aqDq/4I3LpRQ7+)

After performing the upgrade to **WooCommerce 3.6.1 with Stripe 3.0.2**

![](http://cld.wthms.co/156iI/5R1OBxaT+)

zd-woothemes-432332

**In the wild:**
https://wordpress.org/support/topic/saved-cards-versus-payment-methods-saved-cards-have-disappeared?replies=5#post-8539768

**Comment by dwainm** [comment] 2016-06-21 12:08
Another ticket:

https://woothemes.zendesk.com/agent/tickets/432487

**Comment by gedex** [comment] 2016-06-22 06:24
Updated label to high from critical as it doesn't block functionality.

**Comment by spraveenitpro** [comment] 2016-06-22 07:16
@gedex I feel it does block functionality as customers can not longer access their saved cards 🎱  :)

**Comment by gedex** [comment] 2016-06-22 09:14
Critical is a when you couldn't do anything to proceed, e.g. fatal error or you can't proceed to checkout for whatever reason. The cards on Stripe still exist and customer can add it, it just missing on the new token table.

This can be a tricky to support as customer cards never stored permanently (just transient) in WP before, that means it should checks each customer, fetches cards from Stripe, and store it to new token table. What I could think of, for the easiest way, is when my payment methods empty and there's Stripe customer_id in user's meta we check cards for that customer_id and store any result it found to the new token table, what do you think?

/cc @mikejolley

**Comment by MrFent** [comment] 2016-06-29 01:20
I tested this with the commits to fix the issue: [[Fixed issue where no param being passed to Stripe in pay order page. #27]](https://github.com/woothemes/woocommerce-gateway-stripe/issues/27)

And it fixed the issue with old saved cards not appearing on My Account page, however it only worked if I first added a product to my cart and then visit the checkout page. 

Is there a way to make it so it'll work right off the bat by going to the my account/Payment Methods page without having to go to the checkout page first?

**Comment by gedex** [comment] 2016-06-29 02:22
@MrFent sorry that PR should fixes #23 instead of #19. Reopened.

**Comment by MrFent** [comment] 2016-06-29 04:43
Thank you, and regarding my previous comment... I just realized that even without applying the fix for #27, the saved cards will still appear once I visit the checkout page first.

**Comment by dwainm** [comment] 2016-07-01 13:11
@gedex I don't think #24 fixes this issue.

**Comment by ritchiem** [comment] 2016-07-07 09:27
Hi I'm just going through a rather long over due upgrade from gateway 2.0.3 to 3.0.2 and had this very issue. 
As @MrFent pointed out if you go to the checkout page your card tokens are pulled in and saved but viewing the My Account Page does not.

The removal of woocommerce_get_customer_payment_tokens doesn't fix this issue for me.

I have a work around that works for me as pull request #34 but would love your feedback on this.

**Comment by spraveenitpro** [comment] 2016-07-18 12:37
Hey @dwainm @gedex what do you think about PR #34 , thanks  :)

**Comment by gedex** [comment] 2016-07-19 05:16
@ritchiem @spraveenitpro not sure if the PR will fix the issue. My only concern with the PR is that it fetches cards even though selected payment method is not Stripe.

To fix this issue, it should performs background updater and check any cards it found before to new token table.

**Comment by ritchiem** [comment] 2016-07-25 15:03
Sorry for slow reply.

There is no selected payment method when the My Account page loads the consumer payment tokens. Or at least the changed method in the PR was never called with 'stripe' == $gateway_id when I was trying to debug this section on the My Account page.

A background updater would be a way of helping this however, it would not solve the issue as you still need to have an on demand migration to guard against the situation where the customer visits their My Account page before the background updater has reached their account. 

As a result I personally prefer on demand migrations at time of access where possible as that way you never miss a migration situation. If data consistency is important for some other system access then have an additional updating process is justified.  Taking the site down to do a migration run is never acceptable.

If the concern is the API call load on Stripe then perhaps the best solution is to check $tokens for any existing saved stripe tokens thus preventing the need to reload. 

Given this is supposed to run on every cart checkout to ensure we have the latest saved cards I don't see a major issue with loading it for the My Account Saved Cards page as consistency of experience is what matters for a good user experience.

**Comment by adaptifyDesigns** [comment] 2016-10-29 22:03
Any progress on this issue? 

Updating the latest WC version is becoming more and more urgent for my website. But I do not want to do this until the saved card issue is resolved...

**Comment by conschneider** [comment] 2016-11-15 04:00
Olà folks, 

I just came across the issue in: 
https://woothemes.zendesk.com/agent/tickets/488645

It seems as if there is a WIP fix here: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/43 - forgive my laymen's view if I am wrong.

Any chances we could push this forward to 🏁? 💌

**Comment by allendav** [comment] 2016-12-12 23:08
Possibly related? 506271-zd-woothemes

**Comment by gedex** [comment] 2016-12-14 15:15
@allendav not related. This issue is more about adding data migration when people update from WC 2.5.5 to 2.6.x. In WC 2.5.5, payment token was not born yet so saved cards were saved in transients (or maybe user meta?). WC 2.6.x and Stripe 3.0 both use payment token API which uses custom tables. People upgraded won't see the saved cards that previously stored in transients (though it's not completely missing as the real card data is in Stripe).

**Comment by numenon** [comment] 2017-04-10 18:55
Any update on this? We just upgraded from WC 2.5.5 and are running into this issue. We use WooCommerce subscriptions and it's quite a big issue for existing subscribers to go to their account and not see their credit cards!

**Comment by mattyza** [comment] 2017-05-11 11:10
@spraveenitpro - has this issue come up again since reported?

I'd like to see us work on a way to remedy this for affected merchants (would you be open to testing with us, @numenon ?), without including that code in the Stripe integration itself.

**Comment by mattyza** [comment] 2017-05-31 08:10
On further reading, I don't actually mind having a small piece of migration code in the extension, if it helps merchants as the quickest route.

@spraveenitpro - has this come up again since I posted last?

Assigning to @gedex, for attention in the next few weeks, after we wrap up a collection of shipping fixes.

**Comment by spraveenitpro** [comment] 2017-06-09 06:11
@mattyza it has not come up since then :)

**Comment by mattyza** [comment] 2017-06-09 07:09
Thanks @spraveenitpro.

@gedex - I like the idea of exploring what this would look like, as a migration script within the extension which shows itself only if necessary.

**Comment by gedex** [comment] 2017-07-26 16:32
@mattyza With WC 3.1 as the latest stable, not sure if this still worth to add into our Stripe extension. IIRC, this only affects WC 2.5.x, but I need to checkout the old branch of WC and Stripe to see if I could still reproduce. If we still pursue this, I'd prefer a small one-time plugin that does the migration.

**Comment by mattyza** [comment] 2017-07-27 08:25
@gedex - we support 2.6.x and higher. If this affects a 2.6.x WooCommerce store, we should make sure we take care of this.

A one-time plugin could be fine, although I'd prefer the customer not have to install something else, just to fix an issue we caused. Thus, I'd love to have this as part of the extension, which only shows when it needs to, and then hides itself.

**Comment by roykho** [comment] 2017-11-15 14:35
Closing this as too much time has passed and merchants would have already updated and refreshed the cards by now so is no longer relevant. We don't have any new complaints on this with current versions. Also this seems to only affect merchants with WC 2.5.x.

cc @mattyza if you still think this is needed please reopen.

**Closed by roykho** 2017-11-15 14:35 UTC
Labels: [Pri] Low, [Type] Bug
