### ISSUE TITLE
Apple Pay - Respect guest checkout settings

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce-gateway-stripe#220] opened 2017-04-01 18:59 UTC
Is it possible to respect guest checkout settings?  Currently, when guest checkout is disabled and an account is required, customers paying with Apple Pay can bypass the account creation process.

**Comment by roykho** [comment] 2017-04-01 21:56
Closed - duplicate of this https://github.com/woocommerce/woocommerce-gateway-stripe/issues/148

**Closed by roykho** 2017-04-01 21:56 UTC
