### ISSUE TITLE
SEPA (Direct Debit) isn't working

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-stripe#903] opened 2019-06-27 15:05 UTC
#### Affected ticket(s)
2107794-zen

#### What I expected
To accept payments in EUR using SEPA (Direct Debit)

#### What happened instead
Whenever I try to pay using SEPA I'm getting an error saying `Unable to process this payment, please try again or use alternative method.`

![Screenshot](https://cld.wthms.co/67iElB+)
Screenshot: https://cld.wthms.co/67iElB

I can see Stripe servers return the following response with 400 error code:

```
{
  "error": {
    "message": "The type `sepa_debit` is not a valid source type.",
    "param": "type",
    "type": "invalid_request_error"
  }
}
```

I compared the request we're sending with Stripe API specs here and everything looks correct so far:

https://stripe.com/docs/sources/sepa-debit

#### Steps to reproduce the issue

1. Set store currency to EUR & enable SEPA in Payments settings
2. Add any products to cart and proceed to checkout
3. Add a bank account number and try to place the order
4. Observe the error

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by RadoslavGeorgiev** [comment] 2019-07-02 13:04
@madeincosmos have you enabled SEPA Direct Debit in https://dashboard.stripe.com/account/payments/settings for your account? If not, this would explain the error you are seeing.

As for the questions in the ticket, @NickGreen already mentioned them in p7bbVw-3e5-p2 and we'll discuss this there.

**Comment by madeincosmos** [comment] 2019-07-02 13:37
Hi @RadoslavGeorgiev! Thanks for checking. I'm not seeing any option for SEPA Direct Debit on the page you've linked to, and all the available options are greyed out anyway:

![Screenshot](https://cld.wthms.co/y9JBAK+)
Screenshot: https://cld.wthms.co/y9JBAK

Is there some other setting on the Stripe account I'll need to switch before I can make it work?

**Comment by RadoslavGeorgiev** [comment] 2019-07-02 13:40
It's interesting that your account is not activated. What happens when you click "Activate" next to cards?

Otherwise SEPA Direct Debit is located a couple of rows after Multibanco. I guess you might be not seeing it if you have set your location to Poland, although this wouldn't make much sense: It should work across the whole European Economic Area.

**Comment by madeincosmos** [comment] 2019-07-02 14:21
Stripe only just started an early beta in Poland and I'm not currently seeing an option to activate their account in Poland yet:

![Screenshot](https://cld.wthms.co/3eKo2n+)
Screenshot: https://cld.wthms.co/3eKo2n

Credit Card and Alipay have been working in test mode pretty well for me so far, and I thought the same would be the case with other payment methods. If SEPA can only be tested on an active account, we should probably let the users know about it in plugin documentation.

**Comment by c-shultz** [comment] 2019-07-16 23:00
I was able to get a test payment to go through OK with SEPA direct debit:
<img width="870" alt="image" src="https://user-images.githubusercontent.com/6209518/61335506-8c4fd380-a7e2-11e9-91a2-e54121ed1478.png">


I used the Stripe account in the SS called `Stripe - test account for SEPA`.

I see SEPA in the list of Payment methods:
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/6209518/61335459-5ad70800-a7e2-11e9-91b4-be45a3b192f9.png">

Perhaps the original issue is a Stripe account specific issue for the customer and they should contact Stripe directly?

I'll close this since I can't reproduce, but feel free to open if there still seems to be an issue.

**Closed by c-shultz** 2019-07-16 23:00 UTC
Labels: [Pri] CRITICAL, [Type] Bug
