### ISSUE TITLE
Deprecated notice in debug logs for `wc_stripe_show_payment_request_on_checkout`

### ISSUE THREAD

**Issue by colmtroy** [woocommerce/woocommerce-gateway-stripe#2101] opened 2021-10-26 15:25 UTC
**Describe the bug**
Deprecated notice in debug logs for `wc_stripe_show_payment_request_on_checkout`

**To Reproduce**
1. Enable `WP_DEBUG_LOG`
2. Configure Payment Request locations in WooCommerce -> Settings -> Payments -> Stripe
3. Select "Cart" from available options

**Expected behavior**
No noise in debug logs

**Actual behavior**
[26-Oct-2021 17:18:30 Europe/Prague] PHP Deprecated:  wc_stripe_show_payment_request_on_checkout is <strong>deprecated</strong> since version 5.5.0 with no alternative available. Please configure Payment Request Button locations through the Stripe plugin settings. in /var/www/snip/htdocs/wp-includes/functions.php on line 5596

**Environment (please complete the following information):**
 - WordPress Version - 5.8.1
 - WooCommerce Version - 5.8.0
 - Stripe Plugin Version - 5.7.0

**Comment by reykjalin** [comment] 2021-10-28 05:49
This filter is deprecated — the warning in the debug log is there to encourage merchants to use the settings UI instead of the filters.

To reduce the noise in your logs please don't use the filter to control where the payment request buttons are displayed.

This could also be because a theme or plugin is using the filter. That aspect of this is being discussed in #2099 .

I'm closing the issue, but feel free to re-open it if you think there's something we're not taking into account here.

**Closed as completed by reykjalin** 2021-10-28 05:49 UTC

**Comment by colmtroy** [comment] 2021-10-28 11:47
hey @reykjalin 
I don't use the `wc_stripe_show_payment_request_on_checkout` anywhere.
I see it's still being reference here
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/807cc10d5febb0c02e232d6add0eba2c333c60c1/woocommerce-gateway-stripe.php#L320

Is that the cause of the issue?

**Comment by reykjalin** [comment] 2021-10-28 19:35
That should only be run once at most — whenever the UI settings haven't been configured. The settings are updated after the first run of that piece of code and so this shouldn't be triggered again. You should see no more than 1 logged instance of using the filter from this.

We apply the deprecated filters there to ensure that if a merchant used the filters in the past those settings are preserved.

Maybe there's a plugin you've got installed that uses the filters? Name Your Price (mentioned in #2099) is one such plugin.

**Comment by colmtroy** [comment] 2021-10-28 21:04
@reykjalin 
I reviewed #2099 and I don't use Name Your Price or any other plugin/theme code is calling that filter (i grep'd the entire wp codebase to be 100% sure).

When I load a single product page,`should_show_payment_request_button()` seems to be called each time
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/59cf1d4f19f413cb4e64cad03971adbd081a8e6a/includes/payment-methods/class-wc-stripe-payment-request.php#L864

which in turn is calling this line
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/59cf1d4f19f413cb4e64cad03971adbd081a8e6a/includes/payment-methods/class-wc-stripe-payment-request.php#L897

which is triggering `should_show_prb_on_product_pages`
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/59cf1d4f19f413cb4e64cad03971adbd081a8e6a/includes/payment-methods/class-wc-stripe-payment-request.php#L969

which from going line by line with debug statements is where the problem lies.

**Comment by colmtroy** [comment] 2021-10-28 21:17
@reykjalin and of course I just realized I'm now reporting issues with a different filter ( `wc_stripe_hide_payment_request_on_product_page` is the one that's relevant to my last comment rather than the original one `wc_stripe_show_payment_request_on_checkout` )

So in addition to the new notice I just spotted in my last comment, I can re-create the original one I reported simply by refreshing the checkout screen which triggers:
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/59cf1d4f19f413cb4e64cad03971adbd081a8e6a/includes/payment-methods/class-wc-stripe-payment-request.php#L892

which in turns calls
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/59cf1d4f19f413cb4e64cad03971adbd081a8e6a/includes/payment-methods/class-wc-stripe-payment-request.php#L942

Should these not be getting called on every checkout page request?

**Comment by reykjalin** [comment] 2021-11-03 07:50
The `apply_filters_deprecated()` function call that we use to add the deprecation notice will only result in a deprecation notice [when the filter is used in an `apply_filters()` call](https://developer.wordpress.org/reference/functions/apply_filters_deprecated/). If there is no code calling `apply_filters()` with the relevant filter there should be no deprecation notice.

The code in the Stripe plugin uses `apply_filters()` with the PRB location filters in 1 location:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4fa9d669bf9b7e9e5c604d853b1a0ddc71e8d17a/woocommerce-gateway-stripe.php#L311-L313

We ensure this is only done once by saving the options after using the `apply_filters()` function calls there:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4fa9d669bf9b7e9e5c604d853b1a0ddc71e8d17a/woocommerce-gateway-stripe.php#L315-L330

Note the if-statement in the same place we use to ensure we only call this once:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4fa9d669bf9b7e9e5c604d853b1a0ddc71e8d17a/woocommerce-gateway-stripe.php#L304-L308


So the point from my [previous comment](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2101#issuecomment-954141280) still stands; the code in the Stripe plugin should only result in a maximum of one deprecation notice being logged, ever.


> i grep'd the entire wp codebase to be 100% sure

I understand you're still seeing repeated deprecation notices, but I'm still not convinced this isn't due to a theme, plugin, or some other setup. I've been unable to reproduce this so far.

The only thing I can think of that might be affecting this is if you have some code manipulating the Stripe settings. As you can see from the code I linked to above we rely on the Stripe settings to determine if we need to use the filters one time to initialize the options. If the settings are cleared or manipulated in such a way that the new options are removed, that would result in the filters being run again, and consequently another deprecation notice will be logged.

**Comment by reykjalin** [comment] 2021-11-03 07:59
As a side note; you're using a version of WordPress that is officially not supported by the Stripe payment gateway anymore:

> WordPress Version - 4.8.1

That may be the source of the issue.

As I'm writing that I realize that we failed to update the version in the readme, and apologize for that. I've already opened a PR to address this (https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2109). The main plugin PHP file comment headers are correct though:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4fa9d669bf9b7e9e5c604d853b1a0ddc71e8d17a/woocommerce-gateway-stripe.php#L9-L10

And we published our intentions with this in [this blog post](https://developer.woocommerce.com/2021/08/26/developer-advisory-woocommerce-stripe-support-policy-change/) back in August of this year.

**Comment by colmtroy** [comment] 2021-11-03 13:06
@reykjalin Re: WP version - sorry I'm actually using 5.8.1 - that was an unfortunate typo in the original report.

Let me setup a clean WP instance and see if I can re-create the problem as it's 100% not some other plugin or theme code causing this. But let's not rule out some other aspect of infrastructure/stack causing this. Will let you know.
