### ISSUE TITLE
UPE - Look into why additional check is required to prevent UPE from mounting twice.

### ISSUE THREAD

**Issue by EvanDotPro** [woocommerce/woocommerce-gateway-stripe#1689] opened 2021-08-16 19:09 UTC
See discussion [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1646#discussion_r688855800).

**Comment by FangedParakeet** [comment] 2021-08-20 22:02
I just want to add an explanation here, since I was the author of that initial cautionary comment. The crux of the issue is that if we try to mount a payment element to a DOM element that already has a payment element mounted on it, Stripe throws an error with a message that will be displayed to the end user, but which will make no sense to them--so the lesson here is do not mount the UPE twice. 

I didn't encounter an instance in that particular section of code where `mountUPEElement` was called twice sequentially, but I know well enough not to put my trust in the predictability of asynchronous Javascript. So I added a double-check inside the callback after an intent is created, just to be safe and sure that the UPE could not be mounted twice. I didn't really check to see how often or if at all that `if` block is actually executed, but it didn't seem to hurt. 

That's the whole story about what's going on there though, so I hope this isn't anti-climactic. If you feel confident enough that the second check is redundant, I won't stop you from removing it.

**Comment by EvanDotPro** [comment] 2021-08-24 16:41
@diegocurbelo @reykjalin ^

**Comment by reykjalin** [comment] 2021-09-01 22:11
Let's solve this issue by linking to @FangedParakeet's comment here in code so we have ready access to an explanation for why we want to do that extra check 🙂

**Comment by dannyschwantes** [comment] 2022-07-29 18:11
I appreciate some time has passed since the original comment, thanks for your patience. 

It is possible that this issue has been fixed by a more recent release as I’ve been unable to replicate the issue you described using the latest release of the core WooCommerce plugin and the [WooCommerce Stripe Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/). 

As I’m unable to reproduce this, I’m marking this Issue as Closed. Please do open a new one if you are able to reproduce this again.

**Closed as completed by dannyschwantes** 2022-07-29 18:11 UTC
Labels: priority: low, component: UPE
