### ISSUE TITLE
Subscriptions: multiple retry rules applied

### ISSUE THREAD

**Issue by DanReyLop** [woocommerce/woocommerce-gateway-stripe#1070] opened 2019-10-28 11:37 UTC
Steps to reproduce:
- Buy a subscription product with the `4000002760003184` credit card (it always requires SCA authorization).
- Go to WP-Admin, manually renew the subscription.
- Go to the renewal order, you'll see something like this in the Order Notes:

![Screenshot 2019-10-28 at 11 29 33](https://user-images.githubusercontent.com/1715800/67675481-1594ab80-f977-11e9-90eb-8de525587165.png)

That's not good. Such information overload makes the Order Notes be just noise.

**Comment by thenbrent** [comment] 2019-10-29 23:12
> you'll see something like this in the Order Notes:

Do you think specific notes should be removed, or the content in some of the notes should be reduced?

It's helpful to include a note for each stage of the retry process so that merchants, and happiness, can see what's happened over the lifecycle of the order. This explains why the order may have a certain status or a payment didn't succeed.

That said, in this screenshot, it looks like two retry rules were applied at the same time. Normally, only one would be applied (and one set of notes added). That could be a bug.

**Comment by DanReyLop** [comment] 2019-10-29 23:20
> That said, in this screenshot, it looks like two retry rules were applied at the same time.

That's the main problem I see. I count 3 retry rules being applied there, and I've been able to reproduce that behaviour consistently.

I'm not even sure that a "retry rule" should be executed at this point, since the "SCA failed" error is not temporary. I (or someone else) would need to spend a bit more time digging into this, see if there's something that we're doing wrong. Sorry for the issue description being a bit vague, I just wanted to put it in writing before it got lost.

**Comment by thenbrent** [comment] 2019-10-30 00:30
@DanReyLop thanks for the confirmation. That's definitely not expected behaviour. I've updated the issue title to reflect that multiple retries is the issue here.

At a guess, because the Stripe extension is changing the order status to failed after a retry rule has been applied, the next rule is applied again.

> I'm not even sure that a "retry rule" should be executed at this point, since the "SCA failed" error is not temporary.

I think there's been a few discussions about that already. I believe the idea was to use the retry system's dunning emails, that's why it's being applied (even though we know additional attempts to process the transaction won't work). FWIW, that's not that different to other use cases already with this behaviour, like an expired card.

**Comment by DanReyLop** [comment] 2019-10-30 08:46
> I believe the idea was to use the retry system's dunning emails, that's why it's being applied (even though we know additional attempts to process the transaction won't work).

Yes, and those retries are fired in intervals, during several days. Those triggered e-mails act as "reminders" for the customer to go back into the site and pass the SCA challenge.

What doesn't make any sense is to have several retries fire immediately (see the times on all those order notes, they all happened in the same PHP request). As I said, someone should dig a bit deeper into why this is happening, and if there's an easy way to stop it. Not super urgent, but it would be a nice UX improvement.

**Comment by v18** [comment] 2019-11-12 03:52
This may be related to how we handle webhooks. My unverified guess is that we receive a webhook, changing the order status back to failed, and thereby triggering another retry.

As for why the first retry rule is applied right away vs in 12 hours - from what I gather the rule is applied right away on status change but the actual renewal attempt is scheduled for 12 hours ahead ([doc](https://docs.woocommerce.com/document/subscriptions/failed-payment-retry/#section-2))

> If a rule exists, it is applied and Subscriptions will:
> schedule a pending retry event to occur after a set period of time
> set the status on the subscription to match the status defined by the rule

**Comment by thenbrent** [comment] 2023-08-10 04:36
Closing this one due to lack of recent activity the last 3 years. If it's still an issue, we can reopen to prioritize it in the backlog.

**Closed by thenbrent** 2023-08-10 04:36 UTC
Labels: priority: low, component: SCA, component: woocommerce subscriptions, component: webhooks
