### ISSUE TITLE
Shipping Cost not being added on Apple Pay product page

### ISSUE THREAD

**Issue by jasonhdavis** [woocommerce/woocommerce-gateway-stripe#813] opened 2019-03-08 23:29 UTC
#### What I expected
When using the Pay Request button on the product page, Apple Pay should pass the shipping address to Woocommerce and return the available shipping options.

#### What happened instead
If a user has not added the product to their cart already, the Apple Pay button will not work properly, saying "Amount Pending" for shipping. 

#### Steps to reproduce the issue

I have removed the payment button on the product page currently. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by dougaitken** [comment] 2019-03-18 10:08
From what you are describing, Apple Pay is working as expected. Shipping rates cannot be returned when there are no products in the cart. 

> Apple Pay should pass the shipping address to Woocommerce and return the available shipping options.
> If a user has not added the product to their cart already

It could be that your theme is controlling the cart behavior. On a standard WooCommerce installation with the latest Stripe extension and using the Storefront theme, shipping is calculated for a product even if I haven't added to cart since there is `1` in the product field.

Here is a gif of my core test site - https://d.pr/94zn3F

Try it out here `https://dougwoocore.mystagingwebsite.com/product/vneck-tee/`

If you cannot replicate the behavior you're experiencing on your own site, then this would be a conflict happening somewhere so I'd recommend going through the [conflict test steps in our documentation](https://docs.woocommerce.com/document/how-to-test-for-conflicts/).

**Comment by allendav** [comment] 2019-09-13 20:54
Closing. Please open a new issue if this can be reproduced.

**Closed by allendav** 2019-09-13 20:54 UTC
Labels: [Status] Needs Author Reply
