### ISSUE TITLE
Order status transition fails after multiple Stripe SCA authentication failed attempts

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#2660] opened 2023-07-11 01:14 UTC
**Describe the bug**

A user reported a case where the payment in Stripe went through after SCA authentication initially failed which marked the order as failed. Then, there's another note that says Stripe charge was successful but order status remained unchanged (Failed).

Order notes when normal:
- Stripe payment intent created (Payment Intent ID: xxxxxx)
- Order status changed from Pending payment to Completed.
- Stripe charge complete (Charge ID: xxxxxx)

Stripe timeline when normal:
- Payment started
- Payment succeeded

Order notes when error happens:
- Stripe payment intent created (Payment Intent ID: xxxxx)
- Stripe SCA authentication failed. Reason: Your card was declined. Order status changed from Pending payment to Failed.
- Error during status transition. First argument is expected to be paramter value, none specified.
- Stripe charge complete (Charge ID: xxxxx)

Stripe timeline when error happens:
- Payment started
- The cardholder attempted 3D Secure authentication 3 times
- Failed payment with xxxxx
- Failed payment with xxxxx
- Failed payment with xxxxx
- 3D Secure authentication succeeded
- The payment was verified with 3D Secure…
- Payment using xxxxx succeeded.

[activity-log.txt](https://github.com/woocommerce/woocommerce-gateway-stripe/files/12009722/all-activity.txt)

**Comment by thenbrent** [comment] 2023-07-11 03:54
At a long shot, I wonder if this could be related to the #2536 race condition given we haven't been able to reproduce it (and I could see that race condition making it harder to reproduce).

Specifically, this part on that issue seems relevant potentially to failed -> processing order status transitions also:

> when the webhook is processed before the customer loads the Order Received page we never finish processing the payment in the UPE gateway because the order status is wrong; it's been set to processing by the call to `WC_Order::payment_complete` when processing the webhook.

Do we know if this use is using UPE?

If so, is it possible something like that could cause the order to get stuck in failed?

**Comment by thenbrent** [comment] 2023-07-11 04:21
> A user reported a case where the payment in Stripe went through after SCA authentication initially failed which marked the order as failed. Then, there's another note that says Stripe charge was successful but order status remained unchanged (Failed).

Just noting that in the [wp.org post](https://wordpress.org/support/topic/bug-when-stripe-sca-authentication-initially-fails/
), the symptoms are described a bit differently: 

> I checked the order in the WC Dashboard and found the status was Completed.

So in that case, it reads like the order's status was changed correctly but corresponding status transition events didn't occur, namely emails being sent. What's particularly weird here is that the status was changed despite the error message noted: "_Error during status transition. First argument is expected to be parameter value, none specified._"

I checked the ticket to make sure this wasn't simply an error with the AutomateWoo workflow requiring a `pending -> complete` transition, and it's not (it is set to run on any status that transitions to `Completed`).

For now, because this is a single report, I'm labelling it low priority; however, we should keep an eye out for other status transition related failures to confirm it's not a compatibility issue.

**Comment by wyter** [comment] 2023-07-16 07:19
6360315-zen

Not a new occurrence, just adding the ticket where the issue was first reported.

**Comment by wpniall** [comment] 2023-07-24 06:36
6466549-zen seems related, as Stripe SCA fails with a WooCommerce Subscriptions initial order that also has this Stripe plugin error reported in 6360315-zen and [this WP.org forum thread](https://wordpress.org/support/topic/bug-when-stripe-sca-authentication-initially-fails/).

```Error during status transition. First argument is expected to be paramter value, none specified. Stripe error.```

In this case:

- Logs show `Could not find order via charge ID: ch_XXXXX...` despite the charge ID recording on the Failed Payment order as well as in the Stripe Dashboard. There's also `Stripe PaymentIntent pi_XXXXX... requires authentication for order XXXXX`.
- There's only one occurrence of this issue, so it appears to perhaps be an isolated case.

**Comment by anant1811** [comment] 2023-08-11 03:54
Similar case here: #6639913-zen 

On this one, SCA failed and the order was marked as Failed. Then, somehow the payment succeeded (merchant confirmed they got the payment in Stripe and we also verified using Stripe log and receipt URL), however, the log of this successful payment in Stripe has a different payment intent ID. On their Woo logs, the same payment intent ID shows this error: `Could not find order via intent ID: pi_3Nd6WRDIF2D7xESr1r5xXZML`

So, this is what I think has happened for this one: 

- Customer tried placing order, payment initially failed as SCA auth failed 
- The customer tried again, the payment went through but with a different payment intent ID 
- The info about the successful payment was relayed back to the site, but since the payment intent was different — Stripe extension was not able to find the order to which the payment belonged to (that's why we see `Could not find order via intent ID: pi_3Nd6WRDIF2D7xESr1r5xXZML` in Stripe's WooCommerce logs)
- The actual order failed as the payment for it was not recognised due to different payment intents

**Comment by WillBrubaker** [comment] 2023-08-30 05:56
I believe we have a case of this in 6688022-zen

Customer's first order failed and `Error when processing payment: The latest payment attempt of this PaymentIntent has failed or been canceled, and the attached payment method has been removed. You can try confirming again with a new payment method.` is logged. A few hours later, the same customer places another order. The merchant has told us that payment was taken at Stripe but the only thing in the Stripe log is the request to `payment_intents` for the second order. No further information about that transaction is logged.

**Comment by ChrissiePollock** [comment] 2023-12-23 17:39
I think this is also happening in #7346874-zen. Some orders were stuck in Pending Payment although the payment had actually taken place, while there were also other orders that were put through to Processing without a payment. The logs show "Could not find order via charge ID."

**Comment by Babylon1999** [comment] 2024-01-03 16:17
One more here: https://wordpress.org/support/topic/how-the-payment-check-works-processing-failed-completed/

**Comment by shameemreza** [comment] 2024-06-09 16:05
Possibly another report here: 8305191-zen
Thread: https://wordpress.org/support/topic/the-provided-paymentmethod-has-failed-authentication/

**Comment by wjrosa** [comment] 2024-12-05 14:46
I tried to reproduce this issue multiple times with different scenarios, different cards, a card falling then succeeding, and many others. I never got the error reported (with the new checkout experience). I will be closing this for now. If this still happens to anyone, please let us know.

**Closed as completed by wjrosa** 2024-12-05 14:46 UTC
Labels: priority: high, type: bug
