### ISSUE TITLE
Failed order: when multiple email addresses are set in notification, duplicate emails are sent

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-stripe#1460] opened 2021-01-29 09:22 UTC
**Describe the bug**

When multiple addresses are set in the email notification settings and the order fails, duplicate emails are sent out. 

**To Reproduce**

1. Go to 'WooCommerce > Settings > Emails > Failed order' and set two email addresses
2. Via the front-end, create a new order. Make sure it fails, you can use the Stripe card `4000008260003178`. Authorize the payment, it'll fail due to not enough funds.
3. Go to 'WooCommerce > Orders' and confirm that the order has been created and set to failed.
4. Check email / mail log to confirm that two order failed emails were sent.

**Expected behavior**

When an order fails, only one email should be sent, rather than two.

**Screenshots**

Set two email addresses in the failed order email settings:

<img width="976" alt="Screen Shot 2021-01-29 at 10 10 42" src="https://user-images.githubusercontent.com/17844465/106255531-6fd78880-621a-11eb-8fd4-1c61a934d901.png">

Confirmation in the email log that the failed order notification sends two emails, while the new order notification is only sent once:

<img width="1131" alt="Screen Shot 2021-01-29 at 10 16 14" src="https://user-images.githubusercontent.com/17844465/106256102-23407d00-621b-11eb-901d-a63a239530a1.png">

(Screenshot is from WP Mail Log, but the same emails showed up in the email inbox)

**Environment (please complete the following information):**

 - WordPress Version: 5.6
 - WooCommerce Version: 4.9.1
 - Stripe Plugin Version: 4.7
 - Browser [e.g. chrome, safari] and Version: Firefox, 85.0
 - WP Mail Logging

**Additional context**

Originally reported: https://wordpress.org/support/topic/double-failed-order-notifications-only-with-stripe/

**Comment by cl0udres** [comment] 2021-01-29 20:32
We're occurring this problem since about one year. We hope that it can be fixed soon.

**Comment by thenbrent** [comment] 2023-06-07 04:55
Given failed order emails are used in the example, this is possible the same as #1229.

**Comment by cl0udres** [comment] 2023-06-07 05:00
We're still occurring this problem, but it's still open I see. Could you fix definitely, please?

**Comment by gameDNA-Helix** [comment] 2024-01-22 12:36
I also experience this issue. Could you please fix?

**Comment by cl0udres** [comment] 2024-01-22 12:44
We've been dealing with this issue for years now. It's unbelievable that no one has taken the initiative to address it.

**Comment by cl0udres** [comment] 2024-05-16 16:47
After 3 years, the problem is still here. Frankly, it seems surreal to me that no one has managed to solve it in all this time. Is there anyone reading this?

**Comment by shameemreza** [comment] 2024-07-18 02:47
Another report here: 8493960-zen
Thread link: https://wordpress.org/support/topic/duplicate-emails-for-failed-orders-if-multiple-admin-email-addresses

**Comment by annemirasol** [comment] 2024-10-17 20:29
Closing.

- Looks to be caused by the same issue that has since been fixed by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3418
- Can no longer reproduce.

**Closed as completed by annemirasol** 2024-10-17 20:29 UTC
Labels: needs repro
