### ISSUE TITLE
Boleto and Oxxo don't update order status after payment when UPE is enabled

### ISSUE THREAD

**Issue by rafaelzaleski** [woocommerce/woocommerce-gateway-stripe#2605] opened 2023-04-27 12:23 UTC
**Describe the bug**

When the UPE (Unified Payment Experience) feature is enabled, the order status is not updating correctly for payments made through Boleto and Oxxo.

**Steps to Reproduce:**

1. Enable the UPE feature in the advanced settings.
2. Place an order using [Boleto](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#checkout-with-boleto) or [Oxxo](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#checkout-with-oxxo) as the payment method. 
3. Complete the payment process.
4. Check the order status after the payment succeeds in Stripe (it takes about 5 minutes).

**Expected Behavior:**

After the payment is successfully completed, the order status should be updated to `Processing` to reflect the payment confirmation.

**Actual Behavior:**

The order status is initially updated to `On-Hold` but never changes to `Processing` when the payment confirmation is received. The order description in Stripe does not match the text of successful orders.

**Environment:**

 - WordPress Version: `latest`
 - WooCommerce Version: `7.6.1`
 - Stripe Plugin Version: `7.3.0`

**Screenshots:**

![image](https://user-images.githubusercontent.com/4153905/234860655-ae5e9a49-be38-4032-b7c1-dd68b470d575.png)

**Additional Information:**

- This issue is specific to payments made through Boleto and Oxxo when the UPE feature is enabled.
- Other payment methods are not affected by this issue.
- The Stripe plugin logs indicate that a matching order could not be found for the payment.

```
====Stripe Version: 7.3.0====
====Start Log====
payment_intents/pi_3N1G45IYPG9vFpGr1NDvf7lI request: Array
(
    [amount] => 4400
    [currency] => MXN
    [statement_descriptor] => 
    [description] => My WordPress Site - Order 661
    [customer] => cus_NmnwFtyo136L4F
    [payment_method_types] => Array
        (
            [0] => oxxo
        )

    [metadata] => Array
        (
            [customer_name] => Customer Customerson
            [customer_email] => XXXXXXXXXXXXXXXXXXXXX
            [site_url] => https://XXXXXXXXX.mystagingwebsite.com/
            [order_id] => 661
            [order_key] => wc_order_16gFOZqIgDqTH
            [payment_type] => single
        )

)

====End Log====


2023-04-26T21:43:02+00:00 DEBUG 
====Stripe Version: 7.3.0====
====Start Log====
Stripe PaymentIntent pi_3N1G45IYPG9vFpGr1NDvf7lI succeeded for order 661
====End Log====


2023-04-26T21:43:04+00:00 DEBUG 
====Stripe Version: 7.3.0====
====Start Log====
Could not find order via charge ID: py_3N1G45IYPG9vFpGr1ozrLRzm
====End Log====
```

**Comment by Mayisha** [comment] 2024-03-19 10:15
I have tested OXXO and Boleto locally and on a test JN site (Stripe `8.0.0`). I could reproduce this issue only when the webhook is not configured properly (missing webhook secret/ missing necessary events in the created webhook etc.). 

With a proper webhook setup, I could not reproduce this issue. The order status successfully moves to the `processing` state after payment is `Succeeded` in the Stripe dashboard.

I was able to get the `Could not find order via charge ID: abc` message in my logs. However, this does not seem like a big issue as during other steps of the transaction flow, the transaction ID is saved properly and the order status is also updated to the expected one (`processing`)

I am closing this issue for now. Let's reopen if this resurfaces and is reported again.

**Closed as completed by Mayisha** 2024-03-19 10:15 UTC
