### ISSUE TITLE
Missing product subtotal in for Express Payment method in both block checkout flow and shortcode checkout flow.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gateway-stripe#1605] opened 2021-06-15 19:11 UTC
**Describe the bug**
I first discovered this while testing the Express Payment method integration for the Cart and Checkout block but discovered it also happens for the express payment method integration in the shortcode checkout flows as well. This _also_ happens with WooCommerce Payments. 

The issue is that the payment request modal (Reproduced with Google Pay and Browser Payment Request button) is not showing the products subtotal (but is showing the correct grand total).  However, when I test with the blocks integration with Stripe build into WooCommerce Blocks, the subtotal _is_ showing correctly.

**Testing environment:**

- Stripe or WooCommerce Payments `trunk` - production build. I was able to reproduce the same thing for both (but I was testing with only one of the payment methods active).
- WooCommerce blocks `trunk`.
- Test mode for payments.

My taxes setup is this:

<img width="723" alt="CleanShot 2021-06-15 at 14 52 05@2x" src="https://user-images.githubusercontent.com/1429108/122108166-dfc16680-cde9-11eb-8dc0-3a73fc8c31b0.png">

**To Reproduce**
Testing involves adding a product to the cart and triggering Express payment method to checkout (I tested Google Pay via Chrome and Browser Payment Request via Edge). 

When the Express Payment modal loads, you'll see that there is a shipping subtotal and a taxes subtotal, but the product subtotal is not present. Grand Total _is_ correct though.

Here's some screenshots of the broken behaviour:

Browser PaymentRequest button on edge (Stripe and WooCommerce Payments):
<img width="558" alt="CleanShot 2021-06-15 at 14 39 38@2x" src="https://user-images.githubusercontent.com/1429108/122107393-029f4b00-cde9-11eb-8b0d-1e7d8376a8e3.png">

Google Pay (Stripe and WooCommerce Payments):
<img width="637" alt="CleanShot 2021-06-15 at 15 08 57@2x" src="https://user-images.githubusercontent.com/1429108/122109723-ae499a80-cdeb-11eb-96cb-c1c03ae13766.png">

However, if I test with the built-in blocks integration for Stripe, I get the expected behaviour. **To test built-in blocks integration:** Comment out [this line](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/ae73978f0012a250f89c377f34b9b89358f1cca1/woocommerce-gateway-stripe.php#L421).

Here's what it looks like when working as expected:

Built In Blocks integration Google Pay:
<img width="631" alt="CleanShot 2021-06-15 at 15 10 51@2x" src="https://user-images.githubusercontent.com/1429108/122109928-ea7cfb00-cdeb-11eb-9769-8b7ea1d8d08b.png">

Built in Blocks Integration Browser PaymentRequest button:
<img width="539" alt="CleanShot 2021-06-15 at 14 44 17@2x" src="https://user-images.githubusercontent.com/1429108/122107580-38dcca80-cde9-11eb-8c6c-71c38101916f.png">

**Comment by reykjalin** [comment] 2021-06-15 19:37
This is intended behavior; we hide the itemized list of products and their subtotals from the Payment Request dialog by default:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/ae73978f0012a250f89c377f34b9b89358f1cca1/includes/payment-methods/class-wc-stripe-payment-request.php#L1491-L1507

You can choose to show the itemized list with a filter:

```php
add_filter( 'wc_stripe_payment_request_hide_itemization', '__return_false' );
```

Since this is not a bug I'll close the issue 🙂

**Comment by asumaran** [comment] 2021-06-15 19:37
It looks like we were returning a "Subtotal" before but now [it's never used](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/trunk/includes/payment-methods/class-wc-stripe-payment-request.php#L1495). 

--

By the way. I'm removing the unused `$subtotal` variable in my PR https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1602

**Comment by reykjalin** [comment] 2021-06-15 19:45
Hmm, we should add the subtotal back actually. That's still supposed to be there — I don't know when it was lost.

So I'm reopening this issue to track the following:

> Add the subtotal of products in the cart (without shipping and tax) back to the payment request overview even when we're not showing an itemized list of products.

**Closed as completed** 2021-08-31 17:15 UTC
Labels: priority: high, type: bug, component: payment request buttons
