### ISSUE TITLE
URGENT: Paid orders stuck at “pending payment”

### ISSUE THREAD

**Issue by Petbeginners** [woocommerce/woocommerce-gateway-stripe#3154] opened 2024-05-27 17:09 UTC
**Describe the bug**
Orders are stuck at "pending payment" in Woocommerce even though customer has completed payment at checkout and Stripe is showing a successful payment with 200OK webhook response. This issue appears to have cropped up after the latest Stripe plugin 8.3 update.

**To Reproduce**
1. Update to latest version of Stripe plugin 8.3 
2. Customer completes payment successfully at checkout and payment is reflecting in Stripe with 3D secure authentication
3. Order in woocommerce remains in "pending payment" status even though Stripe webhooks show 200OK status (the order detail only shows paymentintent started and nothing else...)

**Expected behavior**
The order should be marked as processing after payment is successful, but is stuck at pending payment status. 

**Screenshots**
PLEASE NOTE THAT THIS PROBLEM HAS ALREADY BEEN REPORTED BY MULTIPLE USERS ON THE FORUM: 

1) https://wordpress.org/support/topic/paid-orders-get-a-waiting-for-payment-status/

2) https://wordpress.org/support/topic/payment-status-not-updating-from-stripe-webhook/

3) https://wordpress.org/support/topic/urgent-paid-orders-stuck-at-pending-payment/

4) https://wordpress.org/support/topic/stripe-is-not-updating-order-status/

**Environment (please complete the following information):**
 - WordPress Version - Latest version 6.5.3
 - WooCommerce Version - Latest version 8.9.1
 - Stripe Plugin Version - Latest version 8.3
 - Browser [e.g. chrome, safari] and Version - All browsers
 - Any other plugins installed - Woocommerce PayPal Payments

**Additional context**
I'm not a dev but this is a very serious problem as orders are not being reflected as processing in the Woocommerce dashboard even though they are successfully paid on Stripe's end. Please kindly fix this issue ASAP. Thank you

**Comment by glagonikas** [comment] 2024-05-28 06:37
Hi @Petbeginners it looks like we have the same issue (also reported [here](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3125#issuecomment-2131389553)).

It seems to be an issue caused by #3078.

Upon investigation, we've concluded the following:

This change is made to not duplicate stripe orders meta, however the meta used is used inside the normal Gateway ( [woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php at release/8.3.0 · woocommerce/woocommerce-gateway-stripe](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/release/8.3.0/includes/class-wc-gateway-stripe.php#L459) ) and as well as the UPE Gateway. This makes the error show up when it's not needed, and break the flow on the normal checkout without UPE, in very particular cases.

We've tested using the following

Settings:
- Make sure the new checkout is disabled, so not using the UPE class.
- Make sure that all the stripe webhooks are enabled on the testing enviroment, from stripe account settings.
- Enable logging from the stripe settings.

Theme:
- Twenty Twenty-Four 1.1

Plugins:
- WooCommerce 8.9.1
- WooCommerce Stripe Gateway 8.3.0

Steps to reproduce:
1. Create a simple product with price of 5.
2. Add the product to cart, and proceed to checkout.
3. Start the checkout process, using a 3ds test card, for example: 4000000000003220
4. Tick to save the card information.
5. Click the place order, and on the 3ds challenge, fail the challenge.
6. You will get the message "Unable to process this payment, please try again or use alternative method.".
7. Now click on the "place older" button and complete it.
8. You will observe that the order fails to complete, even if should have worked, as the payment is taken.

Notes:
1. Each subsequent order that will follow the same flow will have the same results, even with the saved card.
2. If you check the logs you will see a message like "Stripe UPE waiting for redirect. The status for order #order-number might need manual adjustment." - that has nothing to do with the checkout that we had, as UPE is not enabled.


Our solution was to revert to the previous version that worked (8.2.0) and wait until this is resolved.

Considering the number of reports on the forum and GH, I think @mattallan should take a look as a priority and release a hotfix.

**Comment by global-ipconnect** [comment] 2024-05-28 19:48
We have encountered the same issue across multiple clients. The only plugins installed for these clients are WooCommerce and the WooCommerce Stripe plugin. PayPal is not being used in these instances.

**Comment by dave-adams85** [comment] 2024-05-28 20:15
Just commenting to say I am also experiencing this issue. 

@glagonikas it appears your comments around the (now missing) meta being used for UPE and normal checkout is correct, as I’ve switched to the UPE gateway and the issue has thus far not recurred. It appears the PR has introduced this bug for the legacy stripe checkout.

UPE however looks poor when using the checkout shortcode, so isn’t (yet) a permanent solution. It looks great with the checkout block, but that is incompatible with some plugins, preventing a switch to it.

**Comment by mattallan** [comment] 2024-05-29 01:26
Thanks @glagonikas for the ping and @Petbeginners for reporting this issue. I've just pushed up a fix in #3162 and have pinged the team to get this tested & reviewed as soon as possible. 

Appreciate your patience!

**Comment by mattallan** [comment] 2024-05-29 05:10
The PR has been merged and will be released in 8.3.1. Closing this

**Closed as completed by mattallan** 2024-05-29 05:10 UTC
Labels: type: bug
