### ISSUE TITLE
Opera Browser Crash when clicking Checkout button in cart AND enabled stripe plugin

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [woocommerce/woocommerce-gateway-stripe#372] opened 2017-10-05 07:12 UTC
This is a bug report.

Products involved:
**WooCommerce v. 3.1.2**
**WooCommerce Stripe Gateway 3.2.3**
[WordPress.com Theme "Snaps" ](https://wordpress.com/theme/snaps) on a self-hosted wp installation
**Jetpack v. 5.4** (required to use with above theme to be able to use its full potential)
**WooCommerce Germanized 1.9.1** (required to use witch WooCommerce in Germany because of legal obligations WooCommerce does not meet out of the box)
**YOAST SEO 5.4.2**
**Advanced Custom Fields PRO v. 5.6.3**

Tested on https://ckvoicelessons.de (Site A) and https://plantbasedkochschule.de (Site B)
Had to deactivate Stripe plugin on both sites now, to allow opera browser users to complete checkout without browser crash.

Description of the issue:
When clicking the “Checkout” button in woocommerce cart page, Opera browser crashes without any further notice. The browser application shuts down and restarts. I am unable to get to the Checkout page, while stripe plugin is activated on the site.

Browser environment where this occurs:

Version: | 48.0.2685.35
Stable
Mac OS X 10.12.6 64-bit

Is this the only opera version affected?
No. I saw this issue already a while back. Can't exactly say when I first noticed it though. And I wasn't sure what was causing the crashes then. Just learned about the stripe plugin connection when I saw these same crashes on Site B (see above) right after activating and setting up stripe plugin.

Is this replicable?
Yes, I tested it on two independent WordPress installations on two different servers. Both installations are setup completely different. One of which is a multisite setup even and is using a different theme and further plugins as well. 

Maybe the developers need to look into this.

[Related support forum thread](https://wordpress.org/support/topic/browser-crash-with-opera-browser/)

**Comment by roykho** [comment] 2017-10-05 14:47
No issues here. Using Opera 48.0.2685.35 and I am able to get to the checkout page. Seen here ![](http://cld.wthms.co/yYTrBG+)

**Comment by roykho** [comment] 2017-10-06 02:44
Closing this for now as I and my colleague can't reproduce this. Please feel free to comment more if you have more information on this.

**Closed by roykho** 2017-10-06 02:44 UTC
Labels: [Pri] Low, [Type] Bug

**Comment by s-a-s-k-i-a** [comment] 2017-10-09 16:49
Update:
This only then happens, if the Option "Payment Request API" is enabled in WooCommerce Stripe settings.
And then only affects Opera.

Maybe this helps. IT happens on all woocommerce sites I have tested this with. Several different WooCommerce setups, plugins and themes.
You might want to add a note next to this stripe setting regarding incompatibility with opera browser.

Best
Saskia

**Comment by roykho** [comment] 2017-10-09 17:36
In my initial test, I had both Apple Pay and PaymentRequest API enabled. It is working just fine for me.

**Comment by s-a-s-k-i-a** [comment] 2017-10-09 18:02
Hm thats odd.

I tried it on three different wp installs. As soon as I enable Payment request API, my opera browser (on Mac OS) crashes when trying to go to Checkout from cart page.

**Comment by roykho** [comment] 2017-10-09 18:25
I would suggest you test again but with only WooCommerce and Stripe enabled and use WooCommerce Storefront theme.
