### ISSUE TITLE
Payment request fails address validation at checkout

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-stripe#880] opened 2019-06-04 19:54 UTC
#### Affected ticket(s)
ticket: 2072852-zen

#### What I expected
To be able to pay for a product via a payment request button.

#### What happened instead
I get the equivalent of an 'invalid billing state' error.

#### Steps to reproduce the issue
1. My Google account has its region configured as Spain
2. My address:
![see screen shot](https://cld.wthms.co/bfxqhR+)
3. It's not entirely clear why the Málaga province isn't showing in that screenshot, but this is the Málaga province.
4. Attempt to pay for an item with that address. This will result in a validation failure here: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.2.0/includes/payment-methods/class-wc-stripe-payment-request.php#L970

The validation failure happens because an htmlentityencoded state is what is being checked, e.g. https://github.com/woocommerce/woocommerce/blob/master/i18n/states.php#L328

wrapping $state in html_entity_decode fixes this in my testing.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by EtiennePoolman** [comment] 2020-02-17 05:51
Another report in 2694848-zen for Spain but using Apple Pay.

Might be related to the same issue in PayPal Checkout here - https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/501

**Comment by dougaitken** [comment] 2020-06-02 14:47
Possibly related to #1065

**Comment by madeincosmos** [comment] 2020-09-29 11:26
Tested this again with WooCommerce 4.5.2 & Stripe 4.5.2 with Apple Pay. 

The error happens whenever I enter province name with different spelling than the official one:

![Screenshot](https://d.pr/i/Br6Hpm+)
Screenshot: https://d.pr/i/Br6Hpm

If I enter the province name exactly as it is defined in WooCommerce core, it's working fine:

https://github.com/woocommerce/woocommerce/blob/master/i18n/states.php#L389

So for example, I'm not able to reproduce the error when province name is `A Coruña`, but it happens when I use `A Coruna` or `a coruna`. Given that there's no option to edit a previously entered address with Apple Pay and you need to add a new one from scratch, this still looks pretty bad to me.

**Comment by abelbascu** [comment] 2021-01-09 23:00
> Tested this again with WooCommerce 4.5.2 & Stripe 4.5.2 with Apple Pay.
> 
> The error happens whenever I enter province name with different spelling than the official one:
> 
> ![Screenshot](https://camo.githubusercontent.com/57c913b5e0448d941ce38bb778f441e18b02146c9426c7e97f46e0334660cee8/68747470733a2f2f642e70722f692f5a77566763642b)
> Screenshot: https://d.pr/i/ZwVgcd
> 
> If I enter the province name exactly as it is defined in WooCommerce core, it's working fine:
> 
> https://github.com/woocommerce/woocommerce/blob/master/i18n/states.php#L389
> 
> So for example, I'm not able to reproduce the error when province name is `A Coruña`, but it happens when I use `A Coruna` or `a coruna`. Given that there's no option to edit a previously entered address with Apple Pay and you need to add a new one from scratch, this still looks pretty bad to me.

@madeincosmos I can confirm that this also happens for GooglePay. Please check my answer at https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/659#issuecomment-757376067

Apologies for the request @WillBrubaker: from a non-coder perspective, what PHP code snippet should be added to a functions.php to workaround this?

**Comment by v18** [comment] 2021-02-25 05:10
Related: #568

**Comment by ricardo** [comment] 2021-03-03 22:14
When I was working on #1476, I considered matching states without accents, but then I realized this would create a broader match on the current approach, which we don't want. E.g. in Brazil we have this state called `Pará`, but we also have this state where I live, which is called `Paraná`. If we skip the accents, the current algorithm will select `Pará` instead of `Paraná`.

This is because the current approach is simply [matching substrings](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.2.0/includes/payment-methods/class-wc-stripe-payment-request.php#L970) from the states list from WC into the input from Chrome or Apple Pay.

This has been working for the majority of the states so far, and we could _perhaps_ improve this by matching words without accents instead of substrings, but it's hard to tell if other matches which are currently working wouldn't start breaking.

I believe this is a much broader fix that needs to be addressed in WC instead of keeping up with these small fixes here and there in payment gateways.

I suggested a [possible solution](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/568#issuecomment-790078365) in issue #568, which is strictly related IMO.

**Comment by v18** [comment] 2021-03-04 02:12
Thank you @ricardo!

> I believe this is a much broader fix that needs to be addressed in WC instead of keeping up with these small fixes here and there in payment gateways.

Do you have some idea about what should be done?

**Comment by ricardo** [comment] 2021-03-04 02:27
> Do you have some idea about what should be done?

@v18 as I suggested in #568, I think at least we should have a way to retrieve a list of untranslated states from WC.

But it would be amazing if we could retrieve a list from core that is not translated and is compatible with [libaddressinput](https://github.com/google/libaddressinput) (this is the address library used by Chrome) - many plugins would benefit from that as we have implementations of the Payment Request API across many different plugins, and all these plugins will have the same issues with Chromium browsers and the states WC supports.

**Closed** 2021-04-07 17:04 UTC
Labels: bundle: payment request buttons, component: payment request buttons, priority: high, type: bug
