### ISSUE TITLE
Quantity Changes Not Detected by Payment Requests Button on Themes with Increment/Decrement Buttons

### ISSUE THREAD

**Issue by MachineITSvcs** [woocommerce/woocommerce-gateway-stripe#1579] opened 2021-05-24 04:40 UTC
**Is your feature request related to a problem? Please describe.**
This plugin's payment request buttons do not work well with themes that utilize the quantity increase/decrease buttons (outside the quantity input field, not the tiny step buttons in the field available on number inputs nowadays). When these buttons are used on affected themes, it does not trigger a refresh of the payment request button, so even though the quantity changes in the "form" (on the product page), the payment request button does not get this new quantity. 

**Describe the solution you'd like**
Possibly added javascript code to detect field change in these situations.

**Describe alternatives you've considered**
I have attempted to contact the theme developers but they insist that this is a plugin issue. And I've contacted plugin support and they insist this is a theme issue, even though it affects multiple themes. I'm using 4 affected themes from different authors/developers that utilize these quantity buttons outside the field.

**Comment by v18** [comment] 2021-05-25 07:02
Hey @MachineITSvcs - thank you for opening this issue 🙌 Could you tell me which themes you tried this with and saw this problem? We'll take a look.

**Comment by MachineITSvcs** [comment] 2021-05-28 01:52
Hi @v18 I've seen this issue on several themes, but a few off the top of my head are Avada, Customify, and Responsive eCommerce. I can locate and include additional examples if necessary. I noticed today that this is not just limited to the Stripe gateway but also the Square gateway as well when digital wallets feature (payment request button equivalent of Stripe) is enabled. Neither of these payment processor plugins detect the changing quantity when the external quantity buttons are used, and therefore do not refresh the payment request button with the new quantity set.

**Comment by asumaran** [comment] 2021-06-21 04:15
> And I've contacted plugin support and they insist this is a theme issue

@MachineITSvcs Indeed, it seems the problem is in our side. The issue currently happens because the Payment Request button is not updated with the new information that comes from the backend after [adding the product to the cart](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/b31bead3a73d16d2edb9d3e9b5bcdd04274aba1c/assets/js/stripe-payment-request.js#L608). 

This will be fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1602. [Here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1602/files#diff-73c011ce1388f1432621c0fb207e47201e82f70fdf7e4a9b0d44eb47a9cb515bR539-R542) we can see we now update the Payment Request button with the info that comes from the backend after adding the product to the cart.

If all mentioned themes above use the standard input (`qty`) for quantity then most likely the issue will be fixed for all of them. Note: I've **only** tested with the `Customify` theme since Avada is a paid theme. 

I'll add this issue to #1563 to keep an eye on this once #1602 is merged.

**Closed as completed** 2022-07-14 02:15 UTC
Labels: component: payment request buttons
