### ISSUE TITLE
Stripe charge shows as completed but not charged

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#2352] opened 2022-05-16 19:01 UTC
**Describe the bug**

Customer paid order 55205 but Stripe charged the customer for order 54777 (the previous successful order which the customer placed on the site).

The order amounts differ, because the customer edited their subscription. The Stripe amounts do not.

Order 55205 is marked as complete, but payment was never received.

**Additional context**

According to the logs, a payment intent set up on 7 April for an order that subsequently failed was re-used on April 27, resulting in the 'old' order values being used for the new order payment after the customer made some attempts to pay.
The error `[code] => payment_intent_unexpected_state` was returned with the values from the old order, which where then subsequently picked up and reused, allowing the customer to place and pay for the "wrong" order.

It looks like an issue with Stripe and Subscriptions.

We have gained access to the database, and can put together a fairly complete history of the transaction.
- April 7. A parent order is placed, fails once, and then succeeds.
- April 24. After editing the subscription, the customer pays a manual renewal. The renewal order and parent order carries identical Stripe meta data
- The cart hashes do not match
- The payment request is made using the same pi_ as was created on April 24.
- Stripe responds correctly with the data from that `pi_` and gives the error:
   ```
    [code] => payment_intent_unexpected_state
    [doc_url] => https://stripe.com/docs/error-codes/payment-intent-unexpected-state
    [message] => This PaymentIntent's payment_method_types could not be updated because it has a status of succeeded. You may only update the payment_method_types of a PaymentIntent with one of the following statuses: requires_payment_method, requires_confirmation, requires_action.
    ```
- The response carries a successful outcome - for the previous order
- The current, unpaid order, is marked as complete.

Looks like a failure to remove Stripe metadata from the renewal order, but apart from that, the current order should possibly not have been updated to complete in view of the response.

Two questions arise:
- Why did the Stripe meta not get successfully removed
- Should there be an additional check before an order is marked as paid when receiving a response such as the one above.

Details and logs are linked in the ticket: 5164347-zd-woothemes

**Environment (please complete the following information):**
 - WordPress Version: `5.9.3`
 - WooCommerce Version: `6.4.1`
 - Stripe Plugin Version: `6.3.0`
 - Browser [e.g. chrome, safari] and Version: 
 - Any other plugins installed:

**Comment by EvanDotPro** [comment] 2022-09-01 16:45
After multiple attempts, we've unfortunately been unable to reproduce this on our end. If any further information or specific steps on how to reliably reproduce this can be provided, that would be very helpful and allow us to proceed.

**Comment by EvanDotPro** [comment] 2022-09-29 17:32
Closing this for now as we've been unable to reproduce. We'll be happy to revisit this if we can get more information so that we can reproduce the issue.

**Closed as completed by EvanDotPro** 2022-09-29 17:32 UTC
Labels: type: support request, needs repro
