### ISSUE TITLE
Duplicate order notes and order emails with New Checkout Experience

### ISSUE THREAD

**Issue by AbhinavSakalle** [woocommerce/woocommerce-gateway-stripe#2451] opened 2022-10-07 06:01 UTC
**Describe the bug**

With the New Checkout Experience enabled in Stripe Advanced settings, customers and admin receive duplicate order emails. Order notes on the Edit Order page are also getting duplicated.

**To Reproduce**
1. Go to **WooCommerce > Settings > Payments > Stripe**
2. Enable the **New Checkout Experience** under **Advanced Settings**
3. Place an order (Live or Test)
4. The customer and admin will receive duplicate order emails and the order notes will also get duplicated.

**Expected behavior**

Once the payment is successful and the order is placed, both customers and admin should receive a single order confirmation email, and also the Order Notes section should not have duplicate entries.

**Screenshots**

* Duplicate Order Notes (Charge & Status Change): https://d.pr/i/QAQYiK
* Stripe Advanced Settings: https://d.pr/i/ZVwGvf

**Environment (please complete the following information):**

 - WordPress Version - 6.0.2
 - WooCommerce Version - 6.9.4
 - Stripe Plugin Version - 6.8.0
 - Browser [e.g. chrome, safari] and Version - Not relevant
 - Any other plugins installed - WooCommerce

**Comment by AbhinavSakalle** [comment] 2022-10-07 06:02
Also reported in 5612750-zen

**Comment by thisissandip** [comment] 2022-10-07 06:20
@AbhinavSakalle This issue is already reported here: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2331

The workaround is to disable the new checkout experience.

**Comment by AbhinavSakalle** [comment] 2022-10-07 06:22
Good catch. Thanks @thisissandip

**Comment by thisissandip** [comment] 2022-10-11 12:48
Closing this as duplicate of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2331

**Closed as completed by thisissandip** 2022-10-11 12:48 UTC
