### ISSUE TITLE
Subscription renewal fails when shipping charge of the recurring payment is different than the parent order.

### ISSUE THREAD

**Issue by Mayisha** [woocommerce/woocommerce-gateway-stripe#3394] opened 2024-08-29 17:24 UTC
**Describe the bug**
India issued cards need e-mandate setup for payment. 
Renewal fails when the shipping charge of the subscription order and the recurring order are different. Suppose the subscription price is 1000, the initial shipping charge is free and the recurring shipping charge is 20. Then it fails with the following error-

```
payment_intent_mandate_invalid This mandate can only be used for a payment of 12000. You attempted a payment of 10000.
```

**To Reproduce**

- Connect to an Indian Stripe account.
- Set your store currency to INR.
- Go to **WooCommerce > Settings > Shipping** and add 2 shipping methods having different amount (e,g free => 0 and flat rate => 20 INR)
- Install the [WooCommerce Subscription](https://woocommerce.com/products/woocommerce-subscriptions/) plugin and create a subscription product worth 1000 INR.
- As a shopper add the subscription product to your cart.
- Choose free shipping for initial shipment and flat rate for recurring shipment.

<img width="795" alt="Screenshot 2024-08-29 at 11 14 53 PM" src="https://github.com/user-attachments/assets/ef282acc-d9ab-435d-bbb6-aa08953fd288">

- In the payment section use a card from [Indian recurring payment](https://docs.stripe.com/india-recurring-payments?integration=paymentIntents-setupIntents#testing)(e.g `4000003560000123`) and complete the checkout.
- Wait for 2 minutes before renewal because it takes a couple of minutes on the Stripe end for the mandate to be active.
- Now go to the edit subscription page. From the dropdown select `Process renewal`.
- Notice that the renewal order fails.
- Check the logs in your Stripe dashboard (https://dashboard.stripe.com/test/logs) or in your admin dashboard **(WooCommerce > Status > Logs**

**Expected behavior**
- If needed a new mandate should be created.
- The renewal should be successful.

**Comment by annemirasol** [comment] 2024-09-19 19:31
> Wait for 2 minutes before renewal because it takes a couple of minutes on the Stripe end for the mandate to be active.

@Mayisha Is there a way to know if the mandate is already active?

**Comment by annemirasol** [comment] 2024-09-19 20:44
> > Wait for 2 minutes before renewal because it takes a couple of minutes on the Stripe end for the mandate to be active.
> 
> @Mayisha Is there a way to know if the mandate is already active?

Found a way using CLI: `stripe mandates retrieve <mandate id>`

**Comment by annemirasol** [comment] 2024-09-19 22:06
I am unable to reproduce this: I always get the correct amount for the subscription renewal charge (e.g. 1200 with shipping, instead of 1000 free shipping).

I also tried to get charge mismatches using fixed/recurring coupons, but the renewal charge matches the mandate amount.

**Comment by annemirasol** [comment] 2024-12-26 17:07
Unable to repro this issue, possibly fixed by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3359. Closing this issue for now. Please re-open if issue persists.

In my testing, mandate amount correctly matches the recurring payment amount, i.e. 1000, and not the initial charges amount, i.e. 1200:
<img width="600" alt="Image" src="https://github.com/user-attachments/assets/44e51c4e-d78a-434c-a80a-d59ac8f59583" />

**Closed as completed by annemirasol** 2024-12-26 17:07 UTC
Labels: type: bug, priority: medium
