### ISSUE TITLE
Ensure correct saved payment methods are shown

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1047] opened 2019-10-11 13:57 UTC
Steps:

1. Add a bunch of new payment methods using the page `mysite.com/my-account/add-payment-method/`
2. Remove some of the payment methods using the 'delete' button
3. See that they stick around, and are not correctly removed from 'my-account'. However, they are correctly removed from Stripe.

These reproduction steps do not always work. Sometimes I am able to correctly remove a payment method, and other times I'm not.

h/t @tommyshellberg  p7bbVw-3oc-p2#comment-8403

**Comment by thenbrent** [comment] 2023-08-10 04:35
Closing this due to lack of recently activity the last 3 years. It sounds like a serious issue if present, meaning I'd have expected to see more reports via support. If it's still an issue, we can reopen and/or create new issues with more information to reproduce and fix.

**Closed by thenbrent** 2023-08-10 04:35 UTC
Labels: priority: low, type: bug
