### ISSUE TITLE
Checkout: Browser Viewport Change Unmounts Stripe Elements Fields

### ISSUE THREAD

**Issue by ianmcqueen** [woocommerce/woocommerce-gateway-stripe#978] opened 2019-08-28 18:41 UTC
There appears to be an issue where Stripe Elements fields are unmounted for viewports <870px. In my case, it's basically affecting mobile devices and tablets.

**WC Stripe Gateway Version:** 4.2.3

### What I expected

I expect that Stripe Elements fields will remain mounted, regardless of viewport size.

### What happened instead

Stripe Elements were unmounted when there's a viewport change to ~<870px.

### Steps to reproduce the issue

1. Add a product to your cart by clicking **Buy Now** on https://epicsoundeffects.com/quantum-sound-effects/
2. Navigate to the checkout: https://epicsoundeffects.com/checkout/
3. Select **Credit Card** as your payment method (i.e. Stripe)
4. Ensure that your viewport is ~>=870px, fill out a Stripe Elements field, it works fine
5. Adjust your browser viewport to ~<870px
6. Stripe Elements fields have been unmounted, Stripe payment fields are essentially blank/empty

### In browser dev tools

Viewport >870px: https://cl.ly/3b99be1f9c8e
Viewport <=870px: https://cl.ly/5510bb14f9ee

**Comment by v18** [comment] 2021-03-04 02:52
I'm not able to reproduce this issue, so I'm closing this.

**Closed by v18** 2021-03-04 02:52 UTC
Labels: priority: low, type: bug
