### ISSUE TITLE
Processing a failed subscription payment php errors and incorrect order notes

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce-gateway-stripe#247] opened 2017-05-05 07:12 UTC
#### Affected ticket(s)
https://woothemes.zendesk.com/agent/tickets/567914
569260-zd-woothemes

#### What I expected

When a failed renewal order is payment is processed I expected the order status to be set to failed with standard order notes to explain that. 

#### What happened instead

Order status is transitioned from pending to on-hold and then to failed and capture and authorise order notes are added. 
![lvaljnf5x5-1200x1200](https://cloud.githubusercontent.com/assets/8490476/25736119/3cd79970-31b3-11e7-8526-7f0d7e47c403.png)
https://cloudup.com/cxivFla7kZC

Capture payment immediately is enabled https://cloudup.com/ckz3jLKlSAU

Locally I'm also receiving the following errors: 

```
PHP Notice:  Undefined property: WP_Error::$id in /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 853
PHP Notice:  Undefined property: WP_Error::$captured in /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 854
PHP Notice:  Undefined property: WP_Error::$captured in /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 866
PHP Notice:  Undefined property: WP_Error::$id in /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 874
PHP Notice:  Undefined property: WP_Error::$id in /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 880
PHP Notice:  Undefined property: WP_Error::$id in /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 881
```
#### Steps to reproduce the issue
If you already have a subscription setup with Stripe already go to step 2

1. Purchase a subscription product
2. Go to the WP admin dashboard and navigate to **WooCommerce > Subscriptions**
3. Edit the subscription 
4. Edit the billing details and tweak the Stripe customer and card IDs to force a failure (https://cloudup.com/cZjSGGCJ8Gl)
5. From the subscription actions dropdown process a renewal payment (https://cloudup.com/cNiqWhI22_9)
6. Scroll down to the related orders and view the newly created renewal order
7. Notice the order notes are representative of authorise and capture being enabled when it's not. (https://cloudup.com/cJ0stvC78Uu)

The extra status transition (pending to on-hold to failed) is causing extra subscription related emails to be sent which is what this ticket is reporting. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment] 2017-05-11 01:49
Hi @james-allan - So here is what I am seeing ![](http://cld.wthms.co/mNeDa+) From this, are you saying the order "should not" go to "on-hold"?

**Comment by delythchandler** [comment] 2017-05-12 09:57
We are having a similar problem, but on our site https://woodpeckerflooring.co.uk if you order say for eg 6 samples of wood flooring, the first 3 are free, and following ones are charged at £1 each.

When you process the order, the admin receives firstly a failed order notification, then immediately afterwards an order received notification, and the order is changed from pending to processing.

Any ideas?

**Comment by madeincosmos** [comment] 2017-05-15 11:59
@roykho what you've attached are subscription notes, as compared with the renewal order notes added by @james-allan. Subscription being put on-hold is a standard part of the renewal process. As the next step, it creates a renewal order and tries to collect the payment. Clicking on the order number in subscription notes will take you to the order page and let you see the incorrect status flow:

![Screenshot](http://cld.wthms.co/3pD6N+)
Screenshot: http://cld.wthms.co/3pD6N

As far as I understand, the failed payment response from Stripe is not processed correctly here, and this unhandled error puts the renewal order **On hold** for a short while, triggering a **New subscription renewal order** email that should not be sent when the payment has failed.

Just reproduced the same behaviour on my Pressable site, with WooCommerce 3.0.6, Subscriptions 2.2.6 and Stripe 3.1.8.

**Comment by thenbrent** [comment] 2017-05-15 16:56
> are you saying the order "should not" go to "on-hold"?

@roykho yes that's correct. If the payment fails, the order's status should be changed to _failed_.

The issue appears to be that [this block](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/36d6c71f1f/includes/class-wc-gateway-stripe.php#L869:L885) assumes there are only two possible outcomes in the charge response:

1. a captured charge; or
1. an authorised charge.

There are 3, the third being a _failed_ attempt to charge, which is not being handled. This needs to be accounted for, similar to the way it is handled for [pre-orders](https://github.com/woocommerce/woocommerce-gateway-stripe/blame/36d6c71f1f/includes/class-wc-gateway-stripe-addons.php#L234:L244).

**Comment by SiR-DanieL** [comment] 2017-07-27 07:12
@roykho looks like we still have an issue with this in #600588-zen.

This fix was included in Stripe 3.1.11, right?

**Comment by roykho** [comment] 2017-07-27 13:35
@SiR-DanieL yes it was included.

**Comment by majdagithub** [comment] 2017-11-16 13:46
I have this problem with the newest version of WooCommerce Stripe Payment Gateway plugin (3.2.3). 

First, recurring payment was failed due to credit card expired. Customer changed her credit card data via My-account->Payment method and set it as default. Then I (admin) triggered Retry Renewal Payment on failed order and everything went well. 

Now, after one month, subscription recurring payment triggered again and this time it was failed due to insufficient funds. But admin got "New subscription renewal order" email instead of "Automatic payment failed" email. The next retry triggered 12 hours afterwards and that time "Automatic payment failed" email was sent to admin. 

These are Order notes:

Stripe Transaction Failed (Your card has insufficient funds.) Order status changed from On hold to Failed.
added on November 15, 2017 at 11:25PM Delete note
Retry rule applied: Order status changed from Failed to Pending payment.
added on November 15, 2017 at 11:25PM Delete note
Stripe charge authorized (Charge ID: ). Process order to take payment, or cancel to remove the pre-authorization. Order status changed from Pending payment to On hold.
added on November 15, 2017 at 11:25PM Delete note
Stripe Transaction Failed (Your card has insufficient funds.) Order status changed from On hold to Failed.
added on November 15, 2017 at 11:25AM Delete note
Retry rule applied: Order status changed from Failed to Pending payment.
added on November 15, 2017 at 11:25AM Delete note
Stripe charge authorized (Charge ID: ). Process order to take payment, or cancel to remove the pre-authorization. Order status changed from Pending payment to On hold.
added on November 15, 2017 at 11:25AM Delete note

What I do not understand is that order notes for 15th November and 16th November are the same and admin got "New subscription renewal order" email on 15th November and "Automatic payment failed" email on 16th November (after 12 hours). 

We had failed recurring payments in past (without need for changing credit card data) and everything went well (admin got correct email). The only change is that now we had credit card data change before and we updated your plugin from 3.1.9. to 3.2.3. version...

Please reply

**Comment by roykho** [comment] 2017-11-24 22:32
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/aded182f1e230c99e8853c3c94421259540b926d

**Closed by roykho** 2017-11-24 22:32 UTC
Labels: [Pri] High, [Type] Bug

**Comment by majdagithub** [comment] 2017-11-27 09:01
Can you please provide a solution for the newest version of Stripe plugin (3.2.3), considering that this fix cannot be included within new version because there is no "compat" folder within "includes" folder anymore?!

**Comment by majdagithub** [comment] 2017-11-28 08:05
@roykho any answer?
