### ISSUE TITLE
3DS Source not charged if redirect_status == not_required

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-stripe#706] opened 2018-08-01 11:27 UTC
#### Affected ticket(s)
ticket: 1276242-zen

#### What I expected
Using `add_filter( 'wc_stripe_require_3ds', '__return_true' );` I would expect all cards that suppport 3D Secure to have their 3DS source charged and a liability shift.

#### What happened instead
Cards that have the redirect_required attribute set to not_required do not have their 3D Source charged.

#### Steps to reproduce the issue
1. Implement `add_filter( 'wc_stripe_require_3ds', '__return_true' );`
2. Checkout with a card that supports 3DS but is optional and would not require a redirect.
3. 3DS Source not charged, no liability shift.

There is an example of one of these types of transactions in the ticket referenced. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by madeincosmos** [comment] 2018-08-08 09:24
@thorsten-stripe can you please take a look? As far as I understand from Stripe API docs and #647, 3DS source with `redirect.status` `not_required` should not get redirected to 3D Secure. However, according to the info this user got from Stripe support, it should still be possible to charge the 3D Secure source created in the process even without the redirect.

Looking at the plugin code, I can see that currently:

- If 3DS source `redirect.status` is `pending`, there is a redirect:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.1.8/includes/class-wc-gateway-stripe.php#L747:L752

- In every other case (3Ds not supported, `redirect.status` different than `pending`, etc) we're charging the original `$prepared_source`, which is not a 3DS source:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.1.8/includes/class-wc-gateway-stripe.php#L766

Can you please confirm how we should proceed with 3DS sources that have `not_required` status? Should we charge this source directly without the redirect, or use the original `$prepared_source` as we do right now?

**Comment by jm-cm** [comment] 2018-08-08 09:42
A key issue with this is that when a payment starts down the 3D Secure pathway, the final payment should not lose all trace of what has happened. There should be a response shown.

What is particularly vital is that these transactions, for the sake of the merchant and for Stripe, should be covered by the liability shift. 
However because of the way the plugin currently charges the original non 3D Secure source this liability shift is lost, when it should not be.

Stripes wording in regards to the API was this:

> I know what the API library says, but as I mentioned before that documentation has to take into consideration other payment methods too. 
>
> With 3DS sources, when the redirect is not required, the source immediately transitions to 'source:chargeable'. If you want to benefit from the liability shift, you need to charge this 3DS source. Abandoning the process to charge the original card source doesn't make sense. 
>
>**So, the answer to their question about how to handle the redirect.status "not_required" in terms of sources, is charge the 3DS source.** 
>
>If WooCommerce have specific examples where this process doesn't work, please feel free to send them over!

**Comment by madeincosmos** [comment] 2018-08-20 06:54
@thorsten-stripe did you have a chance to look into this?

**Comment by jm-cm** [comment] 2018-08-21 12:37
Any updates on this? It is a common problem for us.

**Comment by thorsten-stripe** [comment] 2018-08-21 16:39
Sorry for the delay, I was OOO.

There is a scenario where liability shift takes place without a redirect:
Liability shift can also occur if the card or issuer isn't enrolled in 3D Secure but the type of card could support 3D Secure (e.g., most Visa and Mastercard consumer cards). During the payment process, the cardholder isn't redirected to complete 3D Secure verification, since the card is not enrolled. Instead, the value of `redirect.status` automatically transitions to `succeeded`, though the value of `three_d_secure.authenticated` is `false`. Although the cardholder did not complete 3D Secure authentication, liability still shifts to the issuer.

We're currently overhauling the docs to make that clearer, sorry for the confusion. 

So yes, as long as the 3D Secure source is chargeable it makes sense to default towards charging that.

**Comment by madeincosmos** [comment] 2018-08-22 07:17
Thanks for the explanation, @thorsten-stripe! So as far as I understand, we can charge 3D Secure source without redirecting the customer to 3DS if the `redirect.status` of the source is `succeeded`, and this will qualify for liability shift.

Does the same scenario hold for sources with `redirect.status: not_required`, or is there something we should do differently in this case?

**Comment by jm-cm** [comment] 2018-08-23 14:38
It looks like it would be covered in the last line 

> So yes, as long as the 3D Secure source is chargeable it makes sense to default towards charging that.

Which agrees with what Stripe communicated originally. 

Direct clarification would be good.

This issue was delayed well over a month almost 2 trying to get it to be recognised as an issue, a speedy resolution of an issue that regularly impacts us would be appreciated.

**Comment by thorsten-stripe** [comment] 2018-08-28 14:31
Sorry about that, my bad. This was changed a good while ago: https://stripe.com/docs/upgrades#2017-08-15

So the above text holds true but since API version 2017-08-15 redirect.status is set to not_required instead of succeeded.

So in the case where redirect status is no_required and the source is in a chargeable state you should default to charging the 3DS Source which will then also be covered by the liability shift.

**Comment by jm-cm** [comment] 2018-08-29 08:53
@thorsten-stripe thank you for the clarification.

@WillBrubaker  @madeincosmos  it is now way over 2 months since this issue was flagged up; there is now direct clarification from Stripe, again, on how to handle this scenario that was not a bug but incorrectly handling of a scenario, please can we get an eta on resolving this soon.

**Comment by madeincosmos** [comment] 2018-08-29 11:59
@roykho can we get your eyes on this? We'll probably need to add an 'else' case here, and replace the originally prepared source with the 3DS one:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.1.8/includes/class-wc-gateway-stripe.php#L746:L753

**Comment by roykho** [comment] 2018-08-29 13:40
cc @laurendavissmith ^

**Comment by roykho** [comment] 2018-09-07 03:51
Ok so I've made some changes which will charge the 3DS source when redirect status is "not_required". However I am not able to test this because there are no testing cards that will simulate a "not_required" redirect AFAIK.

So if you can, please test this branch out https://github.com/woocommerce/woocommerce-gateway-stripe/tree/issue-706

**Comment by thorsten-stripe** [comment] 2018-09-07 10:28
@roykho sorry, the docs have not been updated to the fact, but the standard `4242424242424242` card follows this flow.

**Closed** 2018-09-07 21:51 UTC
Labels: [Pri] Low, [Type] Bug

**Comment by jm-cm** [comment] 2018-09-19 08:44
It appears the issue persists

`"three_d_secure": "optional"`

response
`"status": "not_required"`

whilst having 

`add_filter( 'wc_stripe_require_3ds', '__return_true' );`

Resulted in the 3D Secure source not being charged, and instead the regular source is charged.

**Comment by roykho** [comment] 2018-09-19 13:09
I am not seeing any issues here. Using card 4242424242424242 and with `add_filter( 'wc_stripe_require_3ds', '__return_true' );` we will see the 3DS come back with status `not_required`. Then it will check if the 3DS source is chargeable. If it is, then change the original source with the 3DS source and charge that. I then go to my Stripe dashboard and can confirm the 3DS source was charged and not the original.

**Comment by LaurenaRehbein** [comment] 2018-09-19 19:11
@roykho I am also testing with `add_filter( 'wc_stripe_require_3ds', '__return_true' );` and using card 4242424242424242. In the Stripe dashboard, I am seeing that 3D was NOT verified with 3D secure, and `"three_d_secure": "optional",` in the log.

**Comment by roykho** [comment] 2018-09-19 20:46
@LaurenaRehbein - please check your Stripe dashboard API version and make sure you're using latest or a version after this date 2017-08-15

**Comment by LaurenaRehbein** [comment] 2018-09-19 20:48
@roykho yes, I am: 

 ![http://cld.wthms.co/W8zn5x](http://cld.wthms.co/W8zn5x+)
Full Image: http://cld.wthms.co/W8zn5x+

**Comment by roykho** [comment] 2018-09-19 21:11
@LaurenaRehbein yeah strange I am not seeing that issue on my end however I have pushed up a change where I explicitly set the 3DS source id to the charged source to see if that helps on your end. Please test master.

**Comment by LaurenaRehbein** [comment] 2018-09-19 21:17
@roykho yes, testing Master, with `add_filter( 'wc_stripe_require_3ds', '__return_true' );` on the site, I now see this: 

![http://cld.wthms.co/DzLj34](http://cld.wthms.co/DzLj34+)
Full Image: http://cld.wthms.co/DzLj34+
