### ISSUE TITLE
The 'wc_stripe_payment_metadata' filter doesn't work with UPE

### ISSUE THREAD

**Issue by S-Simon** [woocommerce/woocommerce-gateway-stripe#2855] opened 2024-01-25 15:10 UTC
**Describe the bug**
Perhaps this is known/intentional for now, but the `wc_stripe_payment_metadata` filter doesn't work when the updated checkout experience is enabled. It works when it's disabled.

**To Reproduce**
Add this to the active theme's `functions.php`:
```
add_filter( 'wc_stripe_payment_metadata', 'stripe_payment_metadata_filter_callback', 10, 3 );
function stripe_payment_metadata_filter_callback( $metadata, $order, $prepared_source ) {

    $metadata[ __( 'testKey', 'woocommerce-gateway-stripe' ) ] = 'testValue';

    return $metadata;
}
```

**Expected behavior**
The filter should work the same way as when UPE is disabled, it should modify the payment metadata sent to Stripe.

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version: 6.4.2
 - WooCommerce Version: 8.5.1
 - Stripe Plugin Version: 7.9.1
 - Browser [e.g. chrome, safari] and Version: All, used chrome Version 120.0.6099.234 (Official Build) (arm64)
 - Any other plugins installed: no

**Additional context**

**Comment by Nicscott01** [comment] 2024-03-25 22:54
I've experienced the same issue.

**Comment by tarkan123** [comment] 2024-04-02 16:56
Just seen this is issue - I opened a issue #[3021].

I have found the following hook that works with the new UPE to inckude custom / modified metadata.

add_filter('wc_stripe_intent_metadata', 'your_payment_metadata_function', 10, 2);

function your_payment_metadata_function ($metadata, $order) {

}

**Comment by adam-adapt** [comment] 2024-05-22 12:16
I can confirm that the `'wc_stripe_payment_metadata'` filter does **NOT** when using the New Checkout Experience.

Woo has [this article](https://woocommerce.com/document/stripe/customization/products-as-metadata/) that provides an example on how to send metadata to Stripe using `'wc_stripe_payment_metadata'`. As stated, this no longer works when switching to the New Checkout Experience.

This needs to be fixed before the old checkout experience is deprecated.

(Using the` wc_stripe_intent_metadata `filter instead does NOT work.)

**Comment by adam-adapt** [comment] 2024-05-22 12:31
Can we get @thenbrent, @diegocurbelo, @a-danae  or someone to look at this?

**Comment by tarkan123** [comment] 2024-05-22 20:29
I am using 'wc_stripe_intent_metadata' with no issues since switching to the New Checkout Experience.

**Comment by a-danae** [comment] 2024-07-14 17:08
Hey 👋  Thanks for the reports here!

We currently have two different filters for the payment metadata depending on the checkout experience in use:
- `wc_stripe_intent_metadata` if you’re using the updated checkout experience
- `wc_stripe_payment_metadata` if you’re using the legacy experience

The article [How can I send product details to Stripe as metadata?](https://woocommerce.com/document/stripe/customization/products-as-metadata/), mentioned by @adam-adapt above, has been updated. It now references both filters and for what experience they'd run.

I have tested the following snippet and can confirm both filters work:

```
// For the Legacy checkout experience.
add_filter( 'wc_stripe_payment_metadata', 'wc_stripe_payment_metadata_filter_callback', 10, 3 );
function wc_stripe_payment_metadata_filter_callback( $metadata, $order, $prepared_source ) {

	$metadata[ 'customFilter' ] = 'wc_stripe_payment_metadata';

	return $metadata;
}
```

```
// For the updated checkout experience.
add_filter( 'wc_stripe_intent_metadata', 'wc_stripe_intent_metadata_filter_callback', 10, 2 );
function wc_stripe_intent_metadata_filter_callback( $metadata, $order ) {

	$metadata[ 'customFilter' ] = 'wc_stripe_intent_metadata';

	return $metadata;
}
```

I'm closing this issue since this behavior is intentional. But please feel free to open a new one if you find any problems when using these filters. All the details and replication steps you could provide in those would be of great help to us. And thanks again for reaching out to us about this 🙂

**Closed as completed by a-danae** 2024-07-14 17:08 UTC
