### ISSUE TITLE
Upgrade 'Tested up to WooCommerce version' number

### ISSUE THREAD

**Issue by rolandog** [woocommerce/woocommerce-gateway-stripe#1150] opened 2020-03-23 10:28 UTC
**Describe the bug**
Possibly related to #1148; when trying to upgrade from WooCommerce 3.9.2 to 4.0.1, I'm greeted with a warning that _WooCommerce Stripe Gateway_ has only been tested up to WooCommerce 3.9.2. 

**To Reproduce**
1. Visit `https://example.com/wp-admin/plugins.php` (with similar setup as described below)
1. Scroll to 'WooCommerce'
1. View following information:

> Heads up! The versions of the following plugins you're running haven't been tested with WooCommerce 4.0. Please update them or confirm compatibility before updating WooCommerce, or you may experience issues:
> Plugin | Tested up to WooCommerce version
> -- | --
> WooCommerce Stripe Gateway | 3.9.2

**Expected behavior**
Able to upgrade without uncertainty of compatibility.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - WordPress Version: 5.3.2
 - WooCommerce Version: 3.9.2
 - Stripe Plugin Version: 4.3.2
 - Browser [e.g. chrome, safari] and Version: Firefox 75.0b6 (64-bit)
 - Any other plugins installed: N/A (but I'll list them if requested)

**Additional context**
N/A

**Comment by thenbrent** [comment] 2020-03-24 01:15
Hi @rolandog, thanks for reporting. This will be addressed in the next version of the plugin with #1123.

**Comment by allendav** [comment] 2020-03-27 20:32
Closing as duplicate of #1123

**Closed by allendav** 2020-03-27 20:32 UTC
