### ISSUE TITLE
Issues changing settings with v8.2.0

### ISSUE THREAD

**Issue by pjrobertson** [woocommerce/woocommerce-gateway-stripe#3104] opened 2024-04-30 09:01 UTC
**Describe the bug**
1. In the Stripe payment settings, if I change settings then click 'save' the page does not reflect my updated settings. See the video below.

**Screenshots**

https://github.com/woocommerce/woocommerce-gateway-stripe/assets/150431/afd38f07-20bc-4191-81c0-42f7063401e0

**Environment (please complete the following information):**
Wordpress: 6.5.2
Plugin: 8.2.0
WooCommerce:
Browser: Firefox & Chrome
Caching: Tried disabling, same

**Comment by wjrosa** [comment] 2024-06-07 21:33
Hey @pjrobertson! I cannot reproduce this issue in the latest version of the extension. Can you try updating it and checking if it still happens for you?

**Comment by wjrosa** [comment] 2024-06-25 14:03
I will be closing this issue now @pjrobertson . Let us know if it still happens to you and we can re-open this.

**Closed as completed by wjrosa** 2024-06-25 14:03 UTC
Labels: type: bug
