### ISSUE TITLE
Validation / Flow Problem

### ISSUE THREAD

**Issue by ApplicationError** [woocommerce/woocommerce-gateway-stripe#243] opened 2017-04-27 16:25 UTC
We still have a validation flow problem with the Stripe extension. The extension should check if the email address belongs to an existing customer before presenting the Stripe payment modal.

Steps to reproduce:

Note: Don't be signed in

1.) Add item to cart
2.) Proceed to checkout
3.) Enter details (email) of an existing customer
4.) Choose Stripe and enter valid details -> Submit

Result:
The Stripe modal indicates a successful transaction
After the modal disappears and error message is shown on the checkout page
Error: An account is already registered with your email address. Please login.

Problem:
Customers believe they paid already / their card was charged (when it wasn't)
This results in (a) customers contacting us, arguing they paid, (b) revenue loss, (c) upset people

**Comment by edie-etoile** [comment] 2017-04-27 16:48
+1 We believe that this has happen to us as well.

**Comment by ApplicationError** [comment] 2017-04-27 21:46
I don't think this will help much, but here is a screenshot of my Stripe settings. These are identical to our production settings (other than the API details).

![woocommerce-stripe-settings](https://cloud.githubusercontent.com/assets/26173192/25505793/b1c743e2-2b60-11e7-8fac-ce4c416f2c06.png)

**Comment by mikestern** [comment] 2017-05-17 02:43
+1 We have the same problem. Is there a fix for this yet? Thanks.

**Comment by ApplicationError** [comment] 2017-05-17 13:57
@mikestern There is no fix yet. It has been a while since it was reported. I'm just surprised not more people are "reporting" this issue. It makes me wonder how many people actually use this extension.

**Comment by ApplicationError** [comment] 2017-05-30 13:40
Not sure why this hasn't been fixed it. It's terrible.

**Comment by leehuffman** [comment] 2017-06-14 23:37
This is a duplicate of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/161.

I'm also experiencing this same issue. I have a function hooked onto `woocommerce_checkout_process` that validates a checkbox is checked. This validation isn't triggered until after the Stripe modal is submitted leading to a really confusing UX.

@roykho I noticed you mentioned in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/161 that other fields are being validated properly and you're 100% correct. All the default WooCommerce fields are validated _before_ the Stripe modal is rendered. I even get the error message for my custom checkbox along with WooCommerce's when one of those default fields isn't filled. It's only when all of WooCommerce's standard fields pass validation and you have custom fields that need checked that this problem appears.

If there's anything else I can provide please let me know.

**Comment by leehuffman** [comment] 2017-06-15 06:08
Since the bug referenced above is outside the scope of this code change and is already affecting us on our Will Call Name validation, I'm going to go ahead and push it out.

**Comment by ApplicationError** [comment] 2017-06-16 14:53
Hey @leehuffman. This is a duplicate. WooCommerce or the WooCommerce Slack community had recommended that I open another issue - in case the first issue was missed. I don't think this extension is supported or updated anymore. This issue has been around since I installed the extension - it's really strange that no-one had stepped up and fixed this. 

We'll probably create our own copy and fix this.

**Comment by leehuffman** [comment] 2017-06-22 19:18
> I don't think this extension is supported or updated anymore.

It looks like @roykho responded as recently as May 19th in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/161 and the [latest commit](https://github.com/woocommerce/woocommerce-gateway-stripe/commit/e8a3dfb63077870208119c92568a498a27f548e7) is from 5 days ago. It's definitely still being managed & maintained.

> We'll probably create our own copy and fix this.

If you do fix this up, can you fork this repository and submit the PR? I'm sure if the fix is submitted we can get it included in the next release.

**Comment by roykho** [comment] 2017-07-21 14:45
Fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0

**Closed by roykho** 2017-07-21 14:45 UTC
Labels: [Pri] High, [Type] Enhancement

**Comment by ApplicationError** [comment] 2017-07-21 14:48
Wow, that took a long time to get fixed. Let's see when it will become available as "update" in WP.

**Comment by leehuffman** [comment] 2017-07-24 18:12
> Fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0

Thank you, @roykho!
