### ISSUE TITLE
Restock refunded items does not work

### ISSUE THREAD

**Issue by fanny-stahl** [woocommerce/woocommerce-gateway-stripe#1134] opened 2020-02-10 15:13 UTC
**Describe the bug**

The Restock refunded items option when refunding an order does not work correctly. 

**To Reproduce**
1. Go to an order
2. Click on Refund order
3. Check the box "Restock refunded items"
4. Refund the order

The order is refunded correctly but the items are not restocked.

**Expected behavior**

The items of the order should be restocked if the option to do so is checked.

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version: 5.2.3
 - WooCommerce Version: 3.7.0
 - Stripe Plugin Version: 4.2.4
 - Any other plugins installed: Yes, and a fair amount. However, it's a multisite and the feature works on a different subdomain where we use a different payment gateway.

**Additional context**

**Comment by reykjalin** [comment] 2020-03-03 09:10
Hello @fanny-stahl!

We're aware of several customers having similar issues, but in all the reports I found that have been made in the past, this is because people are refunding an amount directly, and do not set a quantity for the product being refunded.
When refunds are processed that way the refund doesn't get attributed to a specific product in the order. That's likely why it wasn't restocked.

The way around that is to click the "refund" button as normal, and then use the quantity field next to the product that's being refunded to select the number of items that are being refunded. That should make sure the correct amount of items will be restocked.

![image](https://cdn-std.droplr.net/files/acc_566773/KcmGxC)

Please let us know here if this fixes your issue!

For maintainers; ticket with (probably) the same issue: 1211204-zen

**Comment by allendav** [comment] 2020-03-27 20:31
Closing for now. If we hear back or get another instance we can re-open.

**Closed by allendav** 2020-03-27 20:31 UTC
Labels: [Status] Needs Author Reply

**Comment by fbaio-dev** [comment] 2021-11-12 00:20
Hi,

I'm facing the same issue,  I followed the step-by-step described by Kristófer @reykjalin  but it still doesn't work on my side !

Please any fix for this issue?

I'm using the last version of woocommerce.

**Comment by reykjalin** [comment] 2021-11-12 23:40
@fbaio-dev can you please give us a step-by-step example of how this doesn't work as intended?

**Comment by fbaio-dev** [comment] 2021-11-13 00:33
@reykjalin, Here is what I did :

1- I have chosen one of my orders
2- I clicked on "Refund Order"
3- I have chosen the quantity  in my case it's "1"
4- I made sure I checked the box "Restock Refunded Items"
5- Then I clicked on "Refund The Order Via Stripe"


Here is the scenario from the beginning 👍 

1- Before The Purchase
<img src="https://i.imgur.com/uPK3Zu4.png" alt="Before The Purchase">

2- After the purchase
<img src="https://i.imgur.com/4Zoatct.png" alt="After the purchase">

3- Refunding
<img src="https://i.imgur.com/TfYyebd.png" alt="Refunding">

4- After the refund
<img src="https://i.imgur.com/i49lbvR.png" alt="After the refund">


The only solution I found, for now,  is to move the transaction into the trash once it's refunded, this reset the number of sales.

**Comment by reykjalin** [comment] 2021-11-13 01:12
I think the number of sales is something custom in your theme, or possibly provided by a plugin?

I don't think this is a problem with the Stripe gateway because:

1. The refunded item is correctly added back to the available stock (stock is changed from 9 to 10 after the refund).
2. The Stripe gateway doesn't have a way to display the number of sales for items.
3. Moving the order to the trash resets the number of sales.

In particular it's number 3 that has me convinced that this isn't a problem with the gateway. Whatever plugin, theme feature, or custom code you're using to show the number of sales just has to be changed to take into account refunded items in orders.

**Comment by fbaio-dev** [comment] 2021-11-13 22:21
@reykjalin, 

Thank you so much for pointing me to this,  I've been looking for a day in the wrong place :) 
I'll try to figure out what's the issue and I'll update you as soon as I found it.
