### ISSUE TITLE
Undefined index: statement_descriptor

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1006] opened 2019-09-24 16:02 UTC
**Describe the bug**

The following is logged if the descriptor setting is left blank

> PHP Notice:  Undefined index: statement_descriptor in /app/public/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php on line 1040

**To Reproduce**
1. WP_DEBUG true
2. Set the descriptor to an empty string in the gateway settings
3. Capture a payment
4. See the notice in the PHP logs

**Expected behavior**
No notice

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - Stripe Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**

**Comment by tommyshellberg** [comment] 2019-09-24 16:10
I would guess that a default here would be a good idea as a backup if the descriptor was left blank - perhaps the site title?

**Comment by dechov** [comment] 2019-09-24 20:02
Tracked in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/907 (though with lower priority).

**Comment by RadoslavGeorgiev** [comment] 2019-09-25 12:47
The issue is already fixed in the `sca-subs/master` branch through #962. There was even a small conversation about it: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/962/files#r317245517

Even though the code is not in `master` yet, the PR has been closed, so I'll close this issue too.

**Closed by RadoslavGeorgiev** 2019-09-25 12:47 UTC
Labels: Priority: High, [Type] Bug
