### ISSUE TITLE
International payment not going through

### ISSUE THREAD

**Issue by vangovagon** [woocommerce/woocommerce-gateway-stripe#1112] opened 2019-12-25 14:41 UTC
**Describe the bug**

international payments not going through while local are success

Issue:

Cross Border (international) Payments not going through

**Expected behavior**

international card payments should go through

**Screenshots**
![Screenshot_20191222-113814](https://user-images.githubusercontent.com/59228743/71447121-ddc89b00-2750-11ea-927e-6d808fa4eab8.png)
![Screenshot_20191222-120004](https://user-images.githubusercontent.com/59228743/71447129-ed47e400-2750-11ea-987b-9497d681f4a2.png)

**Environment (please complete the following information):**

 - Stripe Plugin Version -  by WooCommerce – 4.3.1
 - Browser [e.g. chrome, safari] and Version - chrome
 - Any other plugins installed - 

WordPress address (URL): https://www.vangovagon.com

WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Cron: ✔

**Comment by v18** [comment] 2020-01-07 05:14
Hi @vangovagon, thanks for opening this issue. Stripe doesn't send the `cross_border_classification` parameter by default, but since it's being sent with Stripe requests on your site I'm guessing that it's being sent by another plugin or code snippet.

Does this happen on your staging site as well? If so, I recommend trying to deactivate all other plugins on your staging site and then turning them back one by one each time try to re-create the issue to see which plugin causes it.

If you're not able to figure out the cause behind the problem, you can contact support about this. If you could send them the Stripe logs for a request that failed, that would help us figure out the problem. You can also send them a link to this issue so they have more context.

I'm going to close the issue here since it's not related to the default behaviour of this plugin.

**Closed by v18** 2020-01-07 05:14 UTC
