### ISSUE TITLE
[Affirm] Error message is displayed when payment is abandoned on the shortcode checkout

### ISSUE THREAD

**Issue by wjrosa** [woocommerce/woocommerce-gateway-stripe#3090] opened 2024-04-23 16:40 UTC
See: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3083#issuecomment-2071553976

<img width="1100" alt="324698377-20234e9b-e6d2-4ae5-ab23-aa03fd14baa7" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/10187816/65a626ce-4437-4a76-a7d2-63757d6251ee">

**Comment by james-allan** [comment] 2024-04-24 02:08
This was intended @wjrosa. This message is shown on the shortcode checkout after you fail/abandon completing the sign up at Stripe. The issue I was mentioning on the PR is that this is correctly shown on the shortcode checkout, but it's not shown on the block checkout. 

You've filed an issue for that here https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3089. I'm going to closing this it is intended.

**Closed as completed by james-allan** 2024-04-24 02:08 UTC
Labels: type: bug, priority: medium
