### ISSUE TITLE
Stripe Gateway sending partial data - Payment input screen is often truncated and cannot enter details

### ISSUE THREAD

**Issue by chelleons** [woocommerce/woocommerce-gateway-stripe#1344] opened 2020-10-28 10:58 UTC
**Describe the bug**

When a client hits send payment, this is the reply - It s not permanent, but happens to a few clients per day?
It has been going on for a long time. But as I say it is not permanent? Any ideas??????

GET /v1/customers/cus_HK05argNzRwcda/sources
200
Time
10/28/20, 10:26:39 AM
IP address
35.214.60.95
Version
2019-09-09
Source
WooCommerce Stripe Gateway/4.5.3 (https://woocommerce.com/products/stripe/)
Origin
https://api.stripe.com/
Request query parameters
{
  "limit": "100"
}
Request POST body
No POST body
Response body

**To Reproduce**
Only happens occasionally as if there is a 'connection' problem
**Expected behavior**
Orders are failing as this is the data being passed
**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version 5.4.2
 - WooCommerce Version 4.2.0
 - Stripe Plugin Version 4.5.3
 - Browser [e.g. chrome, safari] and Version ALL
 - Any other plugins installed

**Additional context**

**Comment by v18** [comment] 2021-02-26 06:30
Hi @chelleons - could you please add the steps to follow in order to reproduce this issue. For example - how does a client get to the page where they can hit "send payment"?

I also recommend contacting support about this so they can help you find the root cause & fix the issue.

I'm going to close the issue for now - please feel free to re-open when you reply.

**Closed by v18** 2021-02-26 06:30 UTC
Labels: priority: low
