### ISSUE TITLE
payment_intent.succeeded 500 error. API version 2022-11-15

### ISSUE THREAD

**Issue by spencernash** [woocommerce/woocommerce-gateway-stripe#2501] opened 2022-12-18 14:07 UTC
Priority: High
With the latest Stripe API (v2022-11-15). The payment_intent.succeeded webhook is different, removal of the charge object.

Replicate: Upgrading API version in Stripe or creating new account and using a card that requires 3D secure.

Error
You will get a 500 error in Stripe. Unless using the latest checkout experience the order will show as Pending/Cancelled in order dashboard.

**Comment by Babylon1999** [comment] 2022-12-23 16:46
Related forum discussion: https://wordpress.org/support/topic/problem-with-payment_intent-succeeded-webhook-event-and-latest-api/

**Comment by darcie** [comment] 2023-01-07 00:54
This appears to be a duplicate of #2488, which has a fix already. I'm going to close this as the changes in #2493 should resolve your error.

**Closed as completed by darcie** 2023-01-07 00:54 UTC
