### ISSUE TITLE
Redirect to /shop after pay

### ISSUE THREAD

**Issue by luispf39** [woocommerce/woocommerce-gateway-stripe#1868] opened 2021-09-16 07:56 UTC
Since February, when we updated WooCommerce Stripe Gateway plugin (then we have updated it again, but problem is still there), when some clients made their payment, they returned to /shop page insted confirmation page. So it is not happening always, only in some cases (when verification is required by customer's card issuer). We can’t replicate this on Stripe test mode, only when system is working in Real mode and only when verification is requiered.

After verification and payment, it redirects to /shop page. If card issuer doesn’t ask for a SMS or APP verification, everything works as expected and it redirects to the confirmation page. 

I’ve seen all URLs when return to /shop page had the “&wc-stripe-confirmation=1” parameter. Could be this a problem?

For example:

/pago/pay-for-order/2428/?pay_for_order=true&key=wc_order_fu55taPgFv7fp&wc-stripe-confirmation=1

Any idea how to fix this problem?

Until we updated the plugin on february, everything was working as expected. We have seen you made some updates and bugfixes related to SCA on 12 December 2020, maybe this could be related to our issue?

Thank you so much

**To Reproduce**
Any purchase that requieres a validation, so it can't be tested on Stripe Test Mode. 
Currently we are using 5.4.0 version of your plugin and Woocommerce version is 5.6.0.

**Comment by dougaitken** [comment] 2022-07-29 15:43
I appreciate some time has passed since the original comment, thanks for your patience. 

It is possible that this issue has been fixed by a more recent release as I’ve been unable to replicate the issue you described using the latest release of the core WooCommerce plugin and the [WooCommerce Stripe Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/). 

As I’m unable to reproduce this, I’m marking this Issue as Closed. Please do open a new one if you are able to reproduce this again.

**Closed as completed by dougaitken** 2022-07-29 15:43 UTC
Labels: needs repro
