### ISSUE TITLE
4.5.4 Broke my site 

### ISSUE THREAD

**Issue by eldritchgreene** [woocommerce/woocommerce-gateway-stripe#1371] opened 2020-11-17 02:33 UTC
Priority: CRITICAL (Can't figure out how to add the label)

The latest update completely broke my site, was unable to access backend even in safe mode. Got fatalerror message Had to downgrade to stop This is the log:

Error Details
=============
An error of type E_ERROR was caused in line 107 of the file /wp-content/plugins/woocommerce/includes/class-wc-data-store.php. Error message: Uncaught Exception: Invalid data store. in /wp-content/plugins/woocommerce/includes/class-wc-data-store.php:107
Stack trace:
#0 /wp-content/plugins/woocommerce/includes/class-wc-data-store.php(139): WC_Data_Store->__construct('admin')
#1 /wp-content/plugins/woocommerce-gateway-stripe/includes/admin/class-wc-stripe-inbox-notes.php(79): WC_Data_Store::load('admin-note')
#2 /wp-content/plugins/woocommerce-gateway-stripe/includes/admin/class-wc-stripe-inbox-notes.php(37): WC_Stripe_Inbox_Notes::should_show_marketing_note()
#3 /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-apple-pay-registration.php(235): WC_Stripe_Inbox_Notes::notify_on_apple_pay_domain_verification(true)
#4 /wp-includes/class-wp-hook.php(287): WC_Stripe_Apple_Pay_Registrati

That's where the log I received via email cuts off. The problem was immediately fixed by downgrading tp 4.5.3. My PHP version is 7.3.16. Latest Wordpress and Woocommerce.

**Comment by reykjalin** [comment] 2020-11-17 04:42
We haven't been able to reproduce this bug yet, but we're in the process of releasing an update that we hope will fix the problem.

Since we're not sure if this update will actually address the issue I'm reopening this issue.

**Comment by eldritchgreene** [comment] 2020-11-17 04:44
Thank you @reykjalin I will test when available.

**Comment by reykjalin** [comment] 2020-11-17 05:05
We've done the release, and it should be available in wp-admin within the hour. You can also download the release archive directly from GitHub [here](https://github.com/woocommerce/woocommerce-gateway-stripe/releases/tag/4.5.5).

@eldritchgreene we would love to hear back from you if you're comfortable with trying the update. Please remember to keep a recent backup of your site before you try it, especially if you don't have a staging site! 🙂 

Thank you for reporting the issue!

**Comment by eldritchgreene** [comment] 2020-11-17 05:10
Updated fine, and no more fatal error 👍 good job and thanks @reykjalin !

**Comment by reykjalin** [comment] 2020-11-17 05:13
That's wonderful to hear! So happy that we addressed the issue 😄 

Since this seems to be resolved I'm closing the issue.

If you run into any other problems, feel free to open another issue! Or comment here again if it seems related to this one ☺️

**Closed by reykjalin** 2020-11-17 05:13 UTC
Labels: Priority: CRITICAL

**Comment by dechov** [comment] 2020-11-19 20:13
Looks like it is reproducible with `woocommerce_admin_disabled` filtered to `true`. @eldritchgreene do you have this filter set?

**Comment by eldritchgreene** [comment] 2020-11-22 01:42
@dechov sorry for the delay, yes I do have it! Thanks for checking, and that does solve the mystery.
