### ISSUE TITLE
Ensure gateway does not create duplicate tokens for existing saved tokens

### ISSUE THREAD

**Issue by FangedParakeet** [woocommerce/woocommerce-gateway-stripe#1857] opened 2021-09-14 20:27 UTC
**Describe the bug**

Saving iDEAL or Bancontact payment methods as tokens and then setting either to the default token for an account causes duplicate tokens to be created.

**To Reproduce**
1. Create a new customer account which has no existing saved payment methods.
2. Checkout with Bancontact and elect to save the payment method at checkout.
3. Checkout again with iDEAL and save the payment method as well.
4. Visit My Account -> Payment Methods page.
5. Click "Make default" on either saved payment method.
6. You'll see many payment methods as below:

![image](https://user-images.githubusercontent.com/1534605/133262579-ceda2dbb-da63-4360-b1ce-2e98b347a404.png)

**Expected behavior**

UPE payment gateway should not create duplicate payment tokens for saved payment methods. 

**Screenshots**

There's one a little bit above.

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - Stripe Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**

**Comment by superdav42** [comment] 2021-09-21 11:02
I can't reproduce this on the develop branch now so I guess it's not a problem. @FangedParakeet was never able to reproduce it when was first working on it so I think it's safe to close this and just call it something funky with my env when I was first testing it.

**Comment by FangedParakeet** [comment] 2021-10-18 20:40
Re-opening this mysterious issue, because I have been able to repeat this scenario again slightly more reliably while testing #2071. This bug occurs when a user has saved SEPA payment methods and adds a new payment method. For some reason the SEPA payment methods are duplicated beyond the `posts_per_page` threshold, which causes us to [exit before querying Stripe for new saved payment methods](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/class-wc-stripe-payment-tokens.php#L232-L236).

I'm not sure why the legacy function [woocommerce_get_customer_payment_tokens_legacy](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/class-wc-stripe-payment-tokens.php#L142) would be called with the UPE enabled--though I've seen stranger things happen with payment tokens--but I noticed that in said function, we track `$stored_tokens` to match saved WC Payment Tokens to Stripe Payment Methods (specifically [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/class-wc-stripe-payment-tokens.php#L146-L148), [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/class-wc-stripe-payment-tokens.php#L172), and [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/class-wc-stripe-payment-tokens.php#L187)), but we don't perform any action on this `$stored_tokens` array once we have a list of existing WC Payment Tokens that no longer exist on Stripe's side. Adding [this logic](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/class-wc-stripe-payment-tokens.php#L289-L296) to remove tokens that no longer exist on Stripe's side to the function `woocommerce_get_customer_payment_tokens_legacy` appeared to resolve this issue of duplicate tokens for me, but this should probably be tested more comprehensively by whoever decides to investigate this further.

**Closed as completed** 2021-11-01 17:48 UTC
Labels: type: bug, component: UPE
