### ISSUE TITLE
Apple Pay charging incorrect amount when there's `'` or `"` in variation attribute name

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-stripe#1129] opened 2020-01-28 14:53 UTC
**Affected tickets**
2666923-zen

**Describe the bug**
When a product has multiple variations at different prices, and the variation attribute name has `'` or `"` characters in it, Apple Pay will always charge the price of the cheapest variation, no matter which variation I've selected. This problem doesn't happen for products that only have alphanumeric characters in variation names.

**To Reproduce**
1. Create a variable product with one attribute and at least 2 values that have `'` or `"` in their name, for example `3'4"`, `3'6"`:
![Screenshot](https://d.pr/i/TJDR9i+)
Screenshot: https://d.pr/i/TJDR9i
2. Create variations out of this attribute and assign different price to each.
3. Go to the product page and select a variation that is not the cheapest one:

![Screenshot](https://d.pr/i/itwtIF+)
Screenshot: https://d.pr/i/itwtIF

4. Click the Apple Pay button and observe we're instead being charged the price of the cheapest variation, even if the selected one is different:

![Screenshot](https://d.pr/i/M7M5YF+)
Screenshot: https://d.pr/i/M7M5YF

**Expected behavior**
I am charged the price of the variation I've selected.

**Screenshots**
See above

**Environment (please complete the following information):**
 - WordPress Version: 5.3.2
 - WooCommerce Version 3.9.0
 - Stripe Plugin Version 4.3.1 
 - Browser [e.g. chrome, safari] and Version: Safari 13
 - Any other plugins installed

**Comment by madeincosmos** [comment] 2020-01-28 15:03
Replacing quotes with curly quotes in the attribute name solved the problem for me: https://typographyforlawyers.com/straight-and-curly-quotes.html

**Comment by kkmuffme** [comment] 2020-04-19 19:05
This is a major bug that actually makes the plugin unusable

**Comment by reykjalin** [comment] 2020-06-19 19:41
I'm unable to reproduce this in the following environment:

- WordPress Version: 5.4.2
- WooCommerce Version: 4.2.0
- Stripe Plugin Version: 4.4.0
- Browser: Safari 13.1.1
- Other Plugins: None.

There have obviously been several updates since the issue was reported, and several updates to the payment request buttons specifically in the last couple of months, so I'm going to take some time to downgrade my environment and see if I can reproduce the issue at an earlier version.

@madeincosmos if you have the time it would be of great help if you could check to see if you can reproduce the issue in your current testing environment if you have a one set up. No need to downgrade anything, I'm mostly interested in whether we've addressed this in an update since this issue was created and if this is still an issue.

**Comment by reykjalin** [comment] 2020-06-24 03:46
I've confirmed that this is indeed an issue in the reported version (Stripe v4.3.1), but I can't reproduce this in the latest release (or at least not the current `master` branch) so I'll close this issue.

This seems to have been fixed as a byproduct of some of the payment request button changes that have happened since the issue was reported.

**Closed by reykjalin** 2020-06-24 03:46 UTC
Labels: LPMs/APMs, Priority: Low, [Type] Bug
