### ISSUE TITLE
Would it be possible to somehow collect checkout data fields when the Payment Request button is being used on the checkout page?

### ISSUE THREAD

**Issue by dexter-adams** [woocommerce/woocommerce-gateway-stripe#1338] opened 2020-10-20 13:38 UTC
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/e507add6fe460c2f69d017cd1db455b2563df377/assets/js/stripe-payment-request.js#L32

**Comment by v18** [comment] 2021-03-04 00:03
Hi @dexter-adams 👋 Could you elaborate a bit? Which fields would you like to see collected, and how will you end up using them? If you could also add a list of reproducible steps to see the current problem, that would help a lot. Thank you!

**Comment by thenbrent** [comment] 2023-08-10 04:06
Closing this one due to lack of recent activity. If it's still required, please let us know with some more of the details request by Val previously.

**Closed by thenbrent** 2023-08-10 04:06 UTC
Labels: type: question, component: payment request buttons
