### ISSUE TITLE
on checkout SyntaxError: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by juju921** [woocommerce/woocommerce-gateway-stripe#1091] opened 2019-11-19 10:55 UTC
Hello,

I have a payment concern with stripe that I'm going to pay I have this error that appears
SyntaxError: Unexpected token <in JSON at position 1

and on the debug console he shows me

Unable to fix malformed JSON   checkout.min.js?ver=3.8.0:1

**Comment by v18** [comment] 2021-02-26 06:11
I'm going to close this issue because I'm not able to reproduce on my test site using these steps:
1. Add a product to cart
2. Go to checkout
3. Pay using a test credit card number

@juju921 if you're still having trouble with this, I recommend contacting support directly so they can help narrow down and fix the cause of the issue.

**Closed by v18** 2021-02-26 06:11 UTC
Labels: priority: low, type: bug
