### ISSUE TITLE
[Klarna] Improve messaging when returning to the block checkout on failure

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#3085] opened 2024-04-22 02:25 UTC
**Describe the bug**

When the order amount is too high for Klarna to be processed, no error message is displayed on the Block checkout page when returning to the store.

This may be happening for other APMs that use redirection.

**To Reproduce**
1. On the WooCommerce settings page, set a page using the block checkout as the main Checkout one, at `wp-admin/admin.php?page=wc-settings&tab=advanced`
2. Publish a product that costs USD 10.000
3. Enable Klarna, under the Stripe settings page at `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods`
4. As a shopper, add this product to the cart and go to the checkout page
5. Select Klarna and place the order
6. On the Klarna site, you'll see an error stating you can't use Klarna for this order. Click on the main button to go back to the store
7. When you're back on the store, notice no error message is displayed

https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/03f6740a-6ec5-4165-bd2c-5efecc282e52

**Expected behavior**
As a shopper, I'd expect to see a message on the store when I'm taken back to it after a failed payment attempt.

**Comment by wjrosa** [comment] 2024-05-02 20:46
I think this is related to https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3060

**Comment by annemirasol** [comment] 2024-09-12 17:30
Closing this as the issue is present only in classic themes, e.g. Storefront, and not in block themes, e.g. Twenty-Twenty-Four. [Rubik has been pinged](https://github.com/woocommerce/woocommerce/issues/42787#issuecomment-2346854725), and a [similar woocommerce issue already exists](https://github.com/woocommerce/woocommerce/issues/51272).

**Closed as completed by annemirasol** 2024-09-12 17:30 UTC
Labels: priority: low, type: enhancement
