### ISSUE TITLE
Apple pay/Google pay/Link forces login when buying Subscription products

### ISSUE THREAD

**Issue by raindeer** [woocommerce/woocommerce-gateway-stripe#3639] opened 2024-12-05 15:40 UTC
**Describe the bug**
When trying to pay for a Subscription with Apple pay/Google pay/Link and not being logged in you are forced to login. It works as expected if you pay with card. And this worked in previous versions.

**To Reproduce**
1. Place subscription product in cart while not being logged in to WP
2. Press Apple pay/Google pay/Link button
3. A popup is shown which says "To complete your transaction with Google Pay, you must log in or create an account with our site." Pressing Ok redirects you to the account login page. The behavior is the same on the checkout page.

The account creation settings in Woocommerce look as follows:
![Image](https://github.com/user-attachments/assets/93bab660-1e60-44a1-908e-dcc47f9818bc)

**Expected behavior**
You should not need to login when paying for a subscription product.
Paying with Card on the checkout pay works as normal without logging in or manually creating an account. 
A user account for the subscription is created automatically in this case.

**Environment (please complete the following information):**
WordPress Version: 6.6.2
WooCommerce Version: 9.3.2
WooCommerce Subscription Version: 6.8.0
Stripe Plugin Version: 8.8.1

**Comment by raindeer** [comment] 2024-12-05 15:43
@annemirasol might be related to the strange Stripe Link behavior and subscriptions.

**Comment by annemirasol** [comment] 2024-12-09 19:58
> might be related to the strange Stripe Link behavior and subscriptions.

The Link and subscriptions issue should be fixed by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3636. It was caused by a bug that set the payment method incorrectly for the confirmation-required flow, e.g. 3D Secure auth cards

The behavior in this issue, i.e. forcing users to log in if paying for subscriptions via Apple Pay/Google Pay/Link (express), looks to be coming from this: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3519dd775bc2b6b574bdd3001ebdb438b60b9697/includes/payment-methods/class-wc-stripe-express-checkout-helper.php#L1281

Next step: We need to investigate if we can support account creation upon checkout, to be consistent with the experience when paying with credit cards.

**Closed as completed** 2024-12-11 16:33 UTC

**Comment by raindeer** [comment] 2024-12-12 10:47
when will this be released?

**Comment by annemirasol** [comment] 2024-12-12 18:25
> when will this be released?

The fix will be included in the `9.1.0` January release.
