### ISSUE TITLE
Checkout Block: Supporting multiple packages in stripe.paymentRequest (express payment)

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gateway-stripe#1504] opened 2021-03-21 18:20 UTC
@nerrad commented on [Wed Apr 08 2020](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2166)

This issue surfaced while working on [woo-blocks/2127](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2127). To quote what I wrote there:

> We'll either have to consider disabling the payment method if there are multiple packages in the order/cart, or setup the [shipping options](https://stripe.com/docs/js/appendix/shipping_option) for the payment method so each option is a combination of the various package selections (since only one option can be selected). The latter can be super complex and grow exponentially depending on the number of packages might exist. I'll create an issue as a followup after this is merged. I should note that I did look at the existing stripe payment gateway extension and how they handle packages is a bit puzzling too...so this may be something that's already a bit of a known issue for express payment methods (might need a p2).

It's entirely possible this is something that should be tackled by a different team as well.

Currently, the payment request payment method is [just pulling the rate details from the first package](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/eb303fe1f7e846d118846c11197779276a6e1dfd/assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/normalize.js#L40-L52).

---

@nerrad commented on [Tue Nov 17 2020](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2166#issuecomment-729147915)

@woocommerce/wc-stripe I'd love to get some thoughts on this issue. Does the Stripe payment request API implementation currently support multiple packages/rates in the shortcode checkout flow? If not, is it disabled in that scenario? What is the expectation/behaviour around that?

---

@github-actions[bot] commented on [Sun Jan 17 2021](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2166#issuecomment-761761886)

This issue has been marked as `stale` because it has not seen any activity within the past 60 days. Our team uses this tool to help surface issues for review. If you are the author of the issue there's no need to comment as it will be looked at.

**Comment by nerrad** [comment] 2021-03-21 18:21
Moved into the Stripe repo as it's a better fit for here.

**Comment by v18** [comment] 2021-04-01 06:10
Thanks @nerrad for opening the issue. I'm not sure I understand it - would you be able to add repro steps please?

**Comment by nerrad** [comment] 2021-04-01 11:59
@Aljullu, the details of this issue when I originally created this in the blocks repo are a bit fuzzy for me too but I know it had to do with the ability for WooCommerce checkout to handle multiple packages in the checkout. Would you be able to help with how to set up a purchase with multiple packages and attempting to checkout using express payments?

**Comment by Aljullu** [comment] 2021-04-01 15:48
Yes, in order to be able to split the order in several packages you need to use an extension. For example, [WooCommerce Advanced Shipping Packages](https://woocommerce.com/products/woocommerce-advanced-shipping-packages/).

These are the testing steps:

1. Install WC Blocks and change the Cart and Checkout shortcodes with the blocks.
2. Install [WooCommerce Advanced Shipping Packages](https://woocommerce.com/products/woocommerce-advanced-shipping-packages/).
3. Go to WooCommerce > Settings > Shipping > Shipping classes and create a shipping class. This is an example one I created:
![imatge](https://user-images.githubusercontent.com/3616980/113316832-0dc8fb80-930f-11eb-81fb-8573209ac60a.png)
4. Go to WooCommerce > Settings > Shipping > Packages and create a package. For example:
![imatge](https://user-images.githubusercontent.com/3616980/113317904-2be32b80-9310-11eb-87c9-fccab46c89a4.png)
5. Edit a product (ie: Sunglasses) and set its shipping class to the one you created.
6. In the frontend, add two products to the Cart (ie: Beanie and Sunglasses).
7. Go to the Cart or Checkout blocks, you should notice there are two packages listed in the shipping options.
![imatge](https://user-images.githubusercontent.com/3616980/113318735-0e629180-9311-11eb-9aca-691423f5e63d.png)
8. Try to pay with Chrome Pay.
9. In the popup, you will notice it lets you choose the shipping method, but **it only handles one package**. (I think this is what this issue is about).

**Comment by reykjalin** [comment] 2021-05-21 00:13
To make sure customers and merchants don't get tripped up by this, maybe we should just start by making sure the Payment Request Buttons don't show up when the order includes multiple packages?

That might be a decent stop-gap for now. I'm not even sure if this is supported by Payment Request.
I know you can give a payment request a list of shipping options, but I'm not sure if you can choose more than one 🤔 

cc @v18

**Comment by v18** [comment] 2021-05-22 06:24
@reykjalin for this issue lets:
- verify: can the payment request API handle multiple packages? if not, let's implement stopgap & close this issue.
- research: is there an existing function in WC (et al) to easily create the data we'd need to send to support multiple packages? if not, let's document what's the data we're looking for?
- decide whether to implement stopgap or full solution depending on the answers above

**Comment by reykjalin** [comment] 2021-06-03 00:03
From glancing through the Payment Request API spec, I think we may have to combine the chosen shipping options into a custom shipping option made in the frontend for the specific order. The `shippingOption` parameter to a payment request [only accepts one item](https://www.w3.org/TR/payment-request/#shippingoption-attribute). The Stripe API doesn't implement any support for multiple packages, there's only the `shippingOptions` array, of which [only one item will be selected](https://stripe.com/docs/js/payment_request/create).

I don't think we do this in the shortcode flow, but that's what I'm looking into next.

**Comment by reykjalin** [comment] 2021-06-03 01:14
So, after testing this with Stripe I can confirm we sort of handle this but we present the options correctly. Currently we just add the possible shipping rates from all packages to the array of shipping options provided to the Payment Request:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/1fc58853fa3c5c64cf1635faf443ceeaa368ff0e/includes/payment-methods/class-wc-stripe-payment-request.php#L930-L945

This causes the Payment Request Dialog to hang when choosing a shipping address because we duplicate some shipping options and the Payment Request doesn't like things having the same IDs:

| Address not yet chosen | It gets stuck loading 😞 | The shipping options |
| :---: | :---: | :---: |
| <img width="861" alt="image" src="https://user-images.githubusercontent.com/13835680/120570905-9b58c280-c408-11eb-844d-2ca74ab21e44.png"> | <img width="861" alt="image" src="https://user-images.githubusercontent.com/13835680/120570918-a6135780-c408-11eb-8a61-70f51fa5303b.png"> | <img width="585" alt="image" src="https://user-images.githubusercontent.com/13835680/120571037-d3f89c00-c408-11eb-8b30-0602d05dcd00.png"> |


## How do we fix this?

We need to do something along the lines of:

1. Retrieve the shipping rates for each package.
2. Retrieve the shipping rates for non-package items.
3. Combine these to create "custom" shipping methods, e.g. "Fragile, Priority" and "Fragile, Free Shipping", etc., allowing people to choose from the different _combinations_ of different options here.

This quickly grows in complexity; if you have 3 products, all with 2 different packaging options, that's `2^3 = 8` combinations we need to present to customers in the Payment Request dialog. 3 products, all with 3 different packaging options is `3^3 = 28` different combinations 😱  

Alternatively we could make it so that we _only_ present the chosen combination of packages **in the cart** to the Payment Request — forcing customers to close the Payment Request Dialog to choose a new shipping option in the cart (i.e. new combination of packages) and then re-opening it to continue the checkout.

The second option is obviously not ideal in terms of UX, but it'd be significantly easier to implement.

<hr />

Finally, we could of course just disable the Payment Request Buttons when we have a cart with multiple packages in it, and instead allow only checkout with a Credit Card or other payment method.

**Comment by reykjalin** [comment] 2021-06-04 22:53
After discussing this in p1622683576178000-slack-C01BZUL57SQ and talking about this with @LevinMedia we decided to hide the Payment Request Buttons when there are multiple packages in the cart because:

1. The [Advanced Shipping Packages extension](https://woocommerce.com/products/woocommerce-advanced-shipping-packages/) is not maintained by Woo and support is not handled by Woo — even though it's sold on WooCommerce.com
1. The functionality is relatively non-standard; you can achieve a similar effect (but not quite the same) using just standard Woo Shipping Classes — and that functionality is fully supported.
1. We couldn't think of a good way to present all the different packaging options in a way that makes sense in the Payment Request Dialog

**Closed as completed** 2021-06-16 01:51 UTC
Labels: component: payment request buttons, priority: medium, component: blocks
