### ISSUE TITLE
[old settings] Payment method description

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1892] opened 2021-09-17 16:56 UTC
## Description

Update the **description and names** for the UPE payment methods from the current placeholder.

Feel free to use either the content from https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/client/payment-methods-map.js or from the designs.

Ensure descriptions are localized with `__( )`.

![Markup 2021-09-17 at 11 56 26](https://user-images.githubusercontent.com/273592/133825893-6444f7ba-7e47-4303-a73b-db173f8b1360.png)

**Comment by c-shultz** [comment] 2021-09-17 20:16
I think this is a duplicate of this: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1773

**Closed as completed** 2021-09-20 16:31 UTC
Labels: priority: high
