### ISSUE TITLE
Properly handle Test Webhooks sent from the Stripe Dashboard

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1258] opened 2020-07-17 22:45 UTC
At least for `charge.captured`, we should return success and log it. When #1200 is implemented, we could display it as the time of the most recently received test webhook.

Properly handling a test webhook sent this way should be independent of the live or test mode the site is set for. See #1136 by @treibalen 

Right now, they 400 (or 500)

<img width="896" alt="Screen Shot 2020-07-17 at 3 43 05 PM" src="https://user-images.githubusercontent.com/1595739/87836328-856bfe80-c844-11ea-9582-7e293b9711f7.png">

**Comment by dougaitken** [comment] 2020-08-04 10:14
As an example - 21565408-hc

The cause was the keys had to be regenerated but no reason given to the customer about why the key needed to be regenerated.

**Comment by v18** [comment] 2021-03-06 09:00
Closing since this is now fixed. I'm able to see successful test webhooks for both webhook types that we handle and those we don't handle (e.g. `account.application.authorized` and `charge.captured`).

**Closed by v18** 2021-03-06 09:00 UTC
Labels: bundle: webhook, component: webhooks, priority: high
