### ISSUE TITLE
Stripe-Apple Pay Bypasses Customer Shipping Selection and Uses Shipping Method Hierarchy

### ISSUE THREAD

**Issue by dreamtooloud** [woocommerce/woocommerce-gateway-stripe#1824] opened 2021-09-09 22:28 UTC
Reported in HC-1077282 / ZD 4282395

**Describe the bug**

_"Whenever customers select our express delivery option on our website but they opt to pay with ApplePay, for some reason apple pay is amending the default shipping method to standard. We have already raised this with Stripe who advised this appears to be a Woocommerce issue."_

This was originally reported in #755 and a pull request was created and later merged to close the issue in #1191 

**In a nutshell:** When a customer puts an item in their cart, selects a shipping option, and then clicks the Apple Pay button, Apple Pay was reverting the shipping option to the first one on the user's list (in this case, it was free shipping and was 7-10 business days instead of the 2-3 the customer wanted when they selected "express") . 

We rectified this by changing the order of the shipping options under WooCommerce-->Settings-->Shipping-->Manager shipping zone. User's site now reflects express delivery first. 

**However:** When we tested using free shipping(the second option in shipping methods hierarchy), Apple Pay was now pulling the Express Shipping option as default. This seems very much related to #755 

**To Reproduce**
1. Enable Apple Payments in Stripe on a test site and set up an Apple Pay Account
2. Create a Shipping Zone and at least two shipping methods in WooCommerce-->Settings-->Shipping-->Shipping Zones--->Edit Shipping Zone-->Add Methods 
3. Check box to allow for all shipping methods to be displayed to the customer
4. Go to shop page and add a product to the cart
5. Go to check and select the shipping method that comes second in your shipping methods hierarchy. 
6. Select Buy with Apple Pay
7. Apple Pay pulls shipping method from hierarchy not the one selected by the customer. 

**Expected behavior**
Apple Pay will pull the selected shipping method to the Apple Pay window

**Environment (please complete the following information):**
 - WordPress Version: 5.8
 - WooCommerce Version: 5.6
 - Stripe Plugin Version: 5.4.1 
 - Browser [e.g. chrome, safari] and Version: ?
 - Any other plugins installed (These are from the user's site): 
 

**Additional context**
I was not able to test on a clean test site because I don't have Apple Pay set up (my test sites are all on staging/sandbox modes). 

I did test the user's website: www.alfredco.com and wasn't able to reproduce since I had a shipping address outside the shipping zone that was created (it defaulted me to a shipping method that was for "all other shipping locations"--So that is actually an expected behavior based on the PR at #1191 . ) 

You can switch shipping methods in the Apple Pay box but user expressed some concern that their customers would still be making mistakes about shipping if they didn't review the Apple Pay box before clicking submit (again, this is expected after PR #1191 ) 

This is looking like a fringe case but but it was recommended to open a report since it is very similar to #755

**Comment by solstudioim** [comment] 2021-09-14 06:18
I wasn't able to replicate the issue.

I have two shipping methods in UK Zone that I created, then I selected the second one (Express).

When I clicked buy with Apple Pay, consistently the second option was selected. Even after adding my details, the selected shipping method stayed the same:

![merge_from_ofoct (1)](https://user-images.githubusercontent.com/17371139/133207154-aa62a74c-2fa4-4f7c-b741-22deeb9e70cb.jpeg)


I used Apple Simulator iPhone X on iOS 12.0



<details>
  <summary>My site SSR</summary>
  
`
### WordPress Environment ###

WordPress address (URL): https://solsubs.mystagingwebsite.com
Site address (URL): https://solsubs.mystagingwebsite.com
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.23
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.78.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.31-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: wp_
Total Database Size: 52.34MB
Database Data Size: 32.18MB
Database Index Size: 20.16MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.83MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fakenames: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 1.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 1.19MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.50MB + Index: 0.52MB + Engine InnoDB
wp_email_log: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.08MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 10.42MB + Index: 11.53MB + Engine InnoDB
wp_posts: Data: 2.19MB + Index: 0.75MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.14MB + Index: 0.17MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 1.06MB + Index: 0.19MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.14MB + Index: 0.19MB + Engine InnoDB
wp_wc_order_stats: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.25MB + Index: 0.58MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_zapier_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1091
aw_workflow: 19
customize_changeset: 4
custom_css: 1
def_reg_fields: 10
elementor_library: 1
event_ticket: 6
fgf_rules: 1
fme_upload_files: 1
nav_menu_item: 6
page: 20
post: 1
product: 434
product_variation: 1093
revision: 36
shop_coupon: 5
shop_order: 1183
shop_order_refund: 4
shop_subscription: 229
wc_booking: 4
wc_membership_plan: 1
wc_user_membership: 10

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.6.1
AutomateWoo: by WooCommerce – 5.5.1
Facebook for WooCommerce: by Facebook – 2.6.4
Order Simulator for WooCommerce: by 75nineteen Media LLC – 1.0.2
Custom User Registration Fields for WooCommerce: by Addify – 1.7.2
CTX Feed: by WebAppick – 4.4.14
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.30
WooCommerce Stripe Gateway: by WooCommerce – 5.4.1
WooCommerce PayPal Payments: by WooCommerce – 1.5.1
WooCommerce Subscriptions: by WooCommerce – 3.1.4
WooCommerce: by Automattic – 5.6.0

### Inactive Plugins (68) ###

Action Scheduler - Disable Default Queue Runner: by Prospress Inc. – 1.0.0
Advanced Database Cleaner: by Younes JFR. – 3.0.3
Akismet Anti-Spam: by Automattic – 4.1.12
All-in-One WP Migration: by ServMask – 7.44
Bulk Edit Products, Prices & Attributes for Woocommerce: by ELEX – 1.0.3
Clean Options: by Mittineague – 1.3.2
Code Snippets: by Code Snippets Pro – 2.14.1
Combine Reviews for WooCommerce: by Ahmad Shyk – 1.0.0
Customer Upload Files for WooCommerce: by FME Addons – 1.0.4
Elementor: by Elementor.com – 3.4.3
Email Log: by Sudar – 2.4.5
Extend WooCommerce Subscription Intervals: by Brent Shepherd – 1.0
Facebook for WordPress: by Facebook – 3.0.5
Free Gifts for WooCommerce: by FantasticPlugins – 6.2
Jetpack: by Automattic – 10.1
JSM's Show Post Metadata: by JS Morisset – 1.3.0
JSON Content Importer: by Bernhard Kux – 1.3.12
Maybe Pass requests through Moesif: by Will Brubaker – 0.1b
Multi Currency for WooCommerce: by VillaTheme – 2.1.7
My Database Admin: by wpshrike – 1.1.22
PayPal Sandbox IPN Tester: by WooThemes – 1.0.0
Plugins Garbage Collector (Database Cleanup): by Vladimir Garagulya – 0.12
Query Monitor: by John Blackbourn – 3.7.1
Say What?: by Ademti Software – 2.0.2
Subscription Box For WooCommerce: by Codup – 1.1.3.4
Subscriptions Add-On for WooCommerce: by Codup – 1.2.9.5
Transients Manager: by Pippin Williamson – 1.8.1
Turbo Admin: by Ross Wintle – 1.0.3
User Role Editor: by Vladimir Garagulya – 4.60.1
User Switching for WooCommerce: by Krokedil – 2.0.1
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.45 (update to version 4.1.46 is available)
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.24
WooCommerce Account Funds: by Themesquad – 2.3.11 (update to version 2.5.3 is available)
WooCommerce Admin Custom Order Fields: by SkyVerge – 1.15.1
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.5.0 (update to version 3.6.2 is available)
WooCommerce Blocks: by Automattic – 5.6.0
WooCommerce Bookings: by WooCommerce – 1.15.37 (update to version 1.15.43 is available)
WooCommerce Box Office: by WooCommerce – 1.1.32 (update to version 1.1.35 is available)
WooCommerce Brands: by WooCommerce – 1.6.24 (update to version 1.6.25 is available)
WooCommerce Checkout Field Editor: by WooCommerce – 1.6.0 (update to version 1.6.2 is available)
WooCommerce Composite Products: by SomewhereWarm – 8.2.0 (update to version 8.3.0 is available)
WooCommerce Deposits: by WooCommerce – 1.5.6 (update to version 1.5.7 is available)
WooCommerce Dynamic Pricing: by Element Stark – 3.1.24 (update to version 3.1.26 is available)
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.1
WooCommerce Memberships: by SkyVerge – 1.21.7 (update to version 1.22.5 is available)
WooCommerce Multi-currency: by TIV.NET INC – 2.14.0 (update to version 2.14.1 is available)
WooCommerce Name Your Price: by Kathy Darling – 3.2.3 (update to version 3.3.2 is available)
WooCommerce Order Barcodes: by WooCommerce – 1.3.23 (update to version 1.3.24 is available)
WooCommerce Order Delivery: by Themesquad – 1.9.0 (update to version 1.9.3 is available)
WooCommerce Payments: by Automattic – 2.9.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.2
WooCommerce Product Bundles: by SomewhereWarm – 6.11.1 (update to version 6.12.1 is available)
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.41 (update to version 1.10.46 is available)
WooCommerce Shipping & Tax: by WooCommerce – 1.25.18
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.14 (update to version 2.3.15 is available)
WooCommerce Store Credit: by Themesquad – 3.6.1 (update to version 3.9.1 is available)
WooCommerce Subscription Downloads: by WooCommerce – 1.1.31
WooCommerce Subscriptions - Custom Price String: by Prospress Inc. – 1.0.4
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.1.0
WooCommerce USPS Shipping: by WooCommerce – 4.4.51 (update to version 4.4.63 is available)
WooCommerce Waitlist: by Neil Pie – 2.2.4 (update to version 2.3.0 is available)
WooCommerce Zapier: by OM4 Software – 2.0.8 (update to version 2.2.1 is available)
WordPress Importer: by wordpressdotorg – 0.7
WP Crontrol: by John Blackbourn & crontributors – 1.10.0
WP phpMyAdmin: by Puvox.software – 5.1.1
WP Rollback: by Impress.org – 1.7.1
WP STAGING: by WP-STAGING – 2.8.5
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.1.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP STAGING Optimizer: by René Hermenau – 1.4.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
box (box)
bundle (bundle)
composite (composite)
deposit (deposit)
external (external)
grouped (grouped)
simple (simple)
store_credit (store_credit)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.8.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://solsubs.mystagingwebsite.com
Subscription Statuses: trash: 4
wc-active: 146
wc-expired: 14
wc-pending: 3
wc-on-hold: 49
wc-cancelled: 13

WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

other: trash: 1
wc-active: 3
wc-expired: 2

Stripe: trash: 2
wc-active: 9
wc-cancelled: 12
wc-expired: 8
wc-on-hold: 9


### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders


### All Products for WooCommerce Subscriptions ###

Template Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: Yes
Shop country code: US
PayPal card processing available in country: Yes
Pay Later messaging available in country: Yes
Vault enabled: Yes

### Action Scheduler ###

Canceled: 3
Oldest: 2021-08-27 03:27:43 +0000
Newest: 2021-09-14 01:14:24 +0000

Complete: 3,159
Oldest: 2021-08-18 08:07:52 +0000
Newest: 2021-08-28 14:18:04 +0000

Failed: 1
Oldest: 2021-05-18 05:36:45 +0000
Newest: 2021-05-18 05:36:45 +0000

Pending: 202
Oldest: 2021-09-14 21:53:41 +0000
Newest: 2024-09-10 04:06:52 +0000


### Status report information ###

Generated at: 2021-09-14 06:17:44 +00:00
`
</details>

**Comment by phillipcornwell** [comment] 2022-01-13 23:28
4684886-zen

**Comment by MoonshotMG** [comment] 2022-01-17 20:01
We are having the same issue on our website as well - www.phyts-usa.com 

All orders over $75+, after discount, qualify for Free Shipping. The Free Shipping zone is setup in WooCommerce and displays as the first shipping option in WooCommerce. 

![Screen Shot 2022-01-17 at 1 57 49 PM](https://user-images.githubusercontent.com/97914799/149830566-cfd09ad9-f72a-4b32-b592-fd004d3f9ed1.png)

But for some reason, when a qualifying order selects Apple Pay, it's defaulting to the $6 Flat Rate Shipping and will now allow the user to select anything but that option. End result, we're charging a qualified customer for shipping when it should be free. Resulting in lots of refunds on our transactions. 

I have reached out to Stripe support to review and they gave us the all clear that the problem was not on their side. After contacting WooCommerce support and providing admin credentials, they spent a full day testing and were able to determine it was indeed a bug but did not provide a resolution. They recommended keeping an eye on this thread and disabling Apple Pay for the time being. 

Any chance for a resolution soon?

**Comment by jacoswan** [comment] 2022-02-04 12:26
Another case similar to the OP reported in 33846991-hc

**Comment by emailgeeks** [comment] 2022-02-06 00:04
Is there an ETA on when this will be fixed? 
I have multiple clients using Stripe, that want to enable Apple Pay but with it not working correctly with delivery options I can't enable it for them. It's very frustrating. I have been watching this for months now and still no solution. I expect better from Woocommerce.

**Comment by darcie** [comment] 2022-05-27 22:24
5250423-zen reported this as well.

**Comment by LazVegas** [comment] 2022-06-28 18:01
5250423 here - spouse-ly.com.  We are seeing the same issue with Google Pay as well.

**Comment by LazVegas** [comment] 2022-06-30 23:57
Express Pay (Google Pay and Apple Pay shipping) is not properly syncing with WooCommerce.

You can see this issue live on our [staging site](https://wordpress-618231-2068638.cloudwaysapps.com/).
> Select this [product](https://wordpress-618231-2068638.cloudwaysapps.com/product/wine-time-t-shirt/), choose any color and size, Add to cart, Checkout
> Complete the Billing details (you will see 4 shipping options).
> Note the default - Flat Rate: $5:00, Total: $21.26, select Buy with GPay/ApplePay.  The Order summary will be correct: $21.26.
> Choose a Shipping address.  The Order summary will be correct: $21.26.
> Change the Shipping method to Local Pickup: The Order will be incorrect $21.26 (It should be $16.26)

> Close GPay/ApplePay, Select WooCommerce Local Pickup.  The Order will be correct: $16.26.
> Select Buy with GPay/ApplePay.  The order will be correct: $16.26.
> Choose a Shipping address.  The Order will be incorrect: $21.26 (It should be $16.26).

> Choose any Shipping method and it (shipping) doesn't update (as a side note, tax does update).

Express Pay shipping is not syncing with WooCommerce.

**Comment by ChrissiePollock** [comment] 2022-09-24 16:03
Reported again on #5566563-zen.

**Comment by ChrissiePollock** [comment] 2022-09-27 10:46
@woocommerce/fractal do we have any idea of the priority of this issue?

**Comment by asumaran** [comment] 2022-09-27 18:13
I'll take a look into this.

**Comment by asumaran** [comment] 2022-09-28 19:58
@ChrissiePollock The problem is that we do not share the address entered by the user in the checkout form with Apple Pay. It's not sure that the Apple Pay dialog will show the same shipping options in the Apple Pay dialog. To select a shipping method, we'd need to set the addresses shown in Apple Pay, which we can't currently do.

I'm not sure we can fix this. The address Apple Pay uses to get the shipping options is out of our control. We could try to set the initial shipping options shown in the Apple pay dialog, but it will be replaced as soon as a shipping address is selected in the Apple pay dialog (if the user has a saved address, it will be replaced immediately). /cc @diegocurbelo

**Comment by ChrissiePollock** [comment] 2022-10-02 16:35
@asumaran Thanks for the followup and looking into it.

**Comment by asumaran** [comment] 2022-10-03 17:28
We discussed this issue internally and agreed this issue can't be fixed for now. Unless Apple Pay (and the Stripe JS library) provide a way to set the address on the Apple Pay dialog, there's no reliable way to fix this. I am closing this issue for now.

**Closed as completed by asumaran** 2022-10-03 17:28 UTC
Labels: priority: low, type: support request, component: payment request buttons, needs repro

**Comment by grygaklym** [comment] 2024-12-03 12:46
Any chance this issue can be reopened? As it's still a concern.

**Comment by Kouzi99** [comment] 2026-08-16 12:33
I am also insteresting in fix for this
