### ISSUE TITLE
Handle order transitions when payment fails

### ISSUE THREAD

**Issue by AzRieilStuff** [woocommerce/woocommerce-gateway-stripe#1561] opened 2021-05-14 08:20 UTC
Plugin has about 20 scenarios when order status moving to “failed”. Mostly, its about the payment failed on some stage.

The problem is, due to my site functionality, I attach some important data to order & order items at moment of order creation ( pending status ), and if user, at checkout, failed payment for some reason, I want to redirect him back and continue checkout, offering another payment method, or another data ( try another credit card, sepa IBAN, etc )

But I cant proceed it without failed order as its failed. I made a solution with `wc_order_is_editable` filter and remove “failed” as non-editable status, but its quite bad solution, also inflicts unpleasant order transition as `woocommerce_order_status_failed_to_completed`.

My ask is – can we provide extra filter/action at these scenarios and give ability prevent order failing on payment errors with our own code?

Thanks

**Comment by reykjalin** [comment] 2021-05-19 17:42
Hi @AzRieilStuff 👋 

I'm not sure I understand what the problem is and what it is you're trying to achieve. Can you let me know if any of the following scenarios are what's happening? If not can you give me a better description of what scenario it is that you have in mind?

## Scenario 1

1. Customer pays for order
2. Customer is shown the "Order Received" page
3. Something fails during payment processing and the payment is not completed successfully (e.g. SEPA payment that can take a couple days to process fails).
4. Order status is set to "failed"
5. You wan't to redirect the customer somehow to the checkout page so they can retry (even though ~1 day may have passed)?

## Scenario 2

1. Customer attempts to pay for order
2. Card is rejected
3. Customer should stay on checkout page so they can retry the payment?

<hr />

For scenario 1 you can direct your customers to **My Account > Orders**, find the order that failed, and ask them to click the **Pay** button to pay for the order. You can also send them a direct link to this page by going to **WP-Admin > WooCommerce > Orders > `failed_order` > Customer Payment Page** and sending them the link to that page.

| My Account Page | WP-Admin |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/13835680/118858235-74f33d00-b8c8-11eb-908a-49ab865d8142.png) | ![image](https://user-images.githubusercontent.com/13835680/118858473-b97ed880-b8c8-11eb-91f6-5863d96897f4.png) |



Scenario 2 is what's supposed to happen with the payment gateway, i.e. the customer should stay on the Checkout page if a payment fails.

<img src="https://user-images.githubusercontent.com/13835680/118858948-327e3000-b8c9-11eb-9e8b-1dce4b8af1e3.png" width="400px" />

If this ^ is not what's happening there may be an issue with either your theme, a conflicting plugin, or the Stripe plugin and that's something we should look into in more detail.

**Comment by AzRieilStuff** [comment] 2021-05-20 06:42
hi o/ thx for response
Im talking not about frontend part or behavior, but these backend code parts
![image](https://user-images.githubusercontent.com/54263505/118931290-7c115e00-b94f-11eb-93b3-efbcaf998fb6.png)

scenario 1
So this scenario is about payments that can take some time. Im ok with behavior we have there 
 - user confirm payment
 - order become "on-hold"
 - redirect to "order-received" page
but then

> 5. You wan't to redirect the customer somehow to the checkout page so they can retry (even though ~1 day may have passed)?

In this case I want to prevent order status transition to failed - instead of this I want to return order to pending status with some internal note "payment have not succeeded"

scenario 2 is mostly the same - we got a response almost instantly. User redirects to order-received ( and its ok ), but my ask is about handle payment errors instead of "failing" order

Technically, its just replacement of string like
`$order->update_status( 'failed' );` or `$order->update_status( 'failed', 'error text' );`
to (1)
```
do_action( 'stripe_order_payment_fails`, 'your_handler', $order, 'some_error_code_like_sepa_say_no' ... )
function your_handler($order){
	$order->update_status('failed');
}
```
or (2)
```
$order_status = apply_filters('stripe_order_status_failed', 'failed', $some_useful_data_to_determine_error_type);
$order->update_status($order_status);
```

In this case I can disable default conduct action (1) or add filters(2) and return order to pending, send user some nice notifications and etc.

**Comment by reykjalin** [comment] 2021-05-25 16:36
> In this case I want to prevent order status transition to failed - instead of this I want to return order to pending status with some internal note "payment have not succeeded"

Ok, I think I understand what you're asking now; you want to prevent the order status from going to `failed` when a payment fails. Let me know if that's not correct 🙂 

We will not implement anything like this in the Stripe plugin itself because this is already possible with hooks available in WooCommerce; `woocommerce_order_status_<from-status>_to_failed` and `woocommerce_status_failed`. You can see where these hooks are registered [here](https://woocommerce.github.io/code-reference/files/woocommerce-includes-class-wc-order.html#source-view.372).

An example of how you might use these:

```php
add_action( 'woocommerce_order_status_processing_to_failed', 'prevent_status_failed' );

function prevent_status_failed( $order_id, $order ) {
    // Process the order's status however you like.
}
```

And

```php
add_action( 'woocommerce_order_status_changed', 'handle_order_status_changes' );

function handle_order_status( $order_id, $from_status, $to_status, $order ) {
    // Assuming we only want to do something when an order changes from "processing"
    // to "failed".
    if ( 'processing' !== $from_status && 'failed' !== $to_status ) {
        return;
    }
    // Process the order's status however you like.
}
```

[There is also the `woocommerce_payment_status_changed` action](https://woocommerce.github.io/code-reference/files/woocommerce-includes-class-wc-order.html#source-view.387) which may be of more interest to you.

I'll close this issue and label it as `category: won't fix` for now, but if it turns out I misunderstood something, please re-open this issue and add a comment to it 🙂 
I hope this helps!

**Closed as completed by reykjalin** 2021-05-25 16:36 UTC

**Comment by AzRieilStuff** [comment] 2021-05-25 17:21
> Let me know if that's not correct 

almost. I want to catch it and decide should I proceed default scenario or handle it, prevent status change and extra actions

> this is already possible with hooks

well, no
Indeed, there are some hooks, but actions in `WC_Order::status_transition` are not able to prevent transition I want to avoid.
Its can be used like - just call `set_status` again inside a hook of any  `set_status` actions but its not the best solution, as not a preventing, but "repairing" already failed order.

`WC_Order::$status_transition` is not editable ( protected ) and not passed by ref into actions.
Also no filters at `set_status` or `update_status`
For now, Stripe plugin is the only side who decide that "failed payment => failed order" and I cant find any workaround;

Also its problematic to determine conrecte reason why payment fails as there is no mechanism which would store error code - like - was card number invalid, or declined for another reason.

**Comment by reykjalin** [comment] 2021-05-28 18:51
> I want to catch it and decide should I proceed default scenario or handle it, prevent status change and extra actions

This looks like you want to change the whole order status processing when an order fails. You can already do this through the `set_status` hooks like you already mentioned, although you're right in that you can't prevent the order from moving temporarily to `failed`.

> its problematic to determine conrecte reason why payment fails as there is no mechanism which would store error code

We add order notes when a payment fails, with the information we have available, and those should at least give you an idea of why an order fails. If you need more details you can also look at your Stripe Dashboard or enable debug logs and read through those.

| Order note | Debug log |
| :---: | :---: |
| <img width="294" alt="image" src="https://user-images.githubusercontent.com/13835680/120028095-c47deb00-bfe3-11eb-903d-6b27c46f0e83.png"> | <img width="688" alt="image" src="https://user-images.githubusercontent.com/13835680/120029396-8da8d480-bfe5-11eb-8112-4aca29753390.png"> |


>Stripe plugin is the only side who decide that "failed payment => failed order" and I cant find any workaround

Based on our conversation it seems like you want to change the order status to something other than `failed`, and you can already achieve this by setting the status to something else whenever it's set to failed via hooks.

Setting the order to `failed` is intended behaviour on our part because of how the Order Status is really composed of "Payment Status" and "Shipping Status". The payment failed, and thus the order fails.

There is nothing stopping a customer from attempting another payment on the same order, or you from implementing custom behaviour on top of that, so we don't see the benefit of adding the filters you're requesting.
