### ISSUE TITLE
Woocommerce stripe gateway missbehave on Shop Page

### ISSUE THREAD

**Issue by shamskabra** [woocommerce/woocommerce-gateway-stripe#1360] opened 2020-11-07 14:26 UTC
**When plug in active the gallery image on product page dose not show, variable product dose not change, Price for selected product dose not show.**
when the stripe plugin is deactive every thing works fine only when plug in actived 
1. The gallery image on product page dose not show, 
2. Variable product dose not change, 
3. Price for selected product dose not show.
**To Reproduce**
1. Go to 'Shop page'
2. Click on 'Veriable product ( in my case ther is Pulse Oximeter )'
3. See the color swatch and brand swatch 'Changing clor dose not change the product, Gallery image dose not apper under the product, Price dose not appear under Add to Cart button.'

**Expected behavior**
When plugin is deactive or Active but in the setting Enable test mode is un checked then everything works fine.

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version 5.5.3
 - WooCommerce Version 4.6.1
 - Stripe Plugin Version 4.5.3
 - Browser Chrome 86.0.4240.183 (Official Build) (64-bit)
 - Any other plugins installed, Bundled Plugins comes with Woodmart theme plug ins are as under
1. Contact Form 7
2. MC4WP: Mailchimp for WordPress
3. Safe SVG
4. Slider Revolution
5. WooCommerce
6. Woodmart Core
7. WPBakery Page Builder
![plugin active](https://user-images.githubusercontent.com/64584674/98443715-319c6280-211e-11eb-8206-a66ead14cd4b.jpg)
![plug in deactivated](https://user-images.githubusercontent.com/64584674/98443725-4d076d80-211e-11eb-813c-58b329beb817.jpg)

**Additional context**

**Comment by dougaitken** [comment] 2023-01-20 13:58
_To ensure the WooCommerce team are having the most impactful work, we review older open Issues on this GitHub repository to find out what is still relevant._ 

I appreciate some time has passed since the original comment, thanks for your patience.

It is possible that this issue has been fixed by a more recent release as I’ve been unable to replicate the issue you described using the latest release of the core WooCommerce plugin and the [WooCommerce Stripe Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/). 

As I’m unable to reproduce this, I’m marking this Issue as Closed. If you feel this is still relevant and requires attention, please post a [new Issue](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/new/choose) with some more details, including the results of any conflict testing.

**Closed** 2023-01-20 14:21 UTC
